/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
public final class AnimationCache {
    private static SpriteData[] animationDataById;
    private static short[] petFrameXOffsets;
    private static short[][] petAnimations;

    public static void initialize() {
        animationDataById = new SpriteData[1000];
    }

    public static SpriteData getAnimationData(int spriteId) {
        if (animationDataById[spriteId] == null) {
            AnimationCache.animationDataById[spriteId] = new SpriteData();
            byte[] byArray = new byte[20000];
            int[] nArray = new int[]{0};
            short[][] sArray = new short[5][4];
            EngineUtils.a(byArray, "/data/spr/spr_" + spriteId + "_all(r)");
            AnimationCache.animationDataById[spriteId].modules = EngineUtils.readFlatShorts(byArray, nArray);
            if (spriteId >= 86 && spriteId <= 185) {
                AnimationCache.animationDataById[spriteId].frames = EngineUtils.readShortMatrix(byArray, nArray);
                for (int i = 0; i < sArray.length; ++i) {
                    for (int j = 0; j < 4; ++j) {
                        sArray[i][j] = j == 1 ? (short)(AnimationCache.animationDataById[spriteId].frames[0][j] + petFrameXOffsets[i]) : AnimationCache.animationDataById[spriteId].frames[0][j];
                    }
                }
                AnimationCache.animationDataById[spriteId].frames = sArray;
                AnimationCache.animationDataById[spriteId].animations = EngineUtils.readShortMatrix(byArray, nArray);
                AnimationCache.animationDataById[spriteId].animations = petAnimations;
            } else {
                AnimationCache.animationDataById[spriteId].frames = EngineUtils.readShortMatrix(byArray, nArray);
                AnimationCache.animationDataById[spriteId].animations = EngineUtils.readShortMatrix(byArray, nArray);
            }
            AnimationCache.animationDataById[spriteId].collisionRegions = AnimationCache.groupRegionsByFrame(EngineUtils.readFlatShorts(byArray, nArray), AnimationCache.animationDataById[spriteId].frames.length);
            AnimationCache.animationDataById[spriteId].attackRegions = AnimationCache.groupRegionsByFrame(EngineUtils.readFlatShorts(byArray, nArray), AnimationCache.animationDataById[spriteId].frames.length);
        }
        ++AnimationCache.animationDataById[spriteId].referenceCount;
        return animationDataById[spriteId];
    }

    private static short[][] groupRegionsByFrame(short[] regions, int frameCount) {
        if (regions == null) {
            return null;
        }
        short[][] sArrayArray = new short[frameCount][];
        for (int i = 0; i < regions.length / 5; ++i) {
            sArrayArray[regions[i * 5]] = EngineUtils.a(sArrayArray[regions[i * 5]], new short[]{regions[i * 5 + 1], regions[i * 5 + 2], regions[i * 5 + 3], regions[i * 5 + 4]});
        }
        return sArrayArray;
    }

    public static void releaseAnimationData(int spriteId) {
        --AnimationCache.animationDataById[spriteId].referenceCount;
        if (AnimationCache.animationDataById[spriteId].referenceCount <= 0) {
            AnimationCache.animationDataById[spriteId].referenceCount = 0;
            AnimationCache.evictAnimationData(spriteId);
        }
    }

    public static boolean evictAnimationData(int spriteId) {
        if (animationDataById[spriteId] != null) {
            AnimationCache.animationDataById[spriteId].referenceCount = 0;
            AnimationCache.animationDataById[spriteId] = null;
            return true;
        }
        return false;
    }

    static {
        petFrameXOffsets = new short[]{0, 10, 3, 7, -10};
        petAnimations = new short[][]{{2, 0}, {1, 0, 1, 1, 1, 2, 1, 3, 1, 2}, {5, 0, 5, 4}};
    }
}

