/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
public abstract class BaseInputHandler {
    protected boolean inputEnabled;
    private BaseInputHandler inputDelegate;
    private int heldKeys;
    private int pressedKeys;
    private int releasedKeys;
    private int frameHeldKeys;
    private int framePressedKeys;
    private int frameReleasedKeys;
    private int pointerX = -1;
    private int pointerY = -1;

    public void onKeyPressed(int keyCode) {
        int n = BaseInputHandler.keyCodeToMask(keyCode);
        this.pressedKeys |= n;
        this.heldKeys |= n;
        if (this.inputDelegate != null) {
            this.inputDelegate.onKeyPressed(keyCode);
        }
    }

    public void onKeyReleased(int keyCode) {
        int n = BaseInputHandler.keyCodeToMask(keyCode);
        this.releasedKeys |= n;
        this.heldKeys &= ~n;
        if (this.inputDelegate != null) {
            this.inputDelegate.onKeyReleased(keyCode);
        }
    }

    public void setInputEnabled(boolean enabled) {
        this.resetInputState();
        this.inputEnabled = enabled;
    }

    public void resetInputState() {
        this.heldKeys = 0;
        this.pressedKeys = 0;
        this.releasedKeys = 0;
        this.frameHeldKeys = 0;
        this.framePressedKeys = 0;
        this.frameReleasedKeys = 0;
        if (this.inputDelegate != null) {
            this.inputDelegate.resetInputState();
        }
    }

    public void onPointerEvent(int x, int y) {
        this.pointerX = x;
        this.pointerY = y;
        if (this.inputDelegate != null) {
            this.inputDelegate.onPointerEvent(x, y);
        }
    }

    private static int keyCodeToMask(int keyCode) {
        switch (keyCode) {
            case 48: {
                return 1;
            }
            case 49: {
                return 2;
            }
            case 50: {
                return 4;
            }
            case 51: {
                return 8;
            }
            case 52: {
                return 16;
            }
            case 53: {
                return 32;
            }
            case 54: {
                return 64;
            }
            case 55: {
                return 128;
            }
            case 56: {
                return 256;
            }
            case 57: {
                return 512;
            }
            case 42: {
                return 1024;
            }
            case 35: {
                return 2048;
            }
            case -1: {
                return 4096;
            }
            case -2: {
                return 8192;
            }
            case -3: {
                return 16384;
            }
            case -4: {
                return 32768;
            }
            case -5: {
                return 65536;
            }
            case -21:
            case -6: {
                return 131072;
            }
            case -22:
            case -7: {
                return 262144;
            }
        }
        return 0;
    }

    public boolean isKeyPressed(int mask) {
        return (this.framePressedKeys & mask) != 0;
    }

    public boolean consumeLeftSoftPointer() {
        if (this.pointerX < 40 || this.pointerX > 85 || this.pointerY < 228 || this.pointerY > 248) {
            return false;
        }
        this.pointerX = -1;
        this.pointerY = -1;
        return true;
    }

    public boolean hasNavigationKeyRelease() {
        return (this.frameReleasedKeys & 0xF154) != 0;
    }

    public boolean isKeyHeld(int mask) {
        return (this.frameHeldKeys & mask) != 0;
    }

    protected void snapshotInput() {
        this.frameHeldKeys = this.heldKeys;
        this.framePressedKeys = this.pressedKeys;
        this.frameReleasedKeys = this.releasedKeys;
        this.pressedKeys = 0;
        this.releasedKeys = 0;
    }

    protected void setInputDelegate(BaseInputHandler delegate) {
        if (this.inputDelegate != null) {
            this.inputDelegate.setInputEnabled(false);
            this.inputDelegate = null;
        }
        if (delegate != null) {
            delegate.setInputEnabled(true);
            this.inputDelegate = delegate;
        }
    }
}

