/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
public class BaseEntity {
    public short[] baseStats;
    public short[] currentStats;
    protected boolean e;
    protected boolean visible;
    protected boolean g;
    protected byte actionState;
    public int posX;
    public int posY;
    public int k;
    public int l;
    public byte m;
    public byte facingDirection;
    public byte o;
    public BaseEntity ownerEntity;
    public int q;
    public int r;
    public int s;
    private short followDistance = (short)10;
    private int[][] followHistory;
    private boolean following = false;

    public final void setCurrentStat(byte statIndex, short value) {
        this.currentStats[statIndex] = value;
    }

    public final short getCurrentHp(byte unusedStatIndex) {
        return this.currentStats[1];
    }

    public void resetCurrentStats() {
        for (int n = 0; n < this.baseStats.length; n = (int)((byte)(n + 1))) {
            int n2 = n;
            short s = this.baseStats[n2];
            n2 = n;
            this.currentStats[n2] = s;
        }
    }

    public final byte getActionState() {
        return this.actionState;
    }

    public final void a(boolean bl) {
        this.e = bl;
    }

    public final boolean i() {
        return this.e;
    }

    public final void setVisible(boolean visible) {
        this.visible = visible;
    }

    public final boolean isVisible() {
        return this.visible;
    }

    public final void c(boolean bl) {
        this.g = bl;
    }

    public final boolean k() {
        return this.g;
    }

    public void setPosition(int x, int y) {
        this.posX = x;
        this.posY = y;
    }

    public final void setFacingDirection(byte direction) {
        this.facingDirection = direction;
    }

    public final int getPosX() {
        return this.posX;
    }

    public final int getPosY() {
        return this.posY;
    }

    public final void movePosX(int dx) {
        this.posX += dx;
    }

    public final void movePosY(int dy) {
        this.posY += dy;
    }

    public void b(int n) {
        this.posX += n;
        this.posY += 4;
    }

    public final boolean moveTowards(int stepSize, int targetX, int targetY) {
        if (this.posX == targetX && this.posY == targetY) {
            return true;
        }
        int n = EngineUtils.a(this.posX, this.posY, targetX, targetY);
        if (n < stepSize) {
            this.posX = targetX;
            this.posY = targetY;
        } else {
            this.movePosX((targetX - this.posX) * stepSize / n);
            this.movePosY((targetY - this.posY) * stepSize / n);
        }
        return false;
    }

    public final void updateFollowing(SpriteRenderer ownerSprite, SpriteRenderer followerSprite) {
        if (!this.following) {
            return;
        }
        if (this.ownerEntity.actionState == 0) {
            return;
        }
        this.followHistory[0][0] = this.ownerEntity.posX;
        this.followHistory[0][1] = this.ownerEntity.posY;
        this.followHistory[0][2] = ownerSprite.animationId;
        this.followHistory[0][3] = this.ownerEntity.facingDirection;
        for (int i = this.followDistance; i > 0; --i) {
            byte by;
            this.followHistory[i][0] = this.followHistory[i - 1][0];
            this.followHistory[i][1] = this.followHistory[i - 1][1];
            this.followHistory[i][2] = this.followHistory[i - 1][2];
            this.followHistory[i][3] = this.followHistory[i - 1][3];
            if (i % this.followDistance != 0) continue;
            this.setPosition(this.followHistory[i][0], this.followHistory[i][1]);
            if (this.followHistory[i][3] == 3) {
                followerSprite.setAnimation((byte)this.followHistory[i][2], (byte)1, false);
            } else {
                followerSprite.setAnimation((byte)this.followHistory[i][2], (byte)this.followHistory[i][3], false);
            }
            this.facingDirection = by = (byte)this.followHistory[i][3];
        }
    }

    public final void startFollowing(byte historySpacing) {
        int n;
        this.following = true;
        this.followHistory = new int[this.followDistance + 1][4];
        for (n = 0; n < this.followDistance + 1; ++n) {
            this.followHistory[n][0] = this.ownerEntity.posX;
            this.followHistory[n][1] = this.ownerEntity.posY;
            this.followHistory[n][3] = this.ownerEntity.facingDirection;
        }
        if (historySpacing >= 0) {
            for (n = 0; n < this.followDistance + 1; ++n) {
                this.followHistory[n][2] = historySpacing;
            }
        }
        switch (this.ownerEntity.facingDirection) {
            case 1: {
                int[] nArray = this.followHistory[10];
                nArray[0] = nArray[0] - this.followDistance;
                break;
            }
            case 3: {
                int[] nArray = this.followHistory[10];
                nArray[0] = nArray[0] + this.followDistance;
                break;
            }
            case 2: {
                int[] nArray = this.followHistory[10];
                nArray[1] = nArray[1] + this.followDistance;
                break;
            }
            case 0: {
                int[] nArray = this.followHistory[10];
                nArray[1] = nArray[1] - this.followDistance;
            }
        }
        this.setPosition(this.followHistory[10][0], this.followHistory[10][1]);
    }

    public final boolean isFollowing() {
        return this.following;
    }

    public final void setOwnerEntity(BaseEntity owner) {
        this.ownerEntity = owner;
    }
}

