/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import game.GameCanvas;
import java.util.TimerTask;

public final class CanvasRepaintTimerTask
extends TimerTask {
    public final void run() {
        GameCanvas.getInstance().repaint();
    }
}

