/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.FilterInputStream;
import java.io.InputStream;
import java.util.Random;
import java.util.Vector;
import javax.microedition.lcdui.Font;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

public final class EngineUtils {
    private static int c = 5;
    private static int d = 300;
    private static int[] e = null;
    private static Random f;
    private static int[][] g;
    private static int[] h;
    private static int[] i;
    private static FormattedTextBuffer j;
    private static char[] k;
    private static int l;
    public static String[] a;
    public static int b;
    private static int m;

    public static short[] a(short[] sArray, short[] sArray2) {
        int n = 0;
        if (sArray != null) {
            n = sArray.length;
        }
        short[] sArray3 = new short[n + sArray2.length];
        if (sArray != null) {
            System.arraycopy(sArray, 0, sArray3, 0, sArray.length);
        }
        System.arraycopy(sArray2, 0, sArray3, n, sArray2.length);
        return sArray3;
    }

    public static void a(byte[] byArray, String object) {
        try {
            if (((String)object).substring(0, 1).endsWith("/")) {
                new Object().getClass();
                object = ResourceStream.openResource((String)object);
            } else {
                new Object().getClass();
                object = ResourceStream.openResource("/" + (String)object);
            }
            object = new DataInputStream((InputStream)object);
            ((FilterInputStream)object).skip(0L);
            ((DataInputStream)object).read(byArray, 0, byArray.length);
            ((FilterInputStream)object).close();
            return;
        }
        catch (Exception exception) {
            System.out.println("GameInf err at getStream()  :  " + exception);
            return;
        }
    }

    public static short[] readFlatShorts(byte[] bytes, int[] cursor) {
        short s = EngineUtils.f(bytes, cursor);
        int n = EngineUtils.f(bytes, cursor);
        if (s == 0) {
            return null;
        }
        short[] sArray = new short[s * n];
        for (n = 0; n < sArray.length; ++n) {
            byte by = bytes[cursor[0]];
            cursor[0] = cursor[0] + 1;
            byte by2 = bytes[cursor[0]];
            cursor[0] = cursor[0] + 1;
            sArray[n] = (short)(by << 8 | by2 & 0xFF);
        }
        return sArray;
    }

    public static short[][] readShortMatrix(byte[] bytes, int[] cursor) {
        int n = EngineUtils.f(bytes, cursor);
        short s = EngineUtils.f(bytes, cursor);
        if (n == 0) {
            return null;
        }
        short[][] sArrayArray = new short[n][];
        for (int i = 0; i < n; ++i) {
            int n2 = EngineUtils.f(bytes, cursor);
            sArrayArray[i] = new short[n2 * s];
            for (n2 = 0; n2 < sArrayArray[i].length; ++n2) {
                byte by = bytes[cursor[0]];
                cursor[0] = cursor[0] + 1;
                byte by2 = bytes[cursor[0]];
                cursor[0] = cursor[0] + 1;
                sArrayArray[i][n2] = (short)(by << 8 | by2 & 0xFF);
            }
        }
        return sArrayArray;
    }

    private static short f(byte[] byArray, int[] nArray) {
        int n = nArray[0];
        nArray[0] = n + 1;
        int n2 = nArray[0];
        nArray[0] = n2 + 1;
        return (short)((byArray[n] & 0xFF) << 8 | byArray[n2] & 0xFF);
    }

    public static InputStream openResource(String path) {
        try {
            "".getClass();
            return ResourceStream.openResource(path);
        }
        catch (Exception exception) {
            return null;
        }
    }

    public static short[][] readShortRows(InputStream input) {
        short[][] sArrayArray = null;
        if (input == null) {
            return null;
        }
        try {
            DataInputStream dataInputStream = new DataInputStream(input);
            int n = dataInputStream.readShort();
            if (n >= 0) {
                sArrayArray = new short[n][];
            }
            for (int i = 0; i < sArrayArray.length; ++i) {
                n = dataInputStream.readShort();
                sArrayArray[i] = new short[n];
                for (n = 0; n < sArrayArray[i].length; ++n) {
                    sArrayArray[i][n] = dataInputStream.readShort();
                }
            }
        }
        catch (Exception exception) {}
        return sArrayArray;
    }

    public static byte[][] readByteRows(InputStream input) {
        byte[][] byArrayArray = null;
        if (input == null) {
            return null;
        }
        try {
            DataInputStream dataInputStream = new DataInputStream(input);
            int n = dataInputStream.readShort();
            if (n >= 0) {
                byArrayArray = new byte[n][];
            }
            for (int i = 0; i < byArrayArray.length; ++i) {
                n = dataInputStream.readShort();
                byArrayArray[i] = new byte[n];
                for (n = 0; n < byArrayArray[i].length; ++n) {
                    byArrayArray[i][n] = dataInputStream.readByte();
                }
            }
        }
        catch (Exception exception) {}
        return byArrayArray;
    }

    public static String[][] readStringRows(InputStream input) {
        Object object;
        String[][] stringArrayArray = null;
        StringBuffer stringBuffer = new StringBuffer();
        try {
            object = new DataInputStream(input);
            int n = ((DataInputStream)object).readShort();
            if (n == 0) {
                return null;
            }
            if (n > 0) {
                stringArrayArray = new String[n][];
            }
            int n2 = 0;
            while (n2 < stringArrayArray.length) {
                n = ((DataInputStream)object).readShort();
                stringArrayArray[n2] = new String[n];
                n = 0;
                while (n < stringArrayArray[n2].length) {
                    int n3 = ((DataInputStream)object).readUnsignedByte();
                    if (n3 == 255) {
                        n3 = ((DataInputStream)object).readShort();
                    }
                    int n4 = 0;
                    while (n4 < n3) {
                        stringBuffer.append((char)((DataInputStream)object).readShort());
                        ++n4;
                    }
                    stringArrayArray[n2][n] = stringBuffer.toString();
                    stringBuffer = new StringBuffer();
                    ++n;
                }
                ++n2;
            }
        }
        catch (Exception exception) {
            object = exception;
            exception.printStackTrace();
        }
        return stringArrayArray;
    }

    public static int a(int n, int n2, int n3, int n4) {
        n = (n - n3) * (n - n3) + (n2 - n4) * (n2 - n4);
        n2 = 0;
        for (n3 = 0x40000000; n3 > 0; n3 >>= 2) {
            if (n >= n2 + n3) {
                n -= n2 + n3;
                n2 = (n2 >> 1) + n3;
                continue;
            }
            n2 >>= 1;
        }
        return n2;
    }

    public static int a(int n, int n2) {
        int n3;
        int n4;
        if (e == null) {
            e = new int[d / c + 1];
            n4 = c * c;
            for (n3 = e.length - 1; n3 >= 0; --n3) {
                EngineUtils.e[n3] = n3 * n3 * n4;
            }
        }
        if (n < 0) {
            return -1;
        }
        if (n <= e[30]) {
            if (n <= e[15]) {
                if (n <= e[5]) {
                    for (n4 = 1; n4 <= 5 && n > e[n4]; ++n4) {
                    }
                } else if (n <= e[10]) {
                    for (n4 = 6; n4 <= 10 && n > e[n4]; ++n4) {
                    }
                } else {
                    for (n4 = 11; n4 <= 15 && n > e[n4]; ++n4) {
                    }
                }
            } else if (n <= e[20]) {
                for (n4 = 16; n4 <= 20 && n > e[n4]; ++n4) {
                }
            } else if (n <= e[25]) {
                for (n4 = 21; n4 <= 25 && n > e[n4]; ++n4) {
                }
            } else {
                for (n4 = 26; n4 <= 30 && n > e[n4]; ++n4) {
                }
            }
        } else if (n <= e[45]) {
            if (n <= e[35]) {
                for (n4 = 31; n4 <= 35 && n > e[n4]; ++n4) {
                }
            } else if (n <= e[40]) {
                for (n4 = 36; n4 <= 40 && n > e[n4]; ++n4) {
                }
            } else {
                for (n4 = 41; n4 <= 45 && n > e[n4]; ++n4) {
                }
            }
        } else if (n <= e[50]) {
            for (n4 = 46; n4 <= 50 && n > e[n4]; ++n4) {
            }
        } else if (n <= e[55]) {
            for (n4 = 51; n4 <= 55 && n > e[n4]; ++n4) {
            }
        } else {
            for (n4 = 56; n4 <= 60 && n > e[n4]; ++n4) {
            }
        }
        for (n3 = (n4 *= c) - c + 1; n3 <= n4; ++n3) {
            if (n3 * n3 < n) continue;
            if (n2 == 0) {
                return n3;
            }
            if (n2 != 1) continue;
            return n3 - 1;
        }
        return -1;
    }

    public static int randomInt(int bound) {
        if (f == null) {
            f = new Random(System.currentTimeMillis());
        }
        return (f.nextInt() >>> 1) % bound;
    }

    public static int a() {
        if (f == null) {
            f = new Random(System.currentTimeMillis());
        }
        return -2 + (f.nextInt() >>> 1) % 4;
    }

    public static int randomRange(int minimum, int maximum) {
        if (f == null) {
            f = new Random(System.currentTimeMillis());
        }
        return (f.nextInt() >>> 1) % (maximum - minimum + 1) + minimum;
    }

    public static int a(int[] nArray, int n) {
        int n2;
        for (n2 = 0; n2 < nArray.length && n < nArray[n2]; ++n2) {
        }
        return n2;
    }

    public static boolean a(int n, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n9) {
        if (n9 % 2 != 0) {
            n9 = n3;
            n3 = n4;
            n4 = n9;
        }
        return n + n3 >= n5 && n5 + n7 >= n && n2 + n4 > n6 && n6 + n8 > n2;
    }

    public static boolean a(int n, int n2, int n3, int n4, int n5) {
        return n >= n3 && n <= n3 + n5 && n2 >= n4 && n2 <= n4 + 40;
    }

    public static boolean a(int n, int n2, int n3, int n4, short[] sArray, short[] sArray2) {
        return n + sArray[0] + sArray[2] >= n3 + sArray2[0] && n + sArray[0] <= n3 + sArray2[0] + sArray2[2] && n2 + sArray[1] <= n4 + sArray2[1] + sArray2[3] && n2 + sArray[1] + sArray[3] >= n4 + sArray2[1];
    }

    public static boolean a(int n, int n2, int n3, int n4, int n5, int n6, short[] sArray) {
        return n + n3 >= n5 + sArray[0] && n <= n5 + sArray[0] + sArray[2] && n2 <= n6 + sArray[1] + sArray[3] && n2 + n4 >= n6 + sArray[1];
    }

    public static boolean a(int n, int n2, int n3, int n4, short[] sArray) {
        return n >= n3 + sArray[0] && n <= n3 + sArray[0] + sArray[2] && n2 <= n4 + sArray[1] + sArray[3] && n2 >= n4 + sArray[1];
    }

    public static Image loadPng(String basePath, String imageName) {
        Image image;
        try {
            image = Image.createImage(basePath + imageName + ".png");
        }
        catch (Exception exception) {
            DebugLogger.a(exception, basePath + imageName + ".png error!!");
            return null;
        }
        return image;
    }

    public static Image loadImage(String basePath, String imageName) {
        byte[] byArray = EngineUtils.g(basePath + imageName + ".mid");
        Object object = byArray;
        return Image.createImage(byArray, 0, ((Object)object).length);
    }

    private static byte[] f(String string) {
        byte[] byArray = null;
        try {
            int n;
            int n2 = 0;
            int n3 = 0;
            InputStream inputStream = "".getClass().getResourceAsStream(string);
            DataInputStream dataInputStream = new DataInputStream(inputStream);
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            byteArrayOutputStream.write(EngineUtils.a(-1991225785L, 4));
            byteArrayOutputStream.write(EngineUtils.a(218765834L, 4));
            byteArrayOutputStream.write(EngineUtils.a(13L, 4));
            byteArrayOutputStream.write(EngineUtils.a(1229472850L, 4));
            byteArrayOutputStream.write(EngineUtils.a((long)dataInputStream.readInt(), 4));
            byteArrayOutputStream.write(EngineUtils.a((long)dataInputStream.readInt(), 4));
            byteArrayOutputStream.write(dataInputStream.readByte());
            byte by = dataInputStream.readByte();
            g = new int[20][2];
            byteArrayOutputStream.write(by);
            byteArrayOutputStream.write(EngineUtils.a(0L, 3));
            byteArrayOutputStream.write(EngineUtils.a(0L, 4));
            EngineUtils.g[0][0] = 8;
            EngineUtils.g[0][1] = 13;
            int n4 = 8 + (g[0][1] + 12);
            ++n3;
            if (by == 3) {
                n2 = dataInputStream.readInt();
                byteArrayOutputStream.write(EngineUtils.a((long)n2, 4));
                byteArrayOutputStream.write(EngineUtils.a(1347179589L, 4));
                byte[] byArray2 = new byte[n2];
                for (n = 0; n < byArray2.length; ++n) {
                    byArray2[n] = (byte)dataInputStream.read();
                }
                byteArrayOutputStream.write(byArray2);
                byteArrayOutputStream.write(EngineUtils.a(0L, 4));
                EngineUtils.g[1][0] = n4;
                EngineUtils.g[1][1] = n2;
                n4 += g[1][1] + 12;
                ++n3;
                n2 = dataInputStream.readInt();
                if (n2 == 1951551059) {
                    int n5 = dataInputStream.read();
                    if (n5 == 0) {
                        n5 = 256;
                    }
                    byteArrayOutputStream.write(EngineUtils.a((long)n5, 4));
                    byteArrayOutputStream.write(EngineUtils.a(1951551059L, 4));
                    n = dataInputStream.read();
                    for (n2 = 0; n2 < n5; ++n2) {
                        if (n2 == n) {
                            byteArrayOutputStream.write(0);
                            continue;
                        }
                        byteArrayOutputStream.write(255);
                    }
                    byteArrayOutputStream.write(EngineUtils.a(0L, 4));
                    EngineUtils.g[2][0] = n4;
                    EngineUtils.g[2][1] = n5;
                    n4 += g[2][1] + 12;
                    ++n3;
                    n2 = dataInputStream.readInt();
                } else {
                    EngineUtils.g[2][0] = n4;
                    EngineUtils.g[2][1] = n2;
                    ++n3;
                }
            } else if (by == 6) {
                n2 = dataInputStream.readInt();
            }
            byteArrayOutputStream.write(EngineUtils.a((long)n2, 4));
            byteArrayOutputStream.write(EngineUtils.a(1229209940L, 4));
            byte[] byArray3 = new byte[n2];
            for (n = 0; n < byArray3.length; ++n) {
                byArray3[n] = (byte)dataInputStream.read();
            }
            byteArrayOutputStream.write(byArray3);
            byteArrayOutputStream.write(EngineUtils.a(0L, 4));
            EngineUtils.g[n3][0] = n4;
            EngineUtils.g[n3][1] = n2;
            ++n3;
            byteArrayOutputStream.write(EngineUtils.a(0L, 4));
            byteArrayOutputStream.write(EngineUtils.a(1229278788L, 4));
            byteArrayOutputStream.write(EngineUtils.a(-1371381630L, 4));
            byArray = byteArrayOutputStream.toByteArray();
            inputStream.close();
            byteArrayOutputStream.close();
            for (n = 0; n < n3; ++n) {
                n4 = g[n][1];
                n2 = g[n][0];
                byArray3 = byArray;
                int n6 = n4 + 4;
                int n7 = n2 + 4;
                int n8 = ~EngineUtils.a(byArray, n7, n6);
                byArray3[n2 + 8 + n4] = n8 >> 24;
                byArray3[n2 + 8 + n4 + 1] = (byte)(n8 >> 16);
                byArray3[n2 + 8 + n4 + 2] = (byte)(n8 >> 8);
                byArray3[n2 + 8 + n4 + 3] = (byte)n8;
            }
        }
        catch (Exception exception) {}
        return byArray;
    }

    private static byte[] a(long l, int n) {
        byte[] byArray = new byte[n];
        --n;
        int n2 = 0;
        while (n >= 0) {
            byArray[n2] = (byte)(l >> (n << 3) & 0xFFL);
            --n;
            ++n2;
        }
        return byArray;
    }

    private static int a(byte[] byArray, int n, int n2) {
        int n3;
        int n4 = -1;
        if (h == null) {
            h = new int[256];
            for (int i = 0; i < 256; ++i) {
                n3 = i;
                for (int j = 0; j < 8; ++j) {
                    if ((n3 & 1) == 1) {
                        n3 = 0xEDB88320 ^ n3 >>> 1;
                        continue;
                    }
                    n3 >>>= 1;
                }
                EngineUtils.h[i] = n3;
            }
        }
        for (n3 = n; n3 < n2 + n; ++n3) {
            n4 = h[(n4 ^ byArray[n3]) & 0xFF] ^ n4 >>> 8;
        }
        return n4;
    }

    public static int[] a(Image image) {
        int n = image.getWidth();
        int n2 = image.getHeight();
        int[] nArray = new int[n * n2];
        image.getRGB(nArray, 0, n, 0, 0, n, n2);
        return nArray;
    }

    public static Image a(int[] nArray, int n, int n2) {
        return Image.createRGBImage(nArray, n, n2, true);
    }

    public static int a(int[] nArray) {
        int n = 0;
        for (int i = 0; i < nArray.length; ++i) {
            if (nArray[i] != -1) continue;
            n = i;
            break;
        }
        return n;
    }

    public static UIComponent a(UIComponent uIComponent, int n) {
        if (uIComponent.getId() == n) {
            return uIComponent;
        }
        for (int i = 0; i < uIComponent.getChildren().length && uIComponent.getChildren()[i] != null; ++i) {
            if (uIComponent.getChildren()[i].getType() == 0) {
                UIComponent uIComponent2 = EngineUtils.a((MenuWidget)uIComponent.getChildren()[i], n);
                if (uIComponent2 == null) continue;
                return uIComponent2;
            }
            if (uIComponent.getChildren()[i].getId() != n) continue;
            return uIComponent.getChildren()[i];
        }
        return null;
    }

    public static int[] b(int n) {
        int[] nArray = new int[n];
        for (int i = 0; i < n; ++i) {
            nArray[i] = -1;
        }
        return nArray;
    }

    public static void b(int[] nArray, int n) {
        int n2;
        if (0 >= nArray.length) {
            return;
        }
        int n3 = 0;
        for (n2 = 0; n2 < nArray.length; ++n2) {
            if (nArray[n2] != -1) continue;
            n3 = n2;
            break;
        }
        for (n2 = n3 - 1; n2 >= 0; --n2) {
            if (n2 + 1 >= nArray.length) continue;
            nArray[n2 + 1] = nArray[n2];
        }
        nArray[0] = n;
    }

    public static void b(byte[] byArray, String object) {
        try {
            int n = 0;
            for (int i = 0; i < ((String)object).length(); ++i) {
                if (((String)object).charAt(i) == '/') continue;
                n = i;
                break;
            }
            String string = "/" + ((String)object).substring(n);
            new Object().getClass();
            object = ResourceStream.openResource(string);
            object = new DataInputStream((InputStream)object);
            ((FilterInputStream)object).skip(0L);
            ((DataInputStream)object).read(byArray, 0, byArray.length);
            ((FilterInputStream)object).close();
            return;
        }
        catch (Exception exception) {
            System.out.println("GameInf err at getStream()  :  " + exception);
            return;
        }
    }

    public static byte readByte(byte[] bytes, int[] cursor) {
        int n = cursor[0];
        cursor[0] = n + 1;
        return bytes[n];
    }

    public static short readShort(byte[] bytes, int[] cursor) {
        int n = cursor[0];
        cursor[0] = n + 1;
        int n2 = cursor[0];
        cursor[0] = n2 + 1;
        return (short)((bytes[n] & 0xFF) << 8 | bytes[n2] & 0xFF);
    }

    public static int readInt(byte[] bytes, int[] cursor) {
        int n = cursor[0];
        cursor[0] = n + 1;
        int n2 = cursor[0];
        cursor[0] = n2 + 1;
        int n3 = cursor[0];
        cursor[0] = n3 + 1;
        int n4 = cursor[0];
        cursor[0] = n4 + 1;
        return (bytes[n] & 0xFF) << 24 | (bytes[n2] & 0xFF) << 16 | (bytes[n3] & 0xFF) << 8 | bytes[n4] & 0xFF;
    }

    public static String decodeUtf16(byte[] bytes) {
        char[] cArray = new char[bytes.length >> 1];
        for (int i = 0; i < bytes.length; i += 2) {
            cArray[i >> 1] = (char)(bytes[i] << 8 | bytes[i + 1] & 0xFF);
        }
        return new String(cArray);
    }

    public static void a(UIComponent uIComponent, int n, int n2, UIComponent uIComponent2) {
        uIComponent.setX(uIComponent.getX() + n, uIComponent2);
        uIComponent.setY(uIComponent.getY() + n2, uIComponent2);
        if (uIComponent.getType() != 1 && uIComponent.getType() == 0) {
            for (int i = 0; i < uIComponent.getChildren().length && uIComponent.getChildren()[i] != null; ++i) {
                EngineUtils.a(uIComponent.getChildren()[i], n, n2, uIComponent2);
            }
        }
    }

    public static void a(Graphics graphics, String string, int n, int n2, int n3, int n4, int n5, int n6, Font font, boolean bl, int n7, int[] nArray, int n8, byte by, TextPainter textPainter, boolean[] blArray) {
        if (by != -1 && textPainter != null) {
            n4 = TextLayoutHelper.a;
        }
        int[] nArray2 = new int[1 + i.length];
        int[] nArray3 = nArray2;
        nArray2[0] = n;
        for (n = 1; n < nArray3.length; ++n) {
            nArray3[n] = i[n - 1];
        }
        j = EngineUtils.a(string, n4, n5, bl, font, by, textPainter);
        n = 0;
        if (EngineUtils.j.d > 0) {
            if (bl) {
                if (EngineUtils.j.a[EngineUtils.j.d - 1][3] + n4 > n6) {
                    blArray[0] = true;
                    if (EngineUtils.j.a[EngineUtils.j.d - 1][3] + n4 > nArray[1]) {
                        nArray[1] = nArray[1] + n8;
                    } else {
                        nArray[1] = -n6;
                        blArray[1] = true;
                    }
                } else {
                    blArray[1] = true;
                    blArray[0] = true;
                    nArray[1] = 0;
                }
            } else {
                n = font.stringWidth(string);
                if (by != -1 && textPainter != null) {
                    String string2 = string;
                    n = TextLayoutHelper.a(string2);
                }
                if (n > n5) {
                    blArray[1] = true;
                    if (n > nArray[0]) {
                        nArray[0] = nArray[0] + n8;
                        if (nArray[0] >= n - n5) {
                            blArray[0] = true;
                        }
                    } else {
                        nArray[0] = -n5;
                    }
                } else {
                    blArray[0] = true;
                    blArray[1] = true;
                    nArray[0] = 0;
                }
            }
        }
        for (int i = 0; i < EngineUtils.j.d; ++i) {
            if (bl) {
                graphics.clipRect(n2, n3, n5, n6);
                EngineUtils.a(graphics, string.substring(EngineUtils.j.a[i][0], EngineUtils.j.a[i][1]), nArray3[EngineUtils.j.a[i][4]], n2 + EngineUtils.j.a[i][2], n3 + EngineUtils.j.a[i][3] - nArray[1], textPainter);
                graphics.clipRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                continue;
            }
            n8 = 0;
            int n9 = 0;
            switch (n7) {
                case 4: {
                    n8 = n > n5 ? n2 : n2 + (n5 - (EngineUtils.j.c + EngineUtils.j.b)) / 2;
                    n9 = n3 + (n6 - n4) / 2;
                    break;
                }
                case 3: {
                    n8 = n2;
                    n9 = n3 + (n6 - n4) / 2;
                    break;
                }
                case 5: {
                    n8 = n2 + (n5 - (EngineUtils.j.c + EngineUtils.j.b));
                    n9 = n3 + (n6 - n4) / 2;
                    break;
                }
                case 6: {
                    n8 = n2;
                    n9 = n3 + (n6 - n4);
                    break;
                }
                case 8: {
                    n8 = n2 + (n5 - (EngineUtils.j.c + EngineUtils.j.b));
                    n9 = n3 + (n6 - n4);
                    break;
                }
                case 7: {
                    n8 = n > n5 ? n2 : n2 + (n5 - (EngineUtils.j.c + EngineUtils.j.b)) / 2;
                    n9 = n3 + (n6 - n4);
                    break;
                }
                case 0: {
                    n8 = n2;
                    n9 = n3;
                    break;
                }
                case 2: {
                    n8 = n2 + (n5 - (EngineUtils.j.c + EngineUtils.j.b));
                    n9 = n3;
                    break;
                }
                case 1: {
                    n8 = n2 + (n5 - (EngineUtils.j.c + EngineUtils.j.b)) / 2;
                    n9 = n3;
                }
            }
            graphics.clipRect(n2, n3, n5, n6);
            EngineUtils.a(graphics, string.substring(EngineUtils.j.a[i][0], EngineUtils.j.a[i][1]), nArray3[EngineUtils.j.a[i][4]], n8 + EngineUtils.j.a[i][2] - nArray[0], n9 + EngineUtils.j.a[i][3], textPainter);
            graphics.clipRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
        }
    }

    private static FormattedTextBuffer a(String string, int n, int n2, boolean bl, Font font, byte by, TextPainter textPainter) {
        FormattedTextBuffer formattedTextBuffer = new FormattedTextBuffer();
        int n3 = 0;
        int n4 = 0;
        int n5 = 0;
        int n6 = 0;
        int n7 = string.length() - 1;
        int n8 = n2 - TextLayoutHelper.b;
        int n9 = 0;
        while (n9 <= n7) {
            block15: {
                block17: {
                    block16: {
                        int n10;
                        char c = string.charAt(n9);
                        if (c == '#' && n9 != n7) {
                            if (string.charAt(n9 + 1) == 'n') {
                                formattedTextBuffer.a[formattedTextBuffer.d++] = new int[]{n3, n9, n4, n5, n6};
                                n4 = 0;
                                n5 += n + 1;
                                n3 = n9 + 2;
                            } else if (string.charAt(n9 + 1) >= '0' && string.charAt(n9 + 1) <= '7') {
                                formattedTextBuffer.c += formattedTextBuffer.b;
                                formattedTextBuffer.a[formattedTextBuffer.d++] = new int[]{n3, n9, n4, n5, n6};
                                n10 = font.charsWidth(string.substring(n3, n9).toCharArray(), 0, n9 - n3);
                                if (by != -1 && textPainter != null) {
                                    n10 = TextPainter.a(string.substring(n3, n9), 0, n9 - n3);
                                }
                                n4 += n10;
                                n6 = string.charAt(n9 + 1) - 48;
                                n3 = n9 + 2;
                            }
                        } else if (n9 - n3 >= 0) {
                            formattedTextBuffer.b = n10 = TextPainter.a(string.substring(n3, n9 + 1), 0, n9 - n3 + 1);
                            if (bl && (n4 + n10 >= n2 || c == ' ' && n4 + n10 >= n8)) {
                                formattedTextBuffer.a[formattedTextBuffer.d++] = new int[]{n3, n9, n4, n5, n6};
                                n4 = 0;
                                n5 += n + 1;
                                n3 = n9;
                            }
                        }
                        if (n9 != n7) break block15;
                        if (n9 != n3) break block16;
                        n10 = 0;
                        while (n10 < k.length) {
                            if (string.charAt(n9) == k[n10]) {
                                formattedTextBuffer.a[formattedTextBuffer.d - 1][1] = n9 + 1;
                                break;
                            }
                            ++n10;
                        }
                        if (n10 < k.length) break block15;
                        break block17;
                    }
                    if (n9 + 1 - n3 <= 0) break block15;
                }
                formattedTextBuffer.a[formattedTextBuffer.d++] = new int[]{n3, n9 + 1, n4, n5, n6};
            }
            ++n9;
        }
        return formattedTextBuffer;
    }

    private static void a(Graphics graphics, String string, int n, int n2, int n3, TextPainter textPainter) {
        TextPainter.a(string, n2, n3, 20, n, graphics);
    }

    public static void a(Graphics graphics, String string, int n, int n2, int n3, TextPainter textPainter, int n4) {
        switch (n4) {
            case 0: {
                if (textPainter != null) {
                    TextPainter.a(string, n2 - 1, n3, 17, 8607289, graphics);
                    TextPainter.a(string, n2 + 1, n3, 17, 8607289, graphics);
                    break;
                }
                graphics.setColor(8607289);
                graphics.drawString(string, n2 - 1, n3, 17);
                graphics.drawString(string, n2 + 1, n3, 17);
                break;
            }
            case 1: {
                if (textPainter != null) {
                    TextPainter.a(string, n2, n3 - 1, 17, 8607289, graphics);
                    TextPainter.a(string, n2, n3 + 1, 17, 8607289, graphics);
                    break;
                }
                graphics.setColor(8607289);
                graphics.drawString(string, n2, n3 - 1, 17);
                graphics.drawString(string, n2, n3 + 1, 17);
                break;
            }
            case 2: {
                if (textPainter != null) {
                    TextPainter.a(string, n2, n3 - 1, 17, 8607289, graphics);
                    TextPainter.a(string, n2, n3 + 1, 17, 8607289, graphics);
                    TextPainter.a(string, n2 - 1, n3, 17, 8607289, graphics);
                    TextPainter.a(string, n2 + 1, n3, 17, 8607289, graphics);
                    break;
                }
                graphics.setColor(8607289);
                graphics.drawString(string, n2, n3 - 1, 17);
                graphics.drawString(string, n2, n3 + 1, 17);
                graphics.drawString(string, n2 - 1, n3, 17);
                graphics.drawString(string, n2 + 1, n3, 17);
            }
        }
        if (textPainter != null) {
            TextPainter.a(string, n2, n3, 17, n, graphics);
            return;
        }
        graphics.setColor(n);
        graphics.drawString(string, n2, n3, 17);
    }

    public static void a(String string, int n, int n2, Font stringArray, TextPainter textPainter) {
        Object object = EngineUtils.a(string, n, n2, true, (Font)stringArray, (byte)-1, textPainter);
        n2 = ((FormattedTextBuffer)object).d;
        object = ((FormattedTextBuffer)object).a;
        b = 1;
        m = 0;
        stringArray = new String[50];
        int n3 = 0;
        Object object2 = object[0][3];
        Object object3 = 0;
        for (int i = 0; i < n2; ++i) {
            if (object2 != object[i][3]) {
                object2 = object[i][3];
                stringArray[n3++] = string.substring((int)object3, (int)object[i][0]);
                object3 = object[i][0];
            }
            if (i != n2 - 1) continue;
            stringArray[n3++] = string.substring((int)object3, (int)object[i][1]);
            break;
        }
        String[] stringArray2 = new String[n3];
        System.arraycopy(stringArray, 0, stringArray2, 0, stringArray2.length);
        a = stringArray2;
    }

    public static void c(int n) {
        l = n / BaseScreen.getFontHeight();
    }

    public static String d(int n) {
        StringBuffer stringBuffer = new StringBuffer();
        for (int i = l * m; i < (n * l > a.length ? a.length : n * l); ++i) {
            stringBuffer.append(a[i]);
        }
        m = n;
        return stringBuffer.toString();
    }

    public static int b() {
        if (a.length % l == 0) {
            return a.length / l;
        }
        return a.length / l + 1;
    }

    public static void c() {
        ++b;
    }

    public static String[] a(String objectArray, char c) {
        Vector<String> vector = new Vector<String>();
        int n = 0;
        int n2 = 0;
        while (n != -1 && (n = objectArray.trim().indexOf(c, n2)) != -1) {
            String string = objectArray.trim().substring(n2, n);
            n2 = n + 1;
            vector.addElement(string);
        }
        vector.addElement(objectArray.substring(n2));
        objectArray = new String[vector.size()];
        vector.copyInto(objectArray);
        return objectArray;
    }

    public static int b(String string) {
        return Integer.parseInt(string);
    }

    public static short c(String string) {
        return Short.parseShort(string);
    }

    public static byte d(String string) {
        return Byte.parseByte(string);
    }

    public static byte[] e(String stringArray) {
        stringArray = EngineUtils.a((String)stringArray, ',');
        byte[] byArray = new byte[stringArray.length];
        for (int i = 0; i < byArray.length; ++i) {
            byArray[i] = Byte.parseByte(stringArray[i]);
        }
        return byArray;
    }

    public static long[] a(long l) {
        long[] lArray = new long[3];
        long[] lArray2 = lArray;
        lArray[0] = l / 3600000L;
        lArray2[1] = l / 60000L;
        lArray2[2] = l / 1000L;
        return lArray2;
    }

    static {
        g = new int[20][2];
        i = new int[]{1862801, 15673612, 12067264, 11689977, 16359727, 0xFF0000, 255};
        j = null;
        k = new char[]{'\uff0c', '\u3002', '\uff1f', '\uff01', '\uff1a', '\uff1b', '\u2019', '\u201d', '\u3001'};
        l = 0;
        b = 1;
        m = 0;
    }

    private static byte[] g(String object) {
        try {
            int n;
            if (((String)object).indexOf("img_") < 0 && !((String)object).endsWith("menu.mid")) {
                return EngineUtils.f((String)object);
            }
            byte[] byArray = new byte[1024];
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            "".getClass();
            object = ResourceStream.openResource((String)object);
            while ((n = ((InputStream)object).read(byArray)) > 0) {
                byteArrayOutputStream.write(byArray, 0, n);
            }
            return byteArrayOutputStream.toByteArray();
        }
        catch (Exception exception) {
            Exception exception2 = exception;
            exception.printStackTrace();
            return null;
        }
    }
}

