/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import javax.microedition.lcdui.Image;

public final class ImageCache {
    private static Image[] images;
    private static byte[] referenceCounts;
    private static int capacity;

    public static void initialize() {
        capacity = 50000;
        images = new Image[50000];
        referenceCounts = new byte[capacity];
    }

    public static Image getImage(int imageId) {
        if (images[imageId] == null) {
            ImageCache.images[imageId] = EngineUtils.loadImage("/data/img/", "img_" + imageId);
        }
        int n = imageId;
        referenceCounts[n] = (byte)(referenceCounts[n] + 1);
        return images[imageId];
    }

    public static void releaseImage(int imageId) {
        int n = imageId;
        referenceCounts[n] = (byte)(referenceCounts[n] - 1);
        if (referenceCounts[imageId] <= 0) {
            ImageCache.referenceCounts[imageId] = 0;
        }
    }

    public static boolean evictImage(int imageId) {
        if (imageId == -1) {
            return true;
        }
        int n = imageId;
        referenceCounts[n] = (byte)(referenceCounts[n] - 1);
        if (referenceCounts[imageId] <= 0) {
            ImageCache.referenceCounts[imageId] = 0;
            ImageCache.images[imageId] = null;
            return true;
        }
        return false;
    }
}

