/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import javax.microedition.lcdui.Image;

public final class ImageTransformer {
    private static byte a = 1;
    private static byte b = (byte)2;

    public static PixelBuffer a(Image image, PixelBuffer pixelBuffer) {
        int n = image.getWidth();
        int n2 = image.getHeight();
        int[] nArray = new int[n * n2];
        image.getRGB(nArray, 0, n, 0, 0, n, n2);
        for (int i = 0; i < nArray.length; ++i) {
            if (nArray[i] != -1 && nArray[i] != -16777216) continue;
            nArray[i] = 0xFFFFFF;
        }
        pixelBuffer.a(nArray, n, n2);
        return pixelBuffer;
    }

    public static PixelBuffer a(SpriteRenderer spriteRenderer, int n, int[] nArray, byte by, PixelBuffer pixelBuffer) {
        Image image = Image.createImage(nArray[2], nArray[3]);
        image.getGraphics().setColor(0);
        image.getGraphics().fillRect(0, 0, nArray[2], nArray[3]);
        spriteRenderer.drawFrame(image.getGraphics(), n, -nArray[0], -nArray[1], by);
        pixelBuffer.d = nArray[0];
        pixelBuffer.e = nArray[1];
        return ImageTransformer.a(image, pixelBuffer);
    }

    public static PixelBuffer a(PixelBuffer pixelBuffer, int n, int n2) {
        int[] nArray = new int[n * n2];
        for (int i = 0; i < n2; ++i) {
            for (int j = 0; j < n; ++j) {
                int n3 = j * pixelBuffer.b / n;
                int n4 = i * pixelBuffer.c / n2;
                nArray[j + i * n] = pixelBuffer.a[n3 + n4 * pixelBuffer.b];
            }
        }
        pixelBuffer.a(nArray, n, n2);
        pixelBuffer.d = pixelBuffer.d * n / pixelBuffer.b / 10;
        pixelBuffer.e = pixelBuffer.e * n / pixelBuffer.b / 10;
        return pixelBuffer;
    }

    public static PixelBuffer a(PixelBuffer pixelBuffer, int n) {
        int n2 = pixelBuffer.b * n / 10;
        int n3 = pixelBuffer.c * n / 10;
        int[] nArray = new int[n2 * n3];
        for (int i = 0; i < n3; ++i) {
            for (int j = 0; j < n2; ++j) {
                int n4 = j * pixelBuffer.b / n2;
                int n5 = i * pixelBuffer.c / n3;
                nArray[j + i * n2] = pixelBuffer.a[n4 + n5 * pixelBuffer.b];
            }
        }
        pixelBuffer.a(nArray, n2, n3);
        pixelBuffer.d = pixelBuffer.d * n / 10;
        pixelBuffer.e = pixelBuffer.e * n / 10;
        return pixelBuffer;
    }

    public static PixelBuffer b(PixelBuffer pixelBuffer, int n, int n2) {
        for (int i = 0; i < pixelBuffer.c; ++i) {
            for (int j = 0; j < pixelBuffer.b; ++j) {
                int n3 = pixelBuffer.a[i * pixelBuffer.b + j];
                int n4 = n3 >> 24;
                int n5 = n3 >> 16 & 0xFF;
                int n6 = n3 >> 8 & 0xFF;
                n3 &= 0xFF;
                n5 = n5 * n + n2;
                n6 = n6 * n + n2;
                n3 = n3 * n + n2;
                if (n5 > 255) {
                    n5 = 255;
                } else if (n5 < 0) {
                    n5 = 0;
                }
                if (n6 > 255) {
                    n6 = 255;
                } else if (n6 < 0) {
                    n6 = 0;
                }
                if (n3 > 255) {
                    n3 = 255;
                } else if (n3 < 0) {
                    n3 = 0;
                }
                pixelBuffer.a[i * pixelBuffer.b + j] = n4 << 24 | n5 << 16 | n6 << 8 | n3;
            }
        }
        return pixelBuffer;
    }

    public static PixelBuffer b(PixelBuffer pixelBuffer, int n) {
        if (n < 0 || n > 255) {
            return pixelBuffer;
        }
        for (int i = 0; i < pixelBuffer.f; ++i) {
            if (pixelBuffer.a[i] == 0xFFFFFF || pixelBuffer.a[i] == 0) continue;
            pixelBuffer.a[i] = pixelBuffer.a[i] == -16777216 ? 0 : n << 24 | pixelBuffer.a[i] & 0xFFFFFF;
        }
        return pixelBuffer;
    }

    public static Image a(Image image) {
        PixelBuffer pixelBuffer = new PixelBuffer();
        int n = image.getWidth();
        int n2 = image.getHeight();
        Image image2 = Image.createImage(n, n2);
        image2.getGraphics().setColor(0);
        image2.getGraphics().fillRect(0, 0, n, n2);
        image2.getGraphics().drawImage(image, 0, 0, 20);
        pixelBuffer.a(EngineUtils.a(image2), n, n2);
        ImageTransformer.b(pixelBuffer, 100);
        image = EngineUtils.a(pixelBuffer.a, pixelBuffer.b, pixelBuffer.c);
        pixelBuffer.a = null;
        return image;
    }

    public static PixelBuffer a(PixelBuffer pixelBuffer, int n, int n2, int n3, int n4) {
        for (int i = 0; i < pixelBuffer.a.length; ++i) {
            if (pixelBuffer.a[i] == 0xFFFFFF) continue;
            pixelBuffer.a[i] = n < 0 || n > 255 ? n2 << 16 | n3 << 8 | n4 : n << 24 | n2 << 16 | n3 << 8 | n4;
        }
        return pixelBuffer;
    }

    public static PixelBuffer a(PixelBuffer pixelBuffer, PixelBuffer pixelBuffer2, byte by) {
        int n = 0;
        int n2 = 0;
        if (by == 0) {
            pixelBuffer = ImageTransformer.b(pixelBuffer, 5, 5);
        }
        for (int i = 0; i < pixelBuffer.c; ++i) {
            for (int j = 0; j < pixelBuffer.b; ++j) {
                int n3 = pixelBuffer.a[i * pixelBuffer.b + j];
                int n4 = pixelBuffer2.a[n2 * pixelBuffer2.b + n];
                if (n3 >> 24 != 0) {
                    if (by == 0) {
                        pixelBuffer.a[i * pixelBuffer.b + j] = n3 & n4;
                    } else if (by == a) {
                        pixelBuffer.a[i * pixelBuffer.b + j] = n3 | n4;
                    } else if (by == b) {
                        pixelBuffer.a[i * pixelBuffer.b + j] = n4;
                    }
                }
                if (n < pixelBuffer2.b - 1) {
                    ++n;
                    continue;
                }
                n = 0;
            }
            n2 = n2 < pixelBuffer2.c - 1 ? ++n2 : 0;
            n = 0;
        }
        return pixelBuffer;
    }
}

