/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import game.WorldManager;
import java.io.DataInputStream;
import java.io.FilterInputStream;
import java.io.InputStream;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

public final class MapEngine {
    private static MapEngine instance;
    private static final int[] f;
    private int viewportWidth = -1;
    private int viewportHeight = -1;
    private short mapColumns = (short)-1;
    private short mapRows = (short)-1;
    private short tileWidth = (short)-1;
    private short tileHeight = (short)-1;
    private int mapId = -1;
    private byte tilesetId = (byte)-1;
    private byte previousTilesetId = (byte)-1;
    private Image[] tileImages = null;
    public int cameraX;
    public int cameraY;
    private int q;
    private int r;
    public int mapPixelWidth;
    public int mapPixelHeight;
    private int s;
    private int t;
    private int u;
    private int v;
    private int w;
    private int x;
    private byte y;
    private short[][] z;
    private short[][][] A;
    private byte[] B = null;
    private static Image C;
    private static Graphics D;
    private boolean E = true;

    public static MapEngine getInstance() {
        if (instance == null) {
            instance = new MapEngine();
        }
        return instance;
    }

    public MapEngine() {
        this.viewportHeight = BaseScreen.getScreenHeight();
        this.viewportWidth = BaseScreen.getScreenWidth();
    }

    public final void release() {
        int n;
        if (this.tileImages != null) {
            for (n = 0; n < this.tileImages.length; ++n) {
                this.tileImages[n] = null;
            }
            this.tileImages = null;
        }
        for (n = 0; n < GameDatabase.tilesetImageTable[this.tilesetId].length; ++n) {
            ImageCache.evictImage(GameDatabase.tilesetImageTable[this.tilesetId][n]);
        }
        C = null;
        D = null;
        MapEngine mapEngine = this;
        this.A = null;
        mapEngine.B = null;
        mapEngine.z = null;
    }

    public final void loadMap(int mapId) {
        this.mapId = mapId;
        MapEngine mapEngine = this;
        try {
            mapEngine.getClass();
            InputStream inputStream = ResourceStream.openResource("/data/map/map_" + mapEngine.mapId + ".mid");
            inputStream = new DataInputStream(inputStream);
            byte by = ((DataInputStream)inputStream).readByte();
            mapEngine.previousTilesetId = mapEngine.tilesetId;
            mapEngine.tilesetId = ((DataInputStream)inputStream).readByte();
            mapEngine.d();
            mapEngine.mapColumns = by == 1 ? (short)((DataInputStream)inputStream).readByte() : ((DataInputStream)inputStream).readShort();
            mapEngine.mapRows = by == 1 ? (short)((DataInputStream)inputStream).readByte() : ((DataInputStream)inputStream).readShort();
            mapEngine.tileHeight = mapEngine.tileWidth = (short)((DataInputStream)inputStream).readByte();
            mapEngine.mapPixelWidth = mapEngine.mapColumns * mapEngine.tileWidth;
            mapEngine.mapPixelHeight = mapEngine.mapRows * mapEngine.tileHeight;
            mapEngine.y = ((DataInputStream)inputStream).readByte();
            mapEngine.B = new byte[mapEngine.y];
            mapEngine.A = new short[mapEngine.y][][];
            for (int i = 0; i < mapEngine.y; ++i) {
                int n;
                int n2;
                byte by2 = ((DataInputStream)inputStream).readByte();
                mapEngine.B[i] = ((DataInputStream)inputStream).readByte();
                short s = ((DataInputStream)inputStream).readShort();
                if (mapEngine.B[by2] == 0 || mapEngine.B[by2] == 1) {
                    mapEngine.A[by2] = new short[mapEngine.mapColumns][mapEngine.mapRows];
                    for (n2 = 0; n2 < mapEngine.mapColumns; ++n2) {
                        for (n = 0; n < mapEngine.mapRows; ++n) {
                            mapEngine.A[by2][n2][n] = -1;
                        }
                    }
                } else {
                    mapEngine.A[by2] = new short[s][4];
                }
                for (n2 = 0; n2 < s; ++n2) {
                    short s2;
                    if (by == 1) {
                        n = ((DataInputStream)inputStream).readByte();
                        s2 = ((DataInputStream)inputStream).readByte();
                    } else {
                        n = ((DataInputStream)inputStream).readShort();
                        s2 = ((DataInputStream)inputStream).readShort();
                    }
                    short s3 = ((DataInputStream)inputStream).readShort();
                    if (mapEngine.B[i] == 1) {
                        mapEngine.A[i][n][s2] = s3;
                        continue;
                    }
                    if (mapEngine.B[by2] == 0) {
                        mapEngine.A[i][n][s2] = (short)(s3 & 0xFFF);
                        continue;
                    }
                    mapEngine.A[i][n2][1] = n;
                    mapEngine.A[i][n2][2] = s2;
                    mapEngine.A[i][n2][0] = (short)(s3 & 0xFFF);
                    mapEngine.A[i][n2][3] = (short)((s3 & 0x7000) >> 12);
                }
            }
            ((FilterInputStream)inputStream).close();
        }
        catch (Exception exception) {
            Object var2_4 = null;
            exception.printStackTrace();
        }
        if (C == null) {
            C = Image.createImage(this.viewportWidth, this.viewportHeight);
            D = C.getGraphics();
        }
        this.E = true;
    }

    private void d() {
        int n;
        if (this.tileImages != null) {
            for (n = 0; n < this.tileImages.length; ++n) {
                for (int i = 0; i < GameDatabase.tilesetImageTable[this.tilesetId].length; ++i) {
                    if (GameDatabase.tilesetImageTable[this.previousTilesetId][n] != GameDatabase.tilesetImageTable[this.tilesetId][i]) continue;
                    ImageCache.releaseImage(GameDatabase.tilesetImageTable[this.previousTilesetId][n]);
                    this.tileImages[n] = null;
                    break;
                }
                if (this.tileImages[n] == null) continue;
                ImageCache.evictImage(GameDatabase.tilesetImageTable[this.previousTilesetId][n]);
                this.tileImages[n] = null;
            }
            this.tileImages = null;
        }
        this.tileImages = new Image[GameDatabase.tilesetImageTable[this.tilesetId].length];
        for (n = 0; n < this.tileImages.length; ++n) {
            this.tileImages[n] = ImageCache.getImage(GameDatabase.tilesetImageTable[this.tilesetId][n]);
        }
        try {
            "".getClass();
            InputStream inputStream = ResourceStream.openResource("/data/mod/mod_" + this.tilesetId + ".mid");
            DataInputStream dataInputStream = new DataInputStream(inputStream);
            int n2 = dataInputStream.readShort();
            this.z = new short[n2][5];
            for (int i = 0; i < n2; ++i) {
                this.z[i][0] = dataInputStream.readByte();
                this.z[i][1] = dataInputStream.readShort();
                this.z[i][2] = dataInputStream.readShort();
                this.z[i][3] = dataInputStream.readShort();
                this.z[i][4] = dataInputStream.readShort();
            }
            dataInputStream.close();
            inputStream.close();
            return;
        }
        catch (Exception exception) {
            exception.printStackTrace();
            return;
        }
    }

    public final void c() {
        if (this.tileWidth == 0) {
            return;
        }
        this.t = this.cameraY / this.tileHeight;
        this.s = this.cameraX / this.tileWidth;
        this.v = (this.cameraY + this.viewportHeight) / this.tileHeight;
        if ((this.cameraY + this.viewportHeight) % this.tileHeight != 0) {
            ++this.v;
        }
        if (this.v > this.mapRows) {
            this.v = this.mapRows;
        }
        this.u = (this.cameraX + this.viewportWidth) / this.tileWidth;
        if ((this.cameraX + this.viewportWidth) % this.tileWidth != 0) {
            ++this.u;
        }
        if (this.u > this.mapColumns) {
            this.u = this.mapColumns;
        }
        this.x = this.viewportHeight / this.tileHeight + 1;
        this.w = this.viewportWidth / this.tileWidth + 1;
        if (this.t + this.x >= this.mapRows) {
            this.x = this.mapRows - 1 - this.t;
        }
        if (this.w + this.s >= this.mapColumns) {
            this.w = this.mapColumns - 1 - this.s;
        }
    }

    private void a(Graphics graphics, int n, int n2, int n3, int n4, int n5) {
        WorldManager.a();
        WorldManager.a(graphics, n2, n3, n4, n5);
        switch (this.B[n]) {
            case 0: {
                this.b(graphics, n, n2, n3, n4, n5);
                return;
            }
            case 1: {
                this.c(graphics, n, n2, n3, n4, n5);
            }
        }
    }

    public final void a(Graphics object, int n, int n2) {
        switch (this.B[n]) {
            case 0:
            case 1: {
                n2 = n;
                Graphics graphics = object;
                object = this;
                if (((MapEngine)object).E) {
                    int n3 = ((MapEngine)object).cameraX / ((MapEngine)object).tileWidth < 0 ? 0 : ((MapEngine)object).cameraX / ((MapEngine)object).tileWidth;
                    int n4 = ((MapEngine)object).cameraY / ((MapEngine)object).tileHeight < 0 ? 0 : ((MapEngine)object).cameraY / ((MapEngine)object).tileHeight;
                    int n5 = (((MapEngine)object).cameraX + ((MapEngine)object).viewportWidth) / ((MapEngine)object).tileWidth + 1 > ((MapEngine)object).mapColumns ? ((MapEngine)object).mapColumns : (((MapEngine)object).cameraX + ((MapEngine)object).viewportWidth) / ((MapEngine)object).tileWidth + 1;
                    int n6 = (((MapEngine)object).cameraY + ((MapEngine)object).viewportHeight) / ((MapEngine)object).tileHeight + 1 > ((MapEngine)object).mapRows ? ((MapEngine)object).mapRows : (((MapEngine)object).cameraY + ((MapEngine)object).viewportHeight) / ((MapEngine)object).tileHeight + 1;
                    WorldManager.a();
                    WorldManager.a(D, 0, 0, ((MapEngine)object).viewportWidth, ((MapEngine)object).viewportHeight);
                    switch (((MapEngine)object).B[n2]) {
                        case 0: {
                            super.b(D, n2, n3, n4, n5, n6);
                            break;
                        }
                        case 1: {
                            super.c(D, n2, n3, n4, n5, n6);
                        }
                    }
                    ((MapEngine)object).E = false;
                } else if (((MapEngine)object).q != ((MapEngine)object).cameraX || ((MapEngine)object).r != ((MapEngine)object).cameraY) {
                    int n7 = 0;
                    int n8 = 0;
                    if (((MapEngine)object).cameraX > ((MapEngine)object).q) {
                        n7 = ((MapEngine)object).q - ((MapEngine)object).cameraX;
                    } else if (((MapEngine)object).cameraX < ((MapEngine)object).q) {
                        n7 = ((MapEngine)object).q - ((MapEngine)object).cameraX;
                    }
                    if (((MapEngine)object).cameraY > ((MapEngine)object).r) {
                        n8 = ((MapEngine)object).r - ((MapEngine)object).cameraY;
                    } else if (((MapEngine)object).cameraY < ((MapEngine)object).r) {
                        n8 = ((MapEngine)object).r - ((MapEngine)object).cameraY;
                    }
                    D.copyArea(0, 0, ((MapEngine)object).viewportWidth, ((MapEngine)object).viewportHeight, n7, n8, 20);
                    if (((MapEngine)object).cameraX > ((MapEngine)object).q) {
                        int n9 = (((MapEngine)object).q + ((MapEngine)object).viewportWidth) / ((MapEngine)object).tileWidth;
                        super.a(D, n2, n9, ((MapEngine)object).t, ((MapEngine)object).u, ((MapEngine)object).v);
                    } else if (((MapEngine)object).cameraX < ((MapEngine)object).q) {
                        n7 = ((MapEngine)object).q / ((MapEngine)object).tileWidth + 1;
                        super.a(D, n2, ((MapEngine)object).s, ((MapEngine)object).t, n7, ((MapEngine)object).v);
                    }
                    if (((MapEngine)object).cameraY > ((MapEngine)object).r) {
                        int n10 = (((MapEngine)object).r + ((MapEngine)object).viewportHeight) / ((MapEngine)object).tileHeight;
                        super.a(D, n2, ((MapEngine)object).s, n10, ((MapEngine)object).u, ((MapEngine)object).v);
                    } else if (((MapEngine)object).cameraY < ((MapEngine)object).r) {
                        n7 = ((MapEngine)object).r / ((MapEngine)object).tileHeight + 1;
                        super.a(D, n2, ((MapEngine)object).s, ((MapEngine)object).t, ((MapEngine)object).u, n7);
                    }
                }
                graphics.drawImage(C, 0, 0, 20);
                ((MapEngine)object).q = ((MapEngine)object).cameraX;
                ((MapEngine)object).r = ((MapEngine)object).cameraY;
                return;
            }
            case 2:
            case 3:
            case 4: {
                n2 = n;
                Graphics graphics = object;
                object = this;
                for (int i = 0; i < ((MapEngine)object).A[n2].length; ++i) {
                    if (((MapEngine)object).A[n2][i][2] < 0 || !EngineUtils.a(((MapEngine)object).A[n2][i][1], ((MapEngine)object).A[n2][i][2], ((MapEngine)object).z[((MapEngine)object).A[n2][i][0]][3], ((MapEngine)object).z[((MapEngine)object).A[n2][i][0]][4], ((MapEngine)object).s, ((MapEngine)object).t, ((MapEngine)object).w + 1, ((MapEngine)object).x + 1, ((MapEngine)object).A[n2][i][3])) continue;
                    graphics.drawRegion(((MapEngine)object).tileImages[((MapEngine)object).z[((MapEngine)object).A[n2][i][0]][0]], ((MapEngine)object).z[((MapEngine)object).A[n2][i][0]][1], ((MapEngine)object).z[((MapEngine)object).A[n2][i][0]][2], ((MapEngine)object).z[((MapEngine)object).A[n2][i][0]][3], ((MapEngine)object).z[((MapEngine)object).A[n2][i][0]][4], f[((MapEngine)object).A[n2][i][3]], (((MapEngine)object).A[n2][i][1] - ((MapEngine)object).s) * ((MapEngine)object).tileWidth - ((MapEngine)object).cameraX % ((MapEngine)object).tileWidth, (((MapEngine)object).A[n2][i][2] - ((MapEngine)object).t) * ((MapEngine)object).tileHeight - ((MapEngine)object).cameraY % ((MapEngine)object).tileHeight, 20);
                }
                break;
            }
        }
    }

    private void b(Graphics graphics, int n, int n2, int n3, int n4, int n5) {
        while (n2 < n4) {
            for (int i = n3; i < n5; ++i) {
                short s = this.A[n][n2][i];
                if (s == -1) continue;
                graphics.drawRegion(this.tileImages[0], this.z[s][1], this.z[s][2], this.z[s][3], this.z[s][4], 0, n2 * this.tileWidth - this.cameraX, i * this.tileHeight - this.cameraY, 20);
            }
            ++n2;
        }
    }

    private void c(Graphics graphics, int n, int n2, int n3, int n4, int n5) {
        while (n2 < n4) {
            for (int i = n3; i < n5; ++i) {
                short s = this.A[n][n2][i];
                if (s == -1) continue;
                short s2 = (short)(s & 0xFFF);
                s = (short)f[(s & 0x7000) >> 12];
                graphics.drawRegion(this.tileImages[this.z[s2][0]], this.z[s2][1], this.z[s2][2], this.z[s2][3], this.z[s2][4], s, n2 * this.tileWidth - this.cameraX, i * this.tileHeight - this.cameraY, 20);
            }
            ++n2;
        }
    }

    public final void a(int n, int n2) {
        this.cameraX = n - this.viewportWidth / 2;
        this.cameraY = n2 - this.viewportHeight / 2;
        if (this.cameraX + this.viewportWidth >= this.mapColumns * this.tileWidth) {
            this.cameraX = this.mapColumns * this.tileWidth - this.viewportWidth;
        }
        if (this.cameraX <= 0) {
            this.cameraX = 0;
        }
        if (this.cameraY + this.viewportHeight >= this.mapRows * this.tileHeight) {
            this.cameraY = this.mapRows * this.tileHeight - this.viewportHeight;
        }
        if (this.cameraY <= 0) {
            this.cameraY = 0;
        }
    }

    public final byte b(int n, int n2) {
        if (this.A == null || this.A[0] == null) {
            return -1;
        }
        int n3 = n / this.tileWidth;
        int n4 = n2 / this.tileHeight;
        if (this.c(n, n2)) {
            return 1;
        }
        if (n4 < 0) {
            n4 = 0;
        }
        if (n3 < 0) {
            n3 = 0;
        }
        if (n3 > this.mapColumns) {
            n3 = this.mapColumns;
        }
        if (n4 > this.mapRows) {
            n4 = this.mapRows;
        }
        return (byte)this.A[0][n3][n4];
    }

    public final boolean c(int n, int n2) {
        return n <= 0 || n >= this.mapPixelWidth || n2 <= 0 || n2 >= this.mapPixelHeight;
    }

    static {
        int[] nArray = new int[]{0, 270, 180, 90, 8192, 8462, 8372, 8282};
        f = new int[]{0, 5, 3, 6, 2, 4, 1, 7};
    }
}

