/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import game.WorldManager;
import java.io.DataInputStream;
import java.io.FilterInputStream;
import java.io.InputStream;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

public final class MapEngine {
    private static MapEngine instance;
    private static final int[] transformLookupTable;
    private int viewportWidth = -1;
    private int viewportHeight = -1;
    private short mapColumns = (short)-1;
    private short mapRows = (short)-1;
    private short tileWidth = (short)-1;
    private short tileHeight = (short)-1;
    private int mapId = -1;
    private byte tilesetId = (byte)-1;
    private byte previousTilesetId = (byte)-1;
    private Image[] tileImages = null;
    public int cameraX;
    public int cameraY;
    private int lastCameraX;
    private int lastCameraY;
    public int mapPixelWidth;
    public int mapPixelHeight;
    private int startTileCol;
    private int startTileRow;
    private int endTileCol;
    private int endTileRow;
    private int visibleTileCols;
    private int visibleTileRows;
    private byte layerCount;
    private short[][] tileDefinitions;
    private short[][][] layerData;
    private byte[] layerTypes = null;
    private static Image bufferImage;
    private static Graphics bufferGraphics;
    private boolean needsFullRedraw = true;

    public static MapEngine getInstance() {
        if (instance == null) {
            instance = new MapEngine();
        }
        return instance;
    }

    public MapEngine() {
        this.viewportHeight = BaseScreen.getScreenHeight();
        this.viewportWidth = BaseScreen.getScreenWidth();
    }

    public final void release() {
        int n;
        if (this.tileImages != null) {
            for (n = 0; n < this.tileImages.length; ++n) {
                this.tileImages[n] = null;
            }
            this.tileImages = null;
        }
        for (n = 0; n < GameDatabase.tilesetImageTable[this.tilesetId].length; ++n) {
            ImageCache.evictImage(GameDatabase.tilesetImageTable[this.tilesetId][n]);
        }
        bufferImage = null;
        bufferGraphics = null;
        MapEngine mapEngine = this;
        this.layerData = null;
        mapEngine.layerTypes = null;
        mapEngine.tileDefinitions = null;
    }

    public final void loadMap(int mapId) {
        this.mapId = mapId;
        MapEngine mapEngine = this;
        try {
            mapEngine.getClass();
            InputStream inputStream = ResourceStream.openResource("/data/map/map_" + mapEngine.mapId + ".mid");
            inputStream = new DataInputStream(inputStream);
            byte by = ((DataInputStream)inputStream).readByte();
            mapEngine.previousTilesetId = mapEngine.tilesetId;
            mapEngine.tilesetId = ((DataInputStream)inputStream).readByte();
            mapEngine.loadTileset();
            mapEngine.mapColumns = by == 1 ? (short)((DataInputStream)inputStream).readByte() : ((DataInputStream)inputStream).readShort();
            mapEngine.mapRows = by == 1 ? (short)((DataInputStream)inputStream).readByte() : ((DataInputStream)inputStream).readShort();
            mapEngine.tileHeight = mapEngine.tileWidth = (short)((DataInputStream)inputStream).readByte();
            mapEngine.mapPixelWidth = mapEngine.mapColumns * mapEngine.tileWidth;
            mapEngine.mapPixelHeight = mapEngine.mapRows * mapEngine.tileHeight;
            mapEngine.layerCount = ((DataInputStream)inputStream).readByte();
            mapEngine.layerTypes = new byte[mapEngine.layerCount];
            mapEngine.layerData = new short[mapEngine.layerCount][][];
            for (int i = 0; i < mapEngine.layerCount; ++i) {
                int n;
                int n2;
                byte by2 = ((DataInputStream)inputStream).readByte();
                mapEngine.layerTypes[i] = ((DataInputStream)inputStream).readByte();
                short s = ((DataInputStream)inputStream).readShort();
                if (mapEngine.layerTypes[by2] == 0 || mapEngine.layerTypes[by2] == 1) {
                    mapEngine.layerData[by2] = new short[mapEngine.mapColumns][mapEngine.mapRows];
                    for (n2 = 0; n2 < mapEngine.mapColumns; ++n2) {
                        for (n = 0; n < mapEngine.mapRows; ++n) {
                            mapEngine.layerData[by2][n2][n] = -1;
                        }
                    }
                } else {
                    mapEngine.layerData[by2] = new short[s][4];
                }
                for (n2 = 0; n2 < s; ++n2) {
                    short s2;
                    if (by == 1) {
                        n = ((DataInputStream)inputStream).readByte();
                        s2 = ((DataInputStream)inputStream).readByte();
                    } else {
                        n = ((DataInputStream)inputStream).readShort();
                        s2 = ((DataInputStream)inputStream).readShort();
                    }
                    short s3 = ((DataInputStream)inputStream).readShort();
                    if (mapEngine.layerTypes[i] == 1) {
                        mapEngine.layerData[i][n][s2] = s3;
                        continue;
                    }
                    if (mapEngine.layerTypes[by2] == 0) {
                        mapEngine.layerData[i][n][s2] = (short)(s3 & 0xFFF);
                        continue;
                    }
                    mapEngine.layerData[i][n2][1] = n;
                    mapEngine.layerData[i][n2][2] = s2;
                    mapEngine.layerData[i][n2][0] = (short)(s3 & 0xFFF);
                    mapEngine.layerData[i][n2][3] = (short)((s3 & 0x7000) >> 12);
                }
            }
            ((FilterInputStream)inputStream).close();
        }
        catch (Exception exception) {
            Object var2_4 = null;
            exception.printStackTrace();
        }
        if (bufferImage == null) {
            bufferImage = Image.createImage(this.viewportWidth, this.viewportHeight);
            bufferGraphics = bufferImage.getGraphics();
        }
        this.needsFullRedraw = true;
    }

    private void loadTileset() {
        int n;
        if (this.tileImages != null) {
            for (n = 0; n < this.tileImages.length; ++n) {
                for (int i = 0; i < GameDatabase.tilesetImageTable[this.tilesetId].length; ++i) {
                    if (GameDatabase.tilesetImageTable[this.previousTilesetId][n] != GameDatabase.tilesetImageTable[this.tilesetId][i]) continue;
                    ImageCache.releaseImage(GameDatabase.tilesetImageTable[this.previousTilesetId][n]);
                    this.tileImages[n] = null;
                    break;
                }
                if (this.tileImages[n] == null) continue;
                ImageCache.evictImage(GameDatabase.tilesetImageTable[this.previousTilesetId][n]);
                this.tileImages[n] = null;
            }
            this.tileImages = null;
        }
        this.tileImages = new Image[GameDatabase.tilesetImageTable[this.tilesetId].length];
        for (n = 0; n < this.tileImages.length; ++n) {
            this.tileImages[n] = ImageCache.getImage(GameDatabase.tilesetImageTable[this.tilesetId][n]);
        }
        try {
            "".getClass();
            InputStream inputStream = ResourceStream.openResource("/data/mod/mod_" + this.tilesetId + ".mid");
            DataInputStream dataInputStream = new DataInputStream(inputStream);
            int n2 = dataInputStream.readShort();
            this.tileDefinitions = new short[n2][5];
            for (int i = 0; i < n2; ++i) {
                this.tileDefinitions[i][0] = dataInputStream.readByte();
                this.tileDefinitions[i][1] = dataInputStream.readShort();
                this.tileDefinitions[i][2] = dataInputStream.readShort();
                this.tileDefinitions[i][3] = dataInputStream.readShort();
                this.tileDefinitions[i][4] = dataInputStream.readShort();
            }
            dataInputStream.close();
            inputStream.close();
            return;
        }
        catch (Exception exception) {
            exception.printStackTrace();
            return;
        }
    }

    public final void updateVisibleBounds() {
        if (this.tileWidth == 0) {
            return;
        }
        this.startTileRow = this.cameraY / this.tileHeight;
        this.startTileCol = this.cameraX / this.tileWidth;
        this.endTileRow = (this.cameraY + this.viewportHeight) / this.tileHeight;
        if ((this.cameraY + this.viewportHeight) % this.tileHeight != 0) {
            ++this.endTileRow;
        }
        if (this.endTileRow > this.mapRows) {
            this.endTileRow = this.mapRows;
        }
        this.endTileCol = (this.cameraX + this.viewportWidth) / this.tileWidth;
        if ((this.cameraX + this.viewportWidth) % this.tileWidth != 0) {
            ++this.endTileCol;
        }
        if (this.endTileCol > this.mapColumns) {
            this.endTileCol = this.mapColumns;
        }
        this.visibleTileRows = this.viewportHeight / this.tileHeight + 1;
        this.visibleTileCols = this.viewportWidth / this.tileWidth + 1;
        if (this.startTileRow + this.visibleTileRows >= this.mapRows) {
            this.visibleTileRows = this.mapRows - 1 - this.startTileRow;
        }
        if (this.visibleTileCols + this.startTileCol >= this.mapColumns) {
            this.visibleTileCols = this.mapColumns - 1 - this.startTileCol;
        }
    }

    private void renderTileRegion(Graphics graphics, int layerIndex, int startCol, int startRow, int endCol, int endRow) {
        WorldManager.a();
        WorldManager.a(graphics, startCol, startRow, endCol, endRow);
        switch (this.layerTypes[layerIndex]) {
            case 0: {
                this.renderBasicGridRegion(graphics, layerIndex, startCol, startRow, endCol, endRow);
                return;
            }
            case 1: {
                this.renderTransformedGridRegion(graphics, layerIndex, startCol, startRow, endCol, endRow);
            }
        }
    }

    /*
     * WARNING - void declaration
     */
    public final void renderLayer(Graphics graphics, int layerIndex, int layerParam) {
        switch (this.layerTypes[layerIndex]) {
            case 0:
            case 1: {
                layerParam = layerIndex;
                Graphics graphics2 = graphics;
                MapEngine mapEngine = this;
                if (mapEngine.needsFullRedraw) {
                    int n = mapEngine.cameraX / mapEngine.tileWidth < 0 ? 0 : mapEngine.cameraX / mapEngine.tileWidth;
                    int n2 = mapEngine.cameraY / mapEngine.tileHeight < 0 ? 0 : mapEngine.cameraY / mapEngine.tileHeight;
                    int n3 = (mapEngine.cameraX + mapEngine.viewportWidth) / mapEngine.tileWidth + 1 > mapEngine.mapColumns ? mapEngine.mapColumns : (mapEngine.cameraX + mapEngine.viewportWidth) / mapEngine.tileWidth + 1;
                    int n4 = (mapEngine.cameraY + mapEngine.viewportHeight) / mapEngine.tileHeight + 1 > mapEngine.mapRows ? mapEngine.mapRows : (mapEngine.cameraY + mapEngine.viewportHeight) / mapEngine.tileHeight + 1;
                    WorldManager.a();
                    WorldManager.a(bufferGraphics, 0, 0, mapEngine.viewportWidth, mapEngine.viewportHeight);
                    switch (mapEngine.layerTypes[layerParam]) {
                        case 0: {
                            mapEngine.renderBasicGridRegion(bufferGraphics, layerParam, n, n2, n3, n4);
                            break;
                        }
                        case 1: {
                            mapEngine.renderTransformedGridRegion(bufferGraphics, layerParam, n, n2, n3, n4);
                        }
                    }
                    mapEngine.needsFullRedraw = false;
                } else if (mapEngine.lastCameraX != mapEngine.cameraX || mapEngine.lastCameraY != mapEngine.cameraY) {
                    int n = 0;
                    int n5 = 0;
                    if (mapEngine.cameraX > mapEngine.lastCameraX) {
                        n = mapEngine.lastCameraX - mapEngine.cameraX;
                    } else if (mapEngine.cameraX < mapEngine.lastCameraX) {
                        n = mapEngine.lastCameraX - mapEngine.cameraX;
                    }
                    if (mapEngine.cameraY > mapEngine.lastCameraY) {
                        n5 = mapEngine.lastCameraY - mapEngine.cameraY;
                    } else if (mapEngine.cameraY < mapEngine.lastCameraY) {
                        n5 = mapEngine.lastCameraY - mapEngine.cameraY;
                    }
                    bufferGraphics.copyArea(0, 0, mapEngine.viewportWidth, mapEngine.viewportHeight, n, n5, 20);
                    if (mapEngine.cameraX > mapEngine.lastCameraX) {
                        int n6 = (mapEngine.lastCameraX + mapEngine.viewportWidth) / mapEngine.tileWidth;
                        mapEngine.renderTileRegion(bufferGraphics, layerParam, n6, mapEngine.startTileRow, mapEngine.endTileCol, mapEngine.endTileRow);
                    } else if (mapEngine.cameraX < mapEngine.lastCameraX) {
                        n = mapEngine.lastCameraX / mapEngine.tileWidth + 1;
                        mapEngine.renderTileRegion(bufferGraphics, layerParam, mapEngine.startTileCol, mapEngine.startTileRow, n, mapEngine.endTileRow);
                    }
                    if (mapEngine.cameraY > mapEngine.lastCameraY) {
                        int n7 = (mapEngine.lastCameraY + mapEngine.viewportHeight) / mapEngine.tileHeight;
                        mapEngine.renderTileRegion(bufferGraphics, layerParam, mapEngine.startTileCol, n7, mapEngine.endTileCol, mapEngine.endTileRow);
                    } else if (mapEngine.cameraY < mapEngine.lastCameraY) {
                        n = mapEngine.lastCameraY / mapEngine.tileHeight + 1;
                        mapEngine.renderTileRegion(bufferGraphics, layerParam, mapEngine.startTileCol, mapEngine.startTileRow, mapEngine.endTileCol, n);
                    }
                }
                graphics2.drawImage(bufferImage, 0, 0, 20);
                mapEngine.lastCameraX = mapEngine.cameraX;
                mapEngine.lastCameraY = mapEngine.cameraY;
                return;
            }
            case 2:
            case 3:
            case 4: {
                void var2_2;
                MapEngine mapEngine;
                layerParam = var2_2;
                void var2_4 = mapEngine;
                mapEngine = this;
                for (int i = 0; i < mapEngine.layerData[layerParam].length; ++i) {
                    if (mapEngine.layerData[layerParam][i][2] < 0 || !EngineUtils.a(mapEngine.layerData[layerParam][i][1], mapEngine.layerData[layerParam][i][2], mapEngine.tileDefinitions[mapEngine.layerData[layerParam][i][0]][3], mapEngine.tileDefinitions[mapEngine.layerData[layerParam][i][0]][4], mapEngine.startTileCol, mapEngine.startTileRow, mapEngine.visibleTileCols + 1, mapEngine.visibleTileRows + 1, mapEngine.layerData[layerParam][i][3])) continue;
                    var2_4.drawRegion(mapEngine.tileImages[mapEngine.tileDefinitions[mapEngine.layerData[layerParam][i][0]][0]], mapEngine.tileDefinitions[mapEngine.layerData[layerParam][i][0]][1], mapEngine.tileDefinitions[mapEngine.layerData[layerParam][i][0]][2], mapEngine.tileDefinitions[mapEngine.layerData[layerParam][i][0]][3], mapEngine.tileDefinitions[mapEngine.layerData[layerParam][i][0]][4], transformLookupTable[mapEngine.layerData[layerParam][i][3]], (mapEngine.layerData[layerParam][i][1] - mapEngine.startTileCol) * mapEngine.tileWidth - mapEngine.cameraX % mapEngine.tileWidth, (mapEngine.layerData[layerParam][i][2] - mapEngine.startTileRow) * mapEngine.tileHeight - mapEngine.cameraY % mapEngine.tileHeight, 20);
                }
                break;
            }
        }
    }

    private void renderBasicGridRegion(Graphics graphics, int layerIndex, int startCol, int startRow, int endCol, int endRow) {
        while (startCol < endCol) {
            for (int i = startRow; i < endRow; ++i) {
                short s = this.layerData[layerIndex][startCol][i];
                if (s == -1) continue;
                graphics.drawRegion(this.tileImages[0], this.tileDefinitions[s][1], this.tileDefinitions[s][2], this.tileDefinitions[s][3], this.tileDefinitions[s][4], 0, startCol * this.tileWidth - this.cameraX, i * this.tileHeight - this.cameraY, 20);
            }
            ++startCol;
        }
    }

    private void renderTransformedGridRegion(Graphics graphics, int layerIndex, int startCol, int startRow, int endCol, int endRow) {
        while (startCol < endCol) {
            for (int i = startRow; i < endRow; ++i) {
                short s = this.layerData[layerIndex][startCol][i];
                if (s == -1) continue;
                short s2 = (short)(s & 0xFFF);
                s = (short)transformLookupTable[(s & 0x7000) >> 12];
                graphics.drawRegion(this.tileImages[this.tileDefinitions[s2][0]], this.tileDefinitions[s2][1], this.tileDefinitions[s2][2], this.tileDefinitions[s2][3], this.tileDefinitions[s2][4], s, startCol * this.tileWidth - this.cameraX, i * this.tileHeight - this.cameraY, 20);
            }
            ++startCol;
        }
    }

    public final void centerCamera(int targetX, int targetY) {
        this.cameraX = targetX - this.viewportWidth / 2;
        this.cameraY = targetY - this.viewportHeight / 2;
        if (this.cameraX + this.viewportWidth >= this.mapColumns * this.tileWidth) {
            this.cameraX = this.mapColumns * this.tileWidth - this.viewportWidth;
        }
        if (this.cameraX <= 0) {
            this.cameraX = 0;
        }
        if (this.cameraY + this.viewportHeight >= this.mapRows * this.tileHeight) {
            this.cameraY = this.mapRows * this.tileHeight - this.viewportHeight;
        }
        if (this.cameraY <= 0) {
            this.cameraY = 0;
        }
    }

    public final byte getCollisionTile(int pixelX, int pixelY) {
        if (this.layerData == null || this.layerData[0] == null) {
            return -1;
        }
        int n = pixelX / this.tileWidth;
        int n2 = pixelY / this.tileHeight;
        if (this.isOutOfBounds(pixelX, pixelY)) {
            return 1;
        }
        if (n2 < 0) {
            n2 = 0;
        }
        if (n < 0) {
            n = 0;
        }
        if (n > this.mapColumns) {
            n = this.mapColumns;
        }
        if (n2 > this.mapRows) {
            n2 = this.mapRows;
        }
        return (byte)this.layerData[0][n][n2];
    }

    public final boolean isOutOfBounds(int pixelX, int pixelY) {
        return pixelX <= 0 || pixelX >= this.mapPixelWidth || pixelY <= 0 || pixelY >= this.mapPixelHeight;
    }

    static {
        int[] nArray = new int[]{0, 270, 180, 90, 8192, 8462, 8372, 8282};
        transformLookupTable = new int[]{0, 5, 3, 6, 2, 4, 1, 7};
    }
}

