/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import javax.microedition.lcdui.Graphics;

public final class MenuWidget
implements UIComponent {
    private int componentId = -1;
    private int x = 0;
    private int y = 0;
    private int width = 0;
    private int height = 0;
    private int componentType = 0;
    private byte[][] i = null;
    private UIStyle style = new UIStyle();
    private int parentId = -1;
    private byte l;
    private UISelectionConfig selection = null;
    private UIComponent[] children = new UIComponent[60];
    public UISelectionConfig a = null;
    public UISelectionConfig b = null;
    private boolean visible = true;

    public MenuWidget() {
        this.l = (byte)9;
    }

    public final void setVisible(boolean bl) {
        this.visible = bl;
    }

    public final void a(byte[][] byArray) {
        this.i = byArray;
    }

    public final byte[][] l() {
        return this.i;
    }

    public final void render(Graphics graphics, boolean bl, boolean bl2, UIComponent uIComponent, int[] nArray) {
        if (!this.visible) {
            return;
        }
        for (int i = 0; i < this.children.length && this.children[i] != null; ++i) {
            if (this.children[i].getSelection() != null) {
                boolean bl3 = false;
                int n = EngineUtils.a(nArray);
                if (n > 0 && nArray[n - 1] == this.componentId) {
                    bl3 = true;
                }
                this.children[i].getSelection().a(graphics, this.children[i].getId(), bl3, nArray, bl2, uIComponent);
                continue;
            }
            this.children[i].render(graphics, bl, bl2, uIComponent, nArray);
        }
    }

    public final void a(boolean bl, boolean bl2, UIComponent uIComponent, int[] nArray) {
        for (int i = 0; i < this.children.length && this.children[i] != null; ++i) {
            if (this.children[i].getSelection() != null) {
                this.children[i].getSelection().a(this.children[i].getId(), nArray, bl2, uIComponent);
                continue;
            }
            this.children[i].a(bl, bl2, uIComponent, nArray);
        }
    }

    public final int getId() {
        return this.componentId;
    }

    public final void a(int n) {
        this.componentId = n;
    }

    public final int getX() {
        return this.x;
    }

    public final void setX(int n, UIComponent uIComponent) {
        this.x = n;
        this.updateLayout(uIComponent);
    }

    public final int getY() {
        return this.y;
    }

    public final void setY(int n, UIComponent uIComponent) {
        this.y = n;
        this.updateLayout(uIComponent);
    }

    public final int getWidth() {
        return this.width;
    }

    public final void setWidth(int n, UIComponent uIComponent) {
        this.width = n;
        this.updateLayout(uIComponent);
    }

    public final int getHeight() {
        return this.height;
    }

    public final void setHeight(int n, UIComponent uIComponent) {
        this.height = n;
        this.updateLayout(uIComponent);
    }

    public final UISelectionConfig getSelection() {
        return this.selection;
    }

    public final void a(UISelectionConfig uISelectionConfig) {
        this.selection = uISelectionConfig;
    }

    public final UIComponent[] getChildren() {
        return this.children;
    }

    public final UIStyle getStyle() {
        return this.style;
    }

    public final void setStyle(UIStyle uIStyle) {
        this.style = uIStyle;
    }

    public final int getType() {
        return this.componentType;
    }

    public final void b(int n) {
        this.componentType = n;
    }

    public final int getParentId() {
        return this.parentId;
    }

    public final void c(int n) {
        this.parentId = n;
    }

    public final void updateLayout(UIComponent uIComponent) {
        if (uIComponent != null) {
            if (this.parentId > 0 && this.l != 9) {
                UIComponent uIComponent2 = EngineUtils.a(uIComponent, this.parentId);
                switch (this.l) {
                    case 4: {
                        this.x = uIComponent2.getX();
                        this.y = uIComponent2.getY();
                        this.width = uIComponent2.getWidth();
                        this.height = uIComponent2.getHeight();
                        break;
                    }
                    case 3: {
                        this.x = uIComponent2.getX();
                        this.y = uIComponent2.getY() + (uIComponent2.getHeight() - this.height) / 2;
                        this.height = uIComponent2.getHeight();
                        break;
                    }
                    case 5: {
                        this.x = uIComponent2.getX() + (uIComponent2.getWidth() - this.width);
                        this.y = uIComponent2.getY() + (uIComponent2.getHeight() - this.height) / 2;
                        this.height = uIComponent2.getHeight();
                        break;
                    }
                    case 6: {
                        this.x = uIComponent2.getX();
                        this.y = uIComponent2.getY() + (uIComponent2.getHeight() - this.height);
                        break;
                    }
                    case 8: {
                        this.x = uIComponent2.getX() + (uIComponent2.getWidth() - this.width);
                        this.y = uIComponent2.getY() + (uIComponent2.getHeight() - this.height);
                        break;
                    }
                    case 7: {
                        this.x = uIComponent2.getX() + (uIComponent2.getWidth() - this.width) / 2;
                        this.y = uIComponent2.getY() + (uIComponent2.getHeight() - this.height);
                        this.width = uIComponent2.getWidth();
                        break;
                    }
                    case 0: {
                        this.x = uIComponent2.getX();
                        this.y = uIComponent2.getY();
                        break;
                    }
                    case 2: {
                        this.x = uIComponent2.getX() + (uIComponent2.getWidth() - this.width);
                        this.y = uIComponent2.getY();
                        break;
                    }
                    case 1: {
                        this.x = uIComponent2.getX() + (uIComponent2.getWidth() - this.width) / 2;
                        this.y = uIComponent2.getY();
                        this.width = uIComponent2.getWidth();
                    }
                }
            }
            if (this.children != null) {
                for (int i = 0; i < this.children.length && this.children[i] != null; ++i) {
                    this.children[i].updateLayout(uIComponent);
                }
            }
        }
    }

    public final void release() {
        if (this.b != null) {
            this.b.a();
            this.b = null;
        }
        if (this.a != null) {
            this.a.a();
            this.a = null;
        }
        if (this.children != null) {
            for (int i = 0; i < this.children.length; ++i) {
                if (this.children[i] != null) {
                    this.children[i].release();
                }
                this.children[i] = null;
            }
            this.children = null;
        }
        if (this.selection != null) {
            this.selection = null;
        }
        if (this.i != null) {
            this.i = null;
        }
        if (this.style != null) {
            this.style.c();
            this.style = null;
        }
    }
}

