/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import javax.microedition.lcdui.Graphics;

public final class MessageBox
implements UIComponent {
    private int f = 0;
    private int g = 0;
    private int h = 0;
    private int i = 0;
    private int j = 0;
    private int k = 0;
    private int l = 0;
    private int m = 0;
    private int n = 0;
    private int o = 0;
    private int p = 0;
    private int q = 0;
    private int r = 0;
    private int s = 0;
    private int t;
    private int u;
    private int v;
    private int w;
    private int x = 0;
    public int a;
    public SpriteWidget b;
    public SpriteWidget c = null;
    public boolean d = false;
    private boolean y = true;
    private int z = -1;
    private int A = 2;
    private int B = -1;
    UIHotspot[] e = new UIHotspot[0];

    public final void a(int n) {
        this.h = n;
    }

    public final void b(int n) {
        this.i = n;
    }

    public final void c(int n) {
        this.j = n;
    }

    public final void d(int n) {
        this.k = n;
    }

    public final int l() {
        return this.l;
    }

    public final void e(int n) {
        this.l = n;
    }

    public final int m() {
        return this.m;
    }

    public final void f(int n) {
        this.m = n;
    }

    public final void g(int n) {
        if (n <= 0 || n > this.l) {
            this.p = this.l;
            return;
        }
        this.p = n;
    }

    public final void h(int n) {
        if (n <= 0 || n > this.m) {
            this.r = this.m;
            return;
        }
        this.r = n;
    }

    public final void i(int n) {
        this.q = n;
    }

    public final void j(int n) {
        this.s = n;
    }

    private int o() {
        return this.s + this.r - 1;
    }

    private int p() {
        return this.q + this.p - 1;
    }

    public final void k(int n) {
        this.n = n;
    }

    public final void l(int n) {
        this.o = n;
    }

    public final void m(int n) {
        this.t = n;
    }

    public final void n(int n) {
        this.v = n;
    }

    public final void o(int n) {
        this.u = n;
    }

    public final void p(int n) {
        this.w = n;
    }

    public final UIHotspot[] n() {
        int n;
        int n2;
        int n3;
        int n4;
        int n5;
        int n6;
        UIHotspot uIHotspot;
        Object object;
        int n7;
        int n8 = this.m;
        int n9 = this.l;
        UIHotspot[] uIHotspotArray = new UIHotspot[n9 * n8];
        for (n7 = 0; n7 != n9 * n8; ++n7) {
            object = new UIHotspot(n7 - n9, n7 + n9, n7 - 1, n7 + 1);
            uIHotspotArray[n7] = object;
        }
        UIHotspot[] uIHotspotArray2 = uIHotspotArray;
        int n10 = this.m;
        int n11 = this.l;
        UIHotspot[] uIHotspotArray3 = uIHotspotArray2;
        MessageBox messageBox = this;
        for (n7 = 0; n7 != n10; ++n7) {
            object = new UIHotspot(0);
            uIHotspot = new UIHotspot(0);
            int n12 = -1;
            n6 = -1;
            for (n5 = 0; n5 != n11; ++n5) {
                if (((UIHotspot)object).a() == 0 && uIHotspotArray3[n7 * n11 + n5].a() == 1) {
                    object = uIHotspotArray3[n7 * n11 + n5];
                    n12 = n7 * n11 + n5;
                }
                if (uIHotspot.a() != 0 || uIHotspotArray3[(n7 + 1) * n11 - n5 - 1].a() != 1) continue;
                uIHotspot = uIHotspotArray3[(n7 + 1) * n11 - n5 - 1];
                n6 = (n7 + 1) * n11 - n5 - 1;
            }
            if (((UIHotspot)object).a() != 1) continue;
            if (messageBox.t == 0) {
                ((UIHotspot)object).c(n12);
                uIHotspot.d(n6);
                continue;
            }
            UIHotspot[] uIHotspotArray4 = object;
            n4 = n12;
            n5 = n10;
            n12 = n11;
            object = uIHotspotArray3;
            n3 = -1;
            for (n2 = 0; n2 != ((UIHotspot[])object).length; ++n2) {
                n = n4 - n2 - 1;
                if (n < 0) {
                    n += n12 * n5;
                }
                if (n3 != -1 || ((UIHotspot)object[n]).a() != 1) continue;
                n3 = n;
            }
            uIHotspotArray4.c(n3);
            n4 = n6;
            n5 = n10;
            n12 = n11;
            object = uIHotspotArray3;
            n3 = -1;
            for (n2 = 0; n2 != ((Object)object).length; ++n2) {
                n = n4 + n2 + 1;
                if (n >= n12 * n5) {
                    n -= n12 * n5;
                }
                if (n3 != -1 || ((UIHotspot)object[n]).a() != 1) continue;
                n3 = n;
            }
            uIHotspot.d(n3);
        }
        n10 = this.m;
        n11 = this.l;
        uIHotspotArray3 = uIHotspotArray2;
        messageBox = this;
        for (n7 = 0; n7 != n11; ++n7) {
            int n13;
            object = new UIHotspot(0);
            uIHotspot = new UIHotspot(0);
            int n14 = -1;
            n6 = -1;
            for (n5 = 0; n5 != n10; ++n5) {
                if (((UIHotspot)object).a() == 0 && uIHotspotArray3[n7 + n11 * n5].a() == 1) {
                    object = uIHotspotArray3[n7 + n11 * n5];
                    n14 = n7 + n11 * n5;
                }
                if (uIHotspot.a() != 0 || uIHotspotArray3[n7 + n11 * (n10 - n5 - 1)].a() != 1) continue;
                uIHotspot = uIHotspotArray3[n7 + n11 * (n10 - n5 - 1)];
                n6 = n7 + n11 * (n10 - n5 - 1);
            }
            if (((UIHotspot)object).a() != 1) continue;
            if (messageBox.v == 0) {
                ((UIHotspot)object).a(n14);
                uIHotspot.b(n6);
                continue;
            }
            Object object2 = object;
            int n15 = n14;
            n4 = n10;
            n5 = n11;
            UIHotspot[] uIHotspotArray5 = uIHotspotArray3;
            object = messageBox;
            n3 = -1;
            n2 = n15 % n5;
            for (n = 0; n != n4; ++n) {
                n13 = n15 / n5 - 1 - n;
                if (n13 < 0) {
                    n13 += n4;
                }
                if (n3 != -1 || uIHotspotArray5[n13 * ((MessageBox)object).l + n2].a() != 1) continue;
                n3 = n13 * ((MessageBox)object).l + n2;
            }
            ((UIHotspot)object2).a(n3);
            n15 = n6;
            n4 = n10;
            n5 = n11;
            uIHotspotArray5 = uIHotspotArray3;
            object = messageBox;
            n3 = -1;
            n2 = n15 % n5;
            for (n = 0; n != n4; ++n) {
                n13 = n15 / n5 + 1 + n;
                if (n13 >= n4) {
                    n13 -= n4;
                }
                if (n3 != -1 || uIHotspotArray5[n13 * ((MessageBox)object).l + n2].a() != 1) continue;
                n3 = n13 * ((MessageBox)object).l + n2;
            }
            uIHotspot.b(n3);
        }
        return uIHotspotArray2;
    }

    public final boolean a(byte by) {
        boolean bl = false;
        int n = this.x;
        if (by == 0) {
            if (this.e[this.x].a() == 1 && n != this.e[this.x].b()) {
                n = this.e[this.x].b();
                bl = true;
            }
        } else if (by == 1) {
            if (this.e[this.x].a() == 1 && n != this.e[this.x].c()) {
                n = this.e[this.x].c();
                bl = true;
            }
        } else if (by == 2) {
            if (this.e[this.x].a() == 1 && n != this.e[this.x].d()) {
                n = this.e[this.x].d();
                bl = true;
            }
        } else if (by == 3 && this.e[this.x].a() == 1 && n != this.e[this.x].e()) {
            n = this.e[this.x].e();
            bl = true;
        }
        this.r(n);
        return bl;
    }

    public final void render(Graphics graphics, boolean bl, boolean n, UIComponent uIComponent, int[] nArray) {
        if (!this.y) {
            return;
        }
        if (graphics != null) {
            graphics.setColor(this.a);
            graphics.fillRect(this.f, this.g, this.getWidth(), this.getHeight());
            Rectangle rectangle = new Rectangle(this.f, this.g, this.getWidth(), this.getHeight());
            if (this.b != null && graphics != null) {
                this.b.a(graphics, rectangle, 0);
            }
            n = this.o();
            int n2 = this.p();
            for (int i = this.s; i <= n; ++i) {
                for (int j = this.q; j <= n2; ++j) {
                    rectangle = new Rectangle(this.f + this.j + (j - this.q) * (this.j + this.h), this.g + this.k + (i - this.s) * (this.k + this.i), this.h, this.i);
                    SpriteWidget spriteWidget = this.e[i * this.l + j].a;
                    if (spriteWidget == null || graphics == null) continue;
                    spriteWidget.a(graphics, rectangle, 0);
                }
            }
            rectangle = new Rectangle(this.f + this.j + (this.x % this.l - this.q) * (this.j + this.h) + this.n, this.g + this.k + (this.x / this.l - this.s) * (this.k + this.i) + this.o, this.getWidth(), this.getHeight());
            if (this.d && this.c != null && graphics != null) {
                this.c.a(graphics, rectangle, 0);
            }
        }
    }

    public final void a(boolean n, boolean bl, UIComponent uIComponent, int[] nArray) {
        if (this.b != null) {
            this.b.c();
        }
        for (n = 0; n < this.e.length; ++n) {
            if (this.e[n].a == null) continue;
            this.e[n].a.c();
        }
        if (this.d && this.c != null) {
            this.c.c();
        }
    }

    public final int getId() {
        return this.z;
    }

    public final void q(int n) {
        this.z = n;
    }

    public final int getX() {
        return this.f;
    }

    public final void setX(int n, UIComponent uIComponent) {
        this.f = n;
    }

    public final int getY() {
        return this.g;
    }

    public final void setY(int n, UIComponent uIComponent) {
        this.g = n;
    }

    public final int getWidth() {
        if (this.p > 0 && this.p <= this.l) {
            return (this.h + this.j) * this.p + this.j;
        }
        return (this.h + this.j) * this.l + this.j;
    }

    public final void setWidth(int n, UIComponent uIComponent) {
    }

    public final int getHeight() {
        if (this.r > 0 && this.r <= this.m) {
            return (this.i + this.k) * this.r + this.k;
        }
        return (this.i + this.k) * this.m + this.k;
    }

    public final void setHeight(int n, UIComponent uIComponent) {
    }

    public final void r(int n) {
        if (this.e != null && n > -2 && n < this.e.length) {
            MessageBox messageBox;
            this.x = n;
            MessageBox messageBox2 = messageBox = this;
            int n2 = messageBox.x / messageBox2.l;
            if (messageBox2.w == 1) {
                messageBox2.s = n2 / messageBox2.r * messageBox2.r;
            } else if (n2 < messageBox2.s) {
                messageBox2.s = n2;
            } else if (n2 > messageBox2.o()) {
                v0.s = n2 - messageBox2.r + 1;
            }
            messageBox2 = messageBox;
            n2 = messageBox2.x % messageBox2.l;
            if (messageBox2.u == 1) {
                messageBox2.q = n2 / messageBox2.p * messageBox2.p;
                return;
            }
            if (n2 < messageBox2.q) {
                messageBox2.q = n2;
                return;
            }
            if (n2 > messageBox2.p()) {
                v1.q = n2 - messageBox2.p + 1;
            }
        }
    }

    public final UISelectionConfig getSelection() {
        return null;
    }

    public final UIComponent[] getChildren() {
        return null;
    }

    public final UIStyle getStyle() {
        return null;
    }

    public final void setStyle(UIStyle uIStyle) {
    }

    public final int getType() {
        return this.A;
    }

    public final int getParentId() {
        return this.B;
    }

    public final void s(int n) {
        this.B = n;
    }

    public final void updateLayout(UIComponent uIComponent) {
    }

    public final void release() {
        if (this.c != null) {
            this.c.d();
            this.c = null;
        }
        if (this.b != null) {
            this.b.d();
            this.b = null;
        }
        if (this.e != null) {
            for (int i = 0; i < this.e.length; ++i) {
                if (this.e[i] == null) continue;
                this.e[i].a.d();
                this.e[i] = null;
            }
            this.e = null;
        }
    }

    public final void setVisible(boolean bl) {
        this.y = bl;
    }
}

