/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import java.io.DataInputStream;
import java.io.InputStream;
import java.util.Vector;

public class ResourceStream
extends DataInputStream {
    private String resourcePath;
    private static Vector openStreams = new Vector();
    private static Class resourceClass;

    private ResourceStream(InputStream inputStream, String string) {
        super(inputStream);
        this.resourcePath = string;
    }

    public static InputStream openResource(String path) {
        InputStream inputStream;
        Class<?> clazz = resourceClass;
        if (clazz == null) {
            try {
                clazz = resourceClass = Class.forName("aj");
            }
            catch (ClassNotFoundException classNotFoundException) {
                throw new NoClassDefFoundError(classNotFoundException.getMessage());
            }
        }
        if ((inputStream = clazz.getResourceAsStream(path)) != null) {
            inputStream = new ResourceStream(inputStream, path);
            openStreams.addElement(inputStream);
            if (openStreams.size() > 10) {
                System.out.println("current size: " + openStreams.size());
                int n = 0;
                while (n < openStreams.size()) {
                    ResourceStream resourceStream = (ResourceStream)openStreams.elementAt(n);
                    try {
                        if (resourceStream.available() == 0) {
                            System.out.println("auto close1: " + resourceStream.resourcePath);
                            resourceStream.close();
                            --n;
                        }
                    }
                    catch (Exception exception) {}
                    ++n;
                }
                System.out.println("new size: " + openStreams.size());
                if (openStreams.size() > 10) {
                    ResourceStream resourceStream = (ResourceStream)openStreams.elementAt(0);
                    try {
                        System.out.println("auto close2: " + resourceStream.resourcePath);
                        resourceStream.close();
                    }
                    catch (Exception exception) {}
                }
            }
        }
        return inputStream;
    }

    public void close() {
        openStreams.removeElement(this);
        try {
            super.close();
            return;
        }
        catch (Exception exception) {
            System.out.println("close error");
            return;
        }
    }
}

