/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import game.BattleScreen;
import game.ScriptEngine;
import game.WorldManager;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

public final class ScreenView {
    private static ScreenView e;
    public int a = -1;
    private int f = -1;
    private int g = -1;
    private int h = -1;
    public boolean b;
    public boolean c;
    private int i;
    private int j;
    private int k = 0;
    private int l = 20;
    private int m = 5;
    private int n = -2013265920;
    private int[] o = null;
    private int[] p = null;
    private int[] q = null;
    private int r = 16;
    private int s = 4;
    private int t = 0;
    private int[][] u;
    private int[] v;
    private int w = 20;
    private int x;
    private static UIManager y;
    private static ScriptEngine z;
    private static short[][] A;
    private short[][] B = new short[][]{{-20, 20, 20, -20, -15, 15, -15, 15, -5, 5, -5, 5}, {-5, 5, 5, -5}, {-5, 10, -5}};
    private int C = 0;
    private int D = 0;
    private int E = 0;
    private int F = 0;
    private int G = 0;
    private int H = 0;
    private int I;
    private int J;
    private int K;
    private int L = 0;
    private int M = 0;
    private Image N = null;
    private PixelBuffer O = null;
    private int P;
    private int Q;
    private int R = 0;
    private int S = 0;
    private int T = 0;
    private int U = 0;
    private int[] V = new int[]{0xFFFFFF, 9115396};
    private static int W;
    private static int[] X;
    private SkillEffect Y;
    private int Z = 0;
    private int aa = 0;
    public byte d = (byte)-1;
    private int ab;
    private int ac;
    private int ad;
    private int ae;
    private int af;
    private int ag;
    private static final int[][] ah;
    private byte ai = (byte)30;
    private Image[] aj;
    private int[][] ak;
    private int al = 0;
    private int am = 0;
    private byte an = 0;

    public static ScreenView a() {
        if (e == null) {
            e = new ScreenView();
        }
        y = UIManager.getInstance();
        z = ScriptEngine.a();
        return e;
    }

    /*
     * Unable to fully structure code
     */
    public final void a(Graphics var1_1) {
        if (this.a == -1 && this.g == -1 && this.h == -1) {
            return;
        }
        switch (this.h) {
            case 18: {
                ScreenView.y.render(var1_1);
                if (this.i < (null).length) break;
                this.i = 0;
                this.h = -1;
                this.b = true;
                ScreenView.y.closeUI("/data/ui/menu1.ui");
                return;
            }
        }
        switch (this.a) {
            case 0:
            case 1:
            case 2: {
                var3_2 = var1_1;
                var2_8 = this;
                var4_13 = var2_8.n & 0xFFFFFF;
                var6_21 = false;
                var5_24 = 0;
                if (var2_8.a == 0) {
                    var5_24 = var2_8.n;
                } else if (var2_8.a == 1) {
                    if (255 - var2_8.k * var2_8.m < 0) {
                        --var2_8.k;
                        var2_8.a = -1;
                        var6_21 = true;
                    }
                    var5_24 = 255 - var2_8.k * var2_8.m << 24;
                    var5_24 = var4_13 | var5_24;
                } else if (var2_8.a == 2) {
                    if (var2_8.k * var2_8.m > 255) {
                        --var2_8.k;
                        var6_21 = true;
                    }
                    var5_24 = var2_8.k * var2_8.m << 24;
                    var5_24 = var4_13 | var5_24;
                }
                var7_31 = var2_8.w;
                var8_33 = BaseScreen.getScreenHeight() / var7_31 + 1;
                var4_13 = BaseScreen.getScreenWidth() * var8_33;
                if (var2_8.o == null || var2_8.o.length != var4_13) {
                    var2_8.o = new int[var4_13];
                }
                if (var2_8.o[0] != var5_24) {
                    for (var9_35 = 0; var9_35 < var2_8.o.length; ++var9_35) {
                        var2_8.o[var9_35] = var5_24;
                    }
                }
                for (var9_35 = 0; var9_35 < var7_31; ++var9_35) {
                    var3_2.drawRGB(var2_8.o, 0, BaseScreen.getScreenWidth(), 0, var9_35 * var8_33, BaseScreen.getScreenWidth(), var8_33, true);
                }
                if (var6_21) {
                    var2_8.d();
                    v0 = true;
                } else {
                    ++var2_8.k;
                    v0 = false;
                }
                this.b = v0;
                break;
            }
            case 3: {
                var3_3 = var1_1;
                var2_9 = this;
                var4_14 = BaseScreen.getScreenWidth();
                var5_25 = BaseScreen.getScreenHeight();
                var6_22 = var2_9.n & 0xFFFFFF;
                var7_32 = var2_9.l;
                var8_34 = 255 / var7_32 / 2;
                var9_36 = var5_25 / 2;
                var10_37 = (var4_14 /= 2) * 200 / 120;
                var11_38 = var10_37 * var10_37;
                var12_39 = false;
                if (var2_9.q == null) {
                    var2_9.q = new int[var10_37];
                }
                var13_40 = var10_37 + var7_32 - (var2_9.k << 1);
                if (var2_9.k <= 0) {
                    var12_39 = true;
                    var13_40 = var10_37 + var7_32 - (--var2_9.k << 1);
                }
                if (var2_9.o == null || var2_9.o.length != var4_14 * var9_36) {
                    var2_9.o = new int[var4_14 * var9_36];
                }
                if (var2_9.p == null || var2_9.p.length != var4_14 * var9_36) {
                    var2_9.p = new int[var4_14 * var9_36];
                }
                for (var14_41 = 0; var14_41 < var2_9.q.length; ++var14_41) {
                    var5_25 = var14_41 - var13_40;
                    var5_25 = var5_25 > var7_32 ? 255 : (var5_25 < -var7_32 ? 0 : 127 + var5_25 * var8_34);
                    var2_9.q[var14_41] = var6_22 | var5_25 << 24;
                }
                var14_41 = var10_37 - 1;
                var5_25 = var13_40 + var7_32;
                var6_22 = var13_40 - var7_32;
                if (var6_22 < 0) {
                    var6_22 = 0;
                }
                var5_25 = var5_25 * var11_38 / var14_41;
                var6_22 = var6_22 * var11_38 / var14_41;
                for (var7_32 = 0; var7_32 < var9_36; ++var7_32) {
                    var10_37 = var7_32 * var7_32;
                    var13_40 = var7_32 * var4_14;
                    for (var15_42 = 0; var15_42 < var4_14; ++var15_42) {
                        var8_34 = var10_37 + var15_42 * var15_42;
                        var2_9.o[var13_40 + var15_42] = var8_34 > var5_25 ? -16777216 : (var8_34 < var6_22 ? 0 : var2_9.q[var14_41 * var8_34 / var11_38]);
                    }
                }
                if (var2_9.o != null) {
                    var3_3.drawRGB(var2_9.o, 0, var4_14, var4_14, var9_36, var4_14, var9_36, true);
                    var3_3.drawRGB(ScreenView.a(var2_9.o, var2_9.p, var4_14, var9_36, (byte)2), 0, var4_14, 0, var9_36, var4_14, var9_36, true);
                    var3_3.drawRGB(ScreenView.a(var2_9.o, var2_9.p, var4_14, var9_36, (byte)3), 0, var4_14, 0, 0, var4_14, var9_36, true);
                    var3_3.drawRGB(ScreenView.a(var2_9.o, var2_9.p, var4_14, var9_36, (byte)1), 0, var4_14, var4_14, 0, var4_14, var9_36, true);
                }
                if (var12_39) {
                    var2_9.d();
                    v1 = true;
                } else {
                    var2_9.k -= 10;
                    v1 = false;
                }
                this.b = v1;
                break;
            }
            case 4: {
                if (this.b) {
                    this.a = -1;
                    var1_1.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                    break;
                }
                v2 = this;
                v3 = this.d(var1_1);
                ** GOTO lbl302
            }
            case 5: {
                if (this.b) break;
                v2 = this;
                v3 = this.d(var1_1);
                ** GOTO lbl302
            }
            case 6: {
                if (this.b) {
                    this.a = -1;
                    var1_1.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                    break;
                }
                var3_4 = var1_1;
                var2_10 = this;
                if (var2_10.i >= 10) ** GOTO lbl142
                if (var2_10.i % 3 == 1) {
                    var3_4.setColor(0xFFFFFF);
                    var3_4.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                } else {
                    WorldManager.a();
                    WorldManager.a(var3_4, 0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                    WorldManager.a().b.a(var3_4);
                }
                ++var2_10.i;
                ** GOTO lbl185
lbl142:
                // 1 sources

                if (var2_10.i >= BaseScreen.getScreenWidth()) {
                    var3_4.setColor(0);
                    var3_4.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                    v4 = true;
                } else {
                    switch (var2_10.x) {
                        case 0: {
                            var3_4.setColor(0);
                            var3_4.fillRect(0, 0, var2_10.i, BaseScreen.getHalfHeight());
                            for (var4_15 = 1; var4_15 < 6; ++var4_15) {
                                var3_4.fillRect(var2_10.i + var4_15 * 15, 0, 15 - var4_15 * 3, BaseScreen.getHalfHeight());
                            }
                            var3_4.fillRect(BaseScreen.getScreenWidth() - var2_10.i, BaseScreen.getHalfHeight(), var2_10.i, BaseScreen.getHalfHeight());
                            for (var4_15 = 1; var4_15 < 6; ++var4_15) {
                                var3_4.fillRect(BaseScreen.getScreenWidth() - var2_10.i - var4_15 * 15, BaseScreen.getHalfHeight(), 15 - var4_15 * 3, BaseScreen.getHalfHeight());
                            }
                            var2_10.i += 15;
                            break;
                        }
                        case 1: {
                            var3_4.setColor(0);
                            var4_16 = false;
                            for (var5_26 = 0; var5_26 < BaseScreen.getScreenHeight(); var5_26 += 10) {
                                if (var4_16) {
                                    var3_4.fillRect(0, var5_26, var2_10.i, 10);
                                    var4_16 = false;
                                    continue;
                                }
                                var3_4.fillRect(BaseScreen.getScreenWidth() - var2_10.i, var5_26, var2_10.i, 10);
                                var4_16 = true;
                            }
                            var2_10.i += 15;
                            break;
                        }
                        case 2: {
                            var3_4.setColor(0);
                            var4_17 = false;
                            for (var5_27 = 0; var5_27 < BaseScreen.getScreenWidth(); var5_27 += 10) {
                                if (var4_17) {
                                    var3_4.fillRect(var5_27, 0, 10, var2_10.i);
                                    var4_17 = false;
                                    continue;
                                }
                                var3_4.fillRect(var5_27, BaseScreen.getScreenHeight() - var2_10.i, 10, var2_10.i);
                                var4_17 = true;
                            }
                            var2_10.i += 15;
                        }
                    }
lbl185:
                    // 5 sources

                    v4 = false;
                }
                this.b = v4;
                break;
            }
            case 7: {
                if (this.Y == null) break;
                this.Y.a(var1_1);
                break;
            }
            case 8: {
                if (this.i >= 5) {
                    var1_1.drawImage(BattleScreen.a().c, 0, 0, 20);
                }
                ScreenView.y.render(var1_1);
                if (this.i < ScreenView.A.length) break;
                this.i = 0;
                this.a = -1;
                this.b = true;
                ScreenView.y.closeUI("/data/ui/npcEnemy.ui");
                return;
            }
            case 9: {
                var1_1.setColor(this.n);
                var1_1.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                break;
            }
            case 10: {
                if (this.i > this.L) break;
                if (this.i % 3 / (this.M + 1) == 0) {
                    var1_1.setColor(0xFFFFFF);
                    var1_1.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                } else if (this.i % 3 / (this.M + 1) == 1) {
                    var1_1.setColor(0);
                    var1_1.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                }
                ++this.i;
                break;
            }
            case 14:
            case 15: {
                var3_5 = var1_1;
                var2_11 = this;
                var4_18 = false;
                var5_28 = 0;
                if (var2_11.a == 15) {
                    var5_28 = var2_11.k;
                    if (var5_28 >= 255) {
                        var5_28 = 255;
                        var2_11.k = 255;
                        var4_18 = true;
                    }
                } else if (var2_11.a == 14 && (var5_28 = 255 - var2_11.k) <= 0) {
                    var5_28 = 0;
                    var2_11.a = -1;
                    var4_18 = true;
                }
                if (var2_11.O != null) {
                    var2_11.O = ImageTransformer.b(var2_11.O, var5_28);
                    var3_5.drawRGB(var2_11.O.a, 0, var2_11.O.b, var2_11.P - var2_11.O.b / 2, var2_11.Q - var2_11.O.c / 2, var2_11.O.b, var2_11.O.c, true);
                }
                if (var4_18) {
                    var2_11.a = -1;
                    var2_11.d();
                    v5 = true;
                } else {
                    var2_11.k += var2_11.m;
                    v5 = false;
                }
                this.b = v5;
                break;
            }
            case 17: {
                var1_1.setColor(this.V[this.n]);
                var5_29 = this.R;
                var4_19 = this.U;
                var3_6 = this.T;
                var1_1.fillArc(var3_6 - var5_29, var4_19 - var5_29, var5_29 << 1, var5_29 << 1, 0, 360);
                break;
            }
            case 19:
            case 20: {
                v2 = this;
                var3_7 = var1_1;
                var2_12 = this;
                var3_7.setColor(var2_12.n);
                var4_20 = 0;
                for (var5_30 = 0; var5_30 < ScreenView.W; ++var5_30) {
                    for (var6_23 = 0; var6_23 < ScreenView.X[1]; ++var6_23) {
                        switch (ScreenView.X[2]) {
                            case 1: {
                                var4_20 = ScreenView.X[0];
                                break;
                            }
                            case -1: {
                                var4_20 = 0;
                            }
                        }
                        switch (ScreenView.X[3]) {
                            case 0: {
                                var4_20 = (var4_20 += (var6_23 - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                                break;
                            }
                            case 1: {
                                var4_20 = (var4_20 += (ScreenView.X[1] - var6_23 - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                                break;
                            }
                            case 2: {
                                var4_20 = (var4_20 += (var5_30 - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                                break;
                            }
                            case 3: {
                                var4_20 = (var4_20 += (8 - var5_30 - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                                break;
                            }
                            case 4: {
                                var4_20 = (var4_20 += ((var5_30 + var6_23 >> 1) - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                                break;
                            }
                            case 5: {
                                var4_20 = (var4_20 += ((8 - var5_30 + var6_23 >> 1) - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                                break;
                            }
                            case 6: {
                                var4_20 = (var4_20 += ((var5_30 + ScreenView.X[1] - var6_23 >> 1) - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                                break;
                            }
                            case 7: {
                                var4_20 = (var4_20 += ((8 - var5_30 + ScreenView.X[1] - var6_23 >> 1) - ScreenView.X[4]) * ScreenView.X[2]) < 0 ? 0 : (var4_20 > ScreenView.X[0] ? ScreenView.X[0] : var4_20);
                            }
                        }
                        var3_7.fillRect(ScreenView.X[0] * var5_30 + (ScreenView.X[0] - var4_20 >> 1), ScreenView.X[0] * var6_23 + (ScreenView.X[0] - var4_20 >> 1), var4_20, var4_20);
                    }
                }
                ScreenView.X[4] = ScreenView.X[4] + 2;
                if (ScreenView.X[4] > 40) {
                    if (var2_12.a == 20) {
                        var2_12.a = -1;
                    }
                    if (var2_12.a == 19) {
                        var3_7.fillRect(0, 0, BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                    }
                    v3 = true;
                } else {
                    v3 = false;
                }
lbl302:
                // 4 sources

                v2.b = v3;
            }
        }
        switch (this.g) {
            case 12: {
                var1_1.setColor(0);
                var1_1.fillRect(0, 0, this.I, this.J - this.j * this.J / this.G);
                var1_1.fillRect(0, BaseScreen.getScreenHeight() - this.K + this.j * this.K / this.G, this.I, this.K - this.j * this.K / this.G);
                return;
            }
            case 13: {
                var1_1.setColor(0);
                var1_1.fillRect(0, 0, this.I, this.j * this.J / this.G);
                var1_1.fillRect(0, BaseScreen.getScreenHeight() - this.j * this.K / this.G, this.I, this.j * this.K / this.G);
            }
        }
    }

    private void a(int n) {
        this.aa = n;
        switch (this.a) {
            case 7: {
                n = GameDatabase.gameDatabase[0][BattleScreen.a().k()][17];
                switch (this.aa) {
                    case 0: {
                        short[] sArray = new short[]{8, 118, 160, n, 0, 1, 0, 4, 0, 2, 1, 8, 0, -16, 10, 0, 0};
                        this.Y = new SkillEffect();
                        this.Y.a(sArray);
                        this.Y.c(true);
                        this.Y.a();
                        return;
                    }
                    case 1: {
                        short[] sArray = new short[]{17, 118, 160, n, 0, 1, 100, 255, 255, 255, 12, 0, 1, 1, 9};
                        this.Y.a(sArray);
                        this.Y.a();
                        return;
                    }
                    case 2: {
                        short[] sArray = new short[]{17, 118, 160, n, 0, 1, 255, 255, 255, 255, 15, 0, 1, 1, 13};
                        this.Y.a(sArray);
                        this.Y.a();
                        return;
                    }
                    case 3: {
                        short[] sArray = new short[]{9, 118, 160, n, 0, 1, 160, 255, 255, 255, 0, 4, 1};
                        this.Y.a(sArray);
                        this.Y.a();
                    }
                }
                return;
            }
            case 8: {
                this.Z = A[this.i].length;
            }
        }
    }

    public final void b() {
        if (this.a == -1 && this.g == -1 && this.h == -1) {
            return;
        }
        switch (this.a) {
            case 8: {
                if (this.aa < this.Z) {
                    z.b(this.i, A[this.i][this.aa]);
                    ++this.aa;
                } else {
                    ++this.i;
                    if (this.i < A.length) {
                        this.a(0);
                    }
                }
                y.update();
                break;
            }
            case 7: {
                if (this.Y == null || this.Y.e()) break;
                ++this.aa;
                if (this.aa >= 4) {
                    this.b = true;
                    this.a = -1;
                    this.i = 0;
                    this.Y = null;
                    return;
                }
                this.a(this.aa);
                break;
            }
            case 11: {
                if (this.C == 0) {
                    if (this.F >= this.B[this.D].length * this.E) {
                        this.a = -1;
                        this.b = true;
                        this.F = 0;
                        ParticleEffect.a().a = ParticleEffect.a().b;
                        return;
                    }
                    ParticleEffect.a().movePosX(this.B[this.D][this.F % this.B[this.D].length]);
                    ++this.F;
                    break;
                }
                if (this.F >= this.B[this.D].length * this.E) {
                    this.a = -1;
                    this.b = true;
                    this.F = 0;
                    ParticleEffect.a().a = ParticleEffect.a().b;
                    return;
                }
                ParticleEffect.a().movePosY(this.B[this.D][this.F % this.B[this.D].length]);
                ++this.F;
                break;
            }
            case 10: {
                if (this.i <= this.L) break;
                this.b = true;
                this.a = -1;
                this.i = 0;
                break;
            }
            case 17: {
                ++this.i;
                if (this.S == 0) {
                    if ((BaseScreen.getScreenWidth() - this.T) * (BaseScreen.getScreenWidth() - this.T) + (BaseScreen.getScreenHeight() - this.U) * (BaseScreen.getScreenHeight() - this.U) < this.R * this.R) {
                        this.i = 0;
                        this.b = true;
                    }
                    this.R += 10;
                    break;
                }
                if (this.S == 1) {
                    this.R -= 10;
                    if (this.R > 0) break;
                    this.i = 0;
                    this.a = -1;
                    this.b = true;
                    break;
                }
                if (this.i <= 10) {
                    this.R += 10;
                    break;
                }
                if (this.i > 10 && this.i <= 20) {
                    this.R -= 10;
                    break;
                }
                this.i = 0;
                this.b = true;
                this.a = -1;
            }
        }
        switch (this.g) {
            case 13: {
                this.j += this.H;
                if (this.j <= this.G) break;
                this.j = this.G;
                this.c = true;
                return;
            }
            case 12: {
                this.j += this.H;
                if (this.j <= this.G) break;
                this.j = 0;
                this.c = true;
                this.g = -1;
            }
        }
    }

    private boolean d(Graphics graphics) {
        int n;
        int n2;
        int n3;
        int n4;
        int n5;
        int n6 = this.n & 0xFFFFFF;
        int n7 = 0;
        int n8 = this.s;
        int n9 = 255 / ((n8 << 1) + 1);
        int n10 = this.r / 2;
        int n11 = n10 * 200 / 120;
        int n12 = n11 * n11;
        int n13 = this.t / this.r + 1;
        int n14 = BaseScreen.getScreenWidth() / this.r;
        int n15 = BaseScreen.getScreenHeight() / this.r;
        int n16 = n14 / 2;
        int n17 = n15 / 2;
        int[] nArray = new int[n11];
        if (this.u == null) {
            this.u = new int[EngineUtils.a(n16 * n16 + n17 * n17, 0)][];
        }
        if (this.v == null) {
            this.v = new int[this.u.length];
        }
        if (n13 > this.u.length) {
            n13 = this.u.length;
        }
        for (n5 = 0; n5 < n13; ++n5) {
            if (this.u[n5] == null) {
                this.u[n5] = new int[this.r * this.r];
            }
            if (this.v[n5] >= n11 + n8) continue;
            n4 = -n8 + this.v[n5];
            for (n3 = 0; n3 < nArray.length; ++n3) {
                n2 = n3 - n4;
                if (n2 > n8) {
                    n7 = this.a == 4 ? 0 : 255;
                } else if (n2 < -n8) {
                    n7 = this.a == 4 ? 255 : 0;
                } else if (this.a == 4) {
                    n7 = 127 - n2 * n9;
                } else if (this.a == 5) {
                    n7 = 127 + n2 * n9;
                }
                nArray[n3] = n6 | n7 << 24;
            }
            n3 = n11 - 1;
            n2 = n4 + n8;
            if ((n4 -= n8) < 0) {
                n4 = 0;
            }
            int n18 = n2 * n12 / n3;
            n = n4 * n12 / n3;
            for (n4 = 0; n4 < this.r; ++n4) {
                n2 = (n4 - n10) * (n4 - n10);
                int n19 = n4 * this.r;
                for (int i = 0; i < this.r; ++i) {
                    n3 = n2 + (i - n10) * (i - n10);
                    int n20 = EngineUtils.a(n3, 1);
                    this.u[n5][n19 + i] = n3 > n18 ? (this.a == 4 ? 0 : -16777216) : (n3 < n ? (this.a == 4 ? -16777216 : 0) : nArray[n20]);
                }
            }
            int n21 = n5;
            this.v[n21] = this.v[n21] + 1;
        }
        n5 = 1;
        graphics.setColor(n6);
        for (n3 = 0; n3 < n15; ++n3) {
            n2 = (n3 - n17) * (n3 - n17);
            for (n = 0; n < n14; ++n) {
                n4 = EngineUtils.a(n2 + (n - n16) * (n - n16), 1);
                if (this.u[n4] == null) {
                    if (this.a != 5) continue;
                    graphics.fillRect(n * this.r, n3 * this.r, this.r, this.r);
                    continue;
                }
                if (this.v[n4] >= n11 + n8) {
                    if (this.a != 4) continue;
                    graphics.fillRect(n * this.r, n3 * this.r, this.r, this.r);
                    continue;
                }
                n5 = 0;
                graphics.drawRGB(this.u[n4], 0, this.r, n * this.r, n3 * this.r, this.r, this.r, true);
            }
        }
        if (n5 != 0) {
            this.d();
            return true;
        }
        this.t += 15;
        return false;
    }

    private static int[] a(int[] nArray, int[] nArray2, int n, int n2, byte by) {
        block11: {
            block14: {
                block13: {
                    block12: {
                        block10: {
                            if (by != 5) break block10;
                            for (by = 0; by < n2; by = (byte)(by + 1)) {
                                int n3 = by * n;
                                int n4 = -1 - by;
                                int n5 = 0;
                                int n6 = 1;
                                while (n5 < n) {
                                    nArray2[n6 * n2 + n4] = nArray[n3 + n5];
                                    ++n5;
                                    ++n6;
                                }
                            }
                            break block11;
                        }
                        if (by != 3) break block12;
                        by = (byte)(n * n2 - 1);
                        for (int i = 0; i < n2; ++i) {
                            int n7 = i * n;
                            int n8 = by - i * n;
                            for (int j = 0; j < n; ++j) {
                                nArray2[n8 - j] = nArray[n7 + j];
                            }
                        }
                        break block11;
                    }
                    if (by != 6) break block13;
                    by = (byte)(n - 1);
                    for (int i = 0; i < n2; ++i) {
                        int n9 = by * n2 + i;
                        int n10 = i * n;
                        for (int j = 0; j < n; ++j) {
                            nArray2[n9 - j * n2] = nArray[n10 + j];
                        }
                    }
                    break block11;
                }
                if (by == 0 || by == 7) break block11;
                if (by != 1) break block14;
                by = (byte)(n2 - 1);
                for (int i = 0; i < n2; ++i) {
                    int n11 = i * n;
                    int n12 = (by - i) * n;
                    for (int j = 0; j < n; ++j) {
                        nArray2[n12 + j] = nArray[n11 + j];
                    }
                }
                break block11;
            }
            if (by == 4 || by != 2) break block11;
            by = (byte)(n - 1);
            for (int i = 0; i < n2; ++i) {
                int n13 = i * n;
                int n14 = n13 + by;
                for (int j = 0; j < n; ++j) {
                    nArray2[n14 - j] = nArray[n13 + j];
                }
            }
        }
        return nArray2;
    }

    public final void c() {
        this.d = (byte)-1;
        this.O = null;
    }

    public final void a(int n, int n2, int n3, int n4, int n5, int n6) {
        this.d = 0;
        this.b(n, n2);
        this.ad = n3;
        this.ae = n4;
        this.af = n5;
        this.ag = n6;
    }

    public final void a(int n, int n2) {
        this.af = n;
        this.ag = n2;
    }

    public final void b(int n, int n2) {
        this.ab = n;
        this.ac = n2;
    }

    public final void b(Graphics graphics) {
        graphics.setColor(0);
        graphics.fillRect(0, 0, this.ad, this.ac - this.ag);
        graphics.fillRect(0, this.ac - this.ag, this.ab - this.af, this.ag << 1);
        graphics.fillRect(0, this.ac + this.ag, this.ad, this.ae - (this.ac + this.ag));
        graphics.fillRect(this.ab + this.af, this.ac - this.ag, this.ad - (this.ab + this.af), this.ag << 1);
    }

    public final void c(int n, int n2) {
        this.k = 0;
        this.n = n;
        if (n2 == 12 || n2 == 13) {
            this.g = n2;
            this.c = false;
        } else if (n2 == 18) {
            this.h = n2;
        } else {
            this.a = n2;
        }
        this.b = false;
        switch (this.a) {
            case 1:
            case 2: {
                this.m = 17;
                return;
            }
            case 3: {
                this.k = BaseScreen.getHalfWidth();
                this.l = 20;
                return;
            }
            case 4:
            case 5: {
                this.t = 0;
                return;
            }
            case 6: {
                this.i = 0;
                this.x = EngineUtils.randomInt(2);
                return;
            }
            case 7: {
                this.a(0);
                return;
            }
            case 8: {
                this.i = 0;
                z.at();
                this.a(0);
                return;
            }
            case 10:
            case 17: {
                this.i = 0;
                return;
            }
            case 19: {
                this.c(-1);
                return;
            }
            case 20: {
                this.c(1);
            }
        }
    }

    public final void a(int n, int n2, int n3) {
        ParticleEffect.a().d((byte)3);
        this.C = n;
        this.D = n2;
        this.E = n3;
    }

    public final void a(int n, int n2, int n3, int n4, int n5) {
        this.j = 0;
        this.G = n;
        this.H = n2;
        this.I = n3;
        this.J = n4;
        this.K = n5;
    }

    public final void d(int n, int n2) {
        this.L = n;
        this.M = n2;
    }

    public final void a(int n, int n2, int n3, int n4) {
        this.S = n;
        this.T = n2;
        this.U = n3;
        this.R = n4;
    }

    public final void a(String string, int n, int n2, int n3) {
        this.N = EngineUtils.loadImage("/data/tex/", string);
        this.O = new PixelBuffer();
        this.O = ImageTransformer.a(this.N, this.O);
        this.P = n;
        this.Q = n2;
        this.m = n3;
    }

    private void d() {
        this.o = null;
        this.p = null;
        this.q = null;
        this.u = null;
        this.v = null;
        this.N = null;
    }

    public final void a(int n, byte by, byte by2, String[] stringArray) {
        this.f = n;
        if (this.a == 17 && this.S == 0) {
            return;
        }
        this.a = -1;
        if (this.f < 16) {
            return;
        }
        this.ai = by;
        this.al = n;
        this.am = 0;
        this.an = by2;
        this.aj = null;
        this.aj = new Image[stringArray.length];
        for (n = 0; n < stringArray.length; ++n) {
            this.aj[n] = EngineUtils.loadImage("/data/tex/", stringArray[n]);
        }
        this.ak = new int[by][5];
        for (n = 0; n < by; ++n) {
            this.b(n);
        }
    }

    private void b(int n) {
        int n2 = EngineUtils.randomInt(100);
        this.ak[n][0] = n2 < 3 ? this.aj.length - 1 : (n2 < 15 ? this.aj.length - 2 : (n2 < 50 ? this.aj.length - 3 : 0));
        this.ak[n][1] = EngineUtils.randomInt(BaseScreen.getScreenWidth());
        this.ak[n][2] = EngineUtils.randomInt(BaseScreen.getScreenHeight());
        this.ak[n][3] = EngineUtils.randomInt(ah[this.ak[n][0]][1] - ah[this.ak[n][0]][0]) + ah[this.ak[n][0]][0];
        this.ak[n][4] = EngineUtils.a();
    }

    public final void c(Graphics graphics) {
        if (this.f < 16) {
            return;
        }
        for (int i = 0; i < this.ai; ++i) {
            if (this.ak[i][1] < BaseScreen.getScreenWidth() && this.ak[i][2] < BaseScreen.getScreenHeight()) {
                graphics.drawImage(this.aj[this.ak[i][0]], this.ak[i][1], this.ak[i][2], 20);
            }
            switch (this.an) {
                case 0: {
                    int[] nArray = this.ak[i];
                    nArray[2] = nArray[2] - this.ak[i][3];
                    break;
                }
                case 1: {
                    int[] nArray = this.ak[i];
                    nArray[1] = nArray[1] + this.ak[i][3];
                    int[] nArray2 = this.ak[i];
                    nArray2[2] = nArray2[2] - this.ak[i][3];
                    break;
                }
                case 2: {
                    int[] nArray = this.ak[i];
                    nArray[1] = nArray[1] + this.ak[i][3];
                    break;
                }
                case 3: {
                    int[] nArray = this.ak[i];
                    nArray[1] = nArray[1] + this.ak[i][3];
                    int[] nArray3 = this.ak[i];
                    nArray3[2] = nArray3[2] + this.ak[i][3];
                    break;
                }
                case 4: {
                    int[] nArray = this.ak[i];
                    nArray[2] = nArray[2] + this.ak[i][3];
                    break;
                }
                case 5: {
                    int[] nArray = this.ak[i];
                    nArray[1] = nArray[1] - this.ak[i][3];
                    int[] nArray4 = this.ak[i];
                    nArray4[2] = nArray4[2] + this.ak[i][3];
                    break;
                }
                case 6: {
                    int[] nArray = this.ak[i];
                    nArray[1] = nArray[1] - this.ak[i][3];
                    break;
                }
                case 7: {
                    int[] nArray = this.ak[i];
                    nArray[1] = nArray[1] - this.ak[i][3];
                    int[] nArray5 = this.ak[i];
                    nArray5[2] = nArray5[2] - this.ak[i][3];
                }
            }
            if (this.ak[i][1] >= this.al - this.aj[this.ak[i][0]].getWidth() && this.ak[i][2] >= 0 - this.aj[this.ak[i][0]].getHeight()) continue;
            this.b(i);
        }
    }

    private void c(int n) {
        ScreenView.X[0] = 20;
        W = BaseScreen.getScreenWidth() / X[0];
        ScreenView.X[1] = (BaseScreen.getScreenHeight() - 1) / X[0] + 1;
        ScreenView.X[2] = n;
        ScreenView.X[3] = EngineUtils.randomRange(0, 7);
        ScreenView.X[4] = 0;
        this.b = false;
    }

    static {
        A = new short[][]{{0}, {1}, {2}, {3}, {4, 5, 6, 7, 8}, {9}, {10}, {11, 12}, {13}, {14, 15, 16, 17, 18, 19, 20}, {21}, {22}};
        W = 0;
        X = new int[5];
        byte[] byArray = new byte[]{0, 5, 3, 6, 2, 7, 1, 4};
        ah = new int[][]{{1, 3}, {1, 4}, {2, 5}, {2, 6}};
    }
}

