/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import java.io.DataInputStream;

public final class ScriptCommand {
    private short opcode;
    private short[] numericArguments;
    private String[] textArguments;

    public final void read(DataInputStream input, String[] stringPool) {
        int n;
        this.opcode = input.readShort();
        byte by = input.readByte();
        int n2 = input.readByte();
        this.numericArguments = new short[n2];
        for (n = 0; n < n2; ++n) {
            this.numericArguments[n] = input.readShort();
        }
        if (stringPool != null) {
            this.textArguments = new String[by - n2];
            for (n = 0; n < by - n2; ++n) {
                short s = input.readShort();
                this.textArguments[n] = stringPool[s];
            }
        }
    }

    public final short getOpcode() {
        return this.opcode;
    }

    public final short[] getNumericArguments() {
        return this.numericArguments;
    }

    public final String[] getTextArguments() {
        return this.textArguments;
    }
}

