/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

public final class SpriteRenderer {
    private static int[] c = new int[]{0, 5, 3, 6, 2, 4, 1, 7};
    private static int[] d = new int[]{2, 4, 1, 7, 0, 5, 3, 6};
    private static int[] e = new int[]{3, 6, 0, 5, 1, 7, 2, 4};
    private static int[] f = new int[]{1, 7, 2, 4, 3, 6, 0, 5};
    private static int[] g = new int[]{0, 270, 180, 90, 8192, 8462, 8372, 8282};
    private static int[] h = new int[]{8192, 8462, 8372, 8282, 0, 270, 180, 90};
    private static int[] i = new int[]{180, 90, 0, 270, 8372, 8282, 8192, 8462};
    private static int[] j = new int[]{8372, 8282, 8192, 8462, 180, 90, 0, 270};
    private Image[] imageSheets;
    private SpriteData spriteData;
    private int[] imageIds;
    public int spriteId;
    private int remainingFrameTicks;
    private int remainingExtraTicks;
    private byte nextAnimationId;
    private int animationStepIndex;
    private int animationStepCount;
    protected byte animationId;
    private boolean s = true;

    public final boolean loadSprite(int spriteId, boolean hasExtendedAnimationSteps) {
        this.imageIds = new int[GameDatabase.spriteTable[spriteId].length - 1];
        this.imageSheets = new Image[GameDatabase.spriteTable[spriteId].length - 1];
        for (int i = 0; i < this.imageSheets.length; ++i) {
            this.imageIds[i] = GameDatabase.spriteTable[spriteId][i + 1];
            this.imageSheets[i] = ImageCache.getImage(this.imageIds[i]);
        }
        this.spriteId = spriteId;
        this.spriteData = AnimationCache.getAnimationData(GameDatabase.spriteTable[spriteId][0]);
        this.spriteData.hasExtendedAnimationSteps = hasExtendedAnimationSteps;
        this.selectAnimationStep(0);
        return true;
    }

    public final void releaseSprite() {
        if (this.imageIds != null) {
            for (int i = 0; i < this.imageIds.length; ++i) {
                if (this.imageSheets != null) {
                    this.imageSheets[i] = null;
                }
                ImageCache.releaseImage(this.imageIds[i]);
            }
        }
        this.imageIds = null;
        if (this.spriteId != 257) {
            this.spriteData = null;
            AnimationCache.releaseAnimationData(this.spriteId);
        }
    }

    public final void evictSprite() {
        if (this.imageIds == null) {
            return;
        }
        for (int i = 0; i < this.imageIds.length; ++i) {
            if (this.imageSheets != null) {
                this.imageSheets[i] = null;
            }
            ImageCache.evictImage(this.imageIds[i]);
        }
        this.imageIds = null;
        this.spriteData = null;
        AnimationCache.evictAnimationData(this.spriteId);
    }

    public final void replaceImage(int sheetIndex, int imageId, boolean unusedFlag) {
        this.imageSheets[sheetIndex] = null;
        ImageCache.evictImage(this.imageIds[sheetIndex]);
        this.imageIds[sheetIndex] = imageId;
        this.imageSheets[sheetIndex] = ImageCache.getImage(this.imageIds[sheetIndex]);
    }

    public static void c() {
    }

    public final void a(int n) {
        for (int i = 0; i < this.imageSheets.length; ++i) {
            if (n == 1) {
                this.imageSheets[i] = ImageTransformer.a(ImageCache.getImage(this.imageIds[i]));
                continue;
            }
            this.evictSprite();
        }
        if (n == 0) {
            this.loadSprite(this.spriteId, false);
        }
    }

    public final boolean setAnimation(byte animationId, byte nextAnimationId, boolean resetStep) {
        if (this.animationId != animationId || resetStep) {
            this.animationId = animationId;
            this.selectAnimationStep(0);
        } else {
            this.animationId = animationId;
        }
        this.nextAnimationId = nextAnimationId;
        return true;
    }

    public final void setAnimationWithoutReset(byte animationId, byte unusedNextAnimationId) {
        this.animationId = animationId;
        this.nextAnimationId = (byte)-1;
    }

    private void selectAnimationStep(int stepIndex) {
        this.animationStepIndex = stepIndex;
        if (this.spriteData.animations == null) {
            return;
        }
        if (this.spriteData.hasExtendedAnimationSteps) {
            this.remainingFrameTicks = this.spriteData.animations[this.animationId][this.animationStepIndex << 2];
            this.animationStepCount = this.spriteData.animations[this.animationId].length / 4;
        } else {
            this.remainingFrameTicks = this.spriteData.animations[this.animationId][this.animationStepIndex << 1];
            this.animationStepCount = this.spriteData.animations[this.animationId].length / 2;
        }
        this.remainingExtraTicks = 0;
        if (this.remainingFrameTicks > 0) {
            --this.remainingFrameTicks;
            return;
        }
        if (this.remainingExtraTicks > 0) {
            --this.remainingExtraTicks;
        }
    }

    public final boolean advanceAnimation() {
        if (this.remainingFrameTicks > 0) {
            --this.remainingFrameTicks;
        } else if (this.remainingExtraTicks > 0) {
            --this.remainingExtraTicks;
        } else {
            ++this.animationStepIndex;
            if (this.animationStepIndex >= this.animationStepCount) {
                if (this.nextAnimationId >= 0) {
                    this.setAnimation(this.nextAnimationId, (byte)-1, true);
                } else if (this.nextAnimationId == -2) {
                    --this.animationStepIndex;
                    this.selectAnimationStep(this.animationStepIndex);
                } else if (this.nextAnimationId == -1) {
                    this.selectAnimationStep(0);
                }
                return true;
            }
            this.selectAnimationStep(this.animationStepIndex);
        }
        return false;
    }

    public final boolean isLastAnimationStep() {
        return this.animationStepIndex >= this.animationStepCount - 1;
    }

    public final boolean isFrameTimerExpired() {
        return this.remainingFrameTicks == 0;
    }

    public final boolean isAnimationStep(int stepIndex) {
        return this.animationStepIndex == stepIndex;
    }

    public final byte getAnimationId() {
        return this.animationId;
    }

    public final int getAnimationStepIndex() {
        return this.animationStepIndex;
    }

    public final int[] getAnimationBounds(int animationId, byte transform) {
        if (animationId >= 0 && animationId < this.spriteData.animations.length) {
            int[] nArray = this.getFrameBounds(this.spriteData.animations[animationId][1], (byte)0);
            int n = nArray[0];
            int n2 = nArray[0] + nArray[2];
            int n3 = nArray[1];
            int n4 = nArray[1] + nArray[3];
            if (this.spriteData.hasExtendedAnimationSteps) {
                for (int i = 1; i != this.spriteData.animations[animationId].length / 4; ++i) {
                    nArray = this.getFrameBounds(this.spriteData.animations[animationId][(i << 2) + 1], (byte)0);
                    if (nArray == null) continue;
                    if (n > nArray[0]) {
                        n = nArray[0];
                    }
                    if (n2 < nArray[0] + nArray[2]) {
                        n2 = nArray[0] + nArray[2];
                    }
                    if (n3 > nArray[1]) {
                        n3 = nArray[1];
                    }
                    if (n4 >= nArray[1] + nArray[3]) continue;
                    n4 = nArray[1] + nArray[3];
                }
            } else {
                for (int i = 1; i != this.spriteData.animations[animationId].length / 2; ++i) {
                    nArray = this.getFrameBounds(this.spriteData.animations[animationId][(i << 1) + 1], (byte)0);
                    if (nArray == null) continue;
                    if (n > nArray[0]) {
                        n = nArray[0];
                    }
                    if (n2 < nArray[0] + nArray[2]) {
                        n2 = nArray[0] + nArray[2];
                    }
                    if (n3 > nArray[1]) {
                        n3 = nArray[1];
                    }
                    if (n4 >= nArray[1] + nArray[3]) continue;
                    n4 = nArray[1] + nArray[3];
                }
            }
            return new int[]{n, n3, n2 - n, n4 - n3};
        }
        return null;
    }

    public final int[] getFrameBounds(int frameIndex, byte transform) {
        int n;
        if (this.spriteData.frames[frameIndex].length <= 0) {
            return null;
        }
        short s = this.spriteData.frames[frameIndex][0];
        int n2 = this.spriteData.frames[frameIndex][1];
        int n3 = this.spriteData.frames[frameIndex][2];
        for (int i = 0; i < this.spriteData.frames[frameIndex].length; i += 4) {
            s = this.spriteData.frames[frameIndex][i];
            if (this.spriteData.frames[frameIndex][i + 1] < n2) {
                n2 = this.spriteData.frames[frameIndex][i + 1];
            }
            if (this.spriteData.frames[frameIndex][i + 2] >= n3) continue;
            n3 = this.spriteData.frames[frameIndex][i + 2];
        }
        int[] nArray = new int[2];
        nArray = this.a(0, (int)s, frameIndex, n2, n3, nArray);
        int n4 = nArray[0];
        int n5 = nArray[1];
        for (n = 0; n < this.spriteData.frames[frameIndex].length; n += 4) {
            s = this.spriteData.frames[frameIndex][n];
            if ((nArray = this.a(n, (int)s, frameIndex, n2, n3, nArray))[0] > n4) {
                n4 = nArray[0];
            }
            if (nArray[1] <= n5) continue;
            n5 = nArray[1];
        }
        switch (transform) {
            case 4: {
                s = this.spriteData.frames[frameIndex][0];
                n3 = this.spriteData.frames[frameIndex][3] % 2 == 1 ? -this.spriteData.frames[frameIndex][2] - this.spriteData.modules[s * 5 + 3] : -this.spriteData.frames[frameIndex][2] - this.spriteData.modules[s * 5 + 4];
                for (n = 0; n < this.spriteData.frames[frameIndex].length; n += 4) {
                    s = this.spriteData.frames[frameIndex][n];
                    if (this.spriteData.frames[frameIndex][n + 3] % 2 == 1) {
                        if (-this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 3] >= n3) continue;
                        n3 = -this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 3];
                        continue;
                    }
                    if (-this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 4] >= n3) continue;
                    n3 = -this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 4];
                }
                break;
            }
            case 1: {
                s = this.spriteData.frames[frameIndex][0];
                n2 = this.spriteData.frames[frameIndex][3] % 2 == 1 ? -this.spriteData.frames[frameIndex][1] - this.spriteData.modules[s * 5 + 4] : -this.spriteData.frames[frameIndex][1] - this.spriteData.modules[s * 5 + 3];
                for (n = 0; n < this.spriteData.frames[frameIndex].length; n += 4) {
                    s = this.spriteData.frames[frameIndex][n];
                    if (this.spriteData.frames[frameIndex][n + 3] % 2 == 1) {
                        if (-this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 4] >= n2) continue;
                        n2 = -this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 4];
                        continue;
                    }
                    if (-this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 3] >= n2) continue;
                    n2 = -this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 3];
                }
                break;
            }
            case 3: {
                s = this.spriteData.frames[frameIndex][0];
                if (this.spriteData.frames[frameIndex][3] % 2 == 1) {
                    n2 = -this.spriteData.frames[frameIndex][1] - this.spriteData.modules[s * 5 + 4];
                    n3 = -this.spriteData.frames[frameIndex][2] - this.spriteData.modules[s * 5 + 3];
                } else {
                    n2 = -this.spriteData.frames[frameIndex][1] - this.spriteData.modules[s * 5 + 3];
                    n3 = -this.spriteData.frames[frameIndex][2] - this.spriteData.modules[s * 5 + 4];
                }
                for (n = 0; n < this.spriteData.frames[frameIndex].length; n += 4) {
                    s = this.spriteData.frames[frameIndex][n];
                    if (this.spriteData.frames[frameIndex][n + 3] % 2 == 1) {
                        if (-this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 4] < n2) {
                            n2 = -this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 4];
                        }
                        if (-this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 3] >= n3) continue;
                        n3 = -this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 3];
                        continue;
                    }
                    if (-this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 3] < n2) {
                        n2 = -this.spriteData.frames[frameIndex][n + 1] - this.spriteData.modules[s * 5 + 3];
                    }
                    if (-this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 4] >= n3) continue;
                    n3 = -this.spriteData.frames[frameIndex][n + 2] - this.spriteData.modules[s * 5 + 4];
                }
                break;
            }
        }
        return new int[]{n2, n3, n4, n5};
    }

    private int[] a(int n, int n2, int n3, int n4, int n5, int[] nArray) {
        if (this.spriteData.frames[n3][n + 3] % 2 == 1) {
            nArray[1] = this.spriteData.frames[n3][n + 2] - n5 + this.spriteData.modules[n2 * 5 + 3];
            nArray[0] = this.spriteData.frames[n3][n + 1] - n4 + this.spriteData.modules[n2 * 5 + 4];
        } else {
            nArray[0] = this.spriteData.frames[n3][n + 1] - n4 + this.spriteData.modules[n2 * 5 + 3];
            nArray[1] = this.spriteData.frames[n3][n + 2] - n5 + this.spriteData.modules[n2 * 5 + 4];
        }
        return nArray;
    }

    public final void drawCurrentFrame(Graphics graphics, int x, int y, byte transform) {
        if (this.spriteData.hasExtendedAnimationSteps) {
            this.drawFrame(graphics, this.spriteData.animations[this.animationId][(this.animationStepIndex << 2) + 1], x, y, transform);
            return;
        }
        this.drawFrame(graphics, this.spriteData.animations[this.animationId][(this.animationStepIndex << 1) + 1], x, y, transform);
    }

    public final void drawFrame(Graphics graphics, int frameIndex, int x, int y, byte transform) {
        if (this.spriteData.frames[frameIndex].length <= 0) {
            return;
        }
        switch (transform) {
            case 0: {
                for (transform = 0; transform < this.spriteData.frames[frameIndex].length; transform = (byte)(transform + 4)) {
                    this.a(graphics, (int)this.spriteData.frames[frameIndex][transform], x + this.spriteData.frames[frameIndex][transform + 1], y + this.spriteData.frames[frameIndex][transform + 2], this.s ? c[this.spriteData.frames[frameIndex][transform + 3]] : g[this.spriteData.frames[frameIndex][transform + 3]], 20);
                }
                return;
            }
            case 1: {
                for (transform = 0; transform < this.spriteData.frames[frameIndex].length; transform = (byte)(transform + 4)) {
                    if (this.spriteData.frames[frameIndex][transform + 3] % 2 == 1) {
                        this.a(graphics, (int)this.spriteData.frames[frameIndex][transform], x - this.spriteData.frames[frameIndex][transform + 1] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 4], y + this.spriteData.frames[frameIndex][transform + 2], this.s ? d[this.spriteData.frames[frameIndex][transform + 3]] : h[this.spriteData.frames[frameIndex][transform + 3]], 20);
                        continue;
                    }
                    this.a(graphics, (int)this.spriteData.frames[frameIndex][transform], x - this.spriteData.frames[frameIndex][transform + 1] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 3], y + this.spriteData.frames[frameIndex][transform + 2], this.s ? d[this.spriteData.frames[frameIndex][transform + 3]] : h[this.spriteData.frames[frameIndex][transform + 3]], 20);
                }
                return;
            }
            case 3: {
                for (transform = 0; transform < this.spriteData.frames[frameIndex].length; transform = (byte)(transform + 4)) {
                    if (this.spriteData.frames[frameIndex][transform + 3] % 2 == 1) {
                        this.a(graphics, (int)this.spriteData.frames[frameIndex][transform], x - this.spriteData.frames[frameIndex][transform + 1] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 4], y - this.spriteData.frames[frameIndex][transform + 2] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 3], this.s ? e[this.spriteData.frames[frameIndex][transform + 3]] : i[this.spriteData.frames[frameIndex][transform + 3]], 20);
                        continue;
                    }
                    this.a(graphics, (int)this.spriteData.frames[frameIndex][transform], x - this.spriteData.frames[frameIndex][transform + 1] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 3], y - this.spriteData.frames[frameIndex][transform + 2] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 4], this.s ? e[this.spriteData.frames[frameIndex][transform + 3]] : i[this.spriteData.frames[frameIndex][transform + 3]], 20);
                }
                return;
            }
            case 4: {
                for (transform = 0; transform < this.spriteData.frames[frameIndex].length; transform = (byte)(transform + 4)) {
                    if (this.spriteData.frames[frameIndex][transform + 3] % 2 == 1) {
                        this.a(graphics, (int)this.spriteData.frames[frameIndex][transform], x + this.spriteData.frames[frameIndex][transform + 1], y - this.spriteData.frames[frameIndex][transform + 2] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 3], this.s ? f[this.spriteData.frames[frameIndex][transform + 3]] : j[this.spriteData.frames[frameIndex][transform + 3]], 20);
                        continue;
                    }
                    this.a(graphics, (int)this.spriteData.frames[frameIndex][transform], x + this.spriteData.frames[frameIndex][transform + 1], y - this.spriteData.frames[frameIndex][transform + 2] - this.spriteData.modules[this.spriteData.frames[frameIndex][transform] * 5 + 4], this.s ? f[this.spriteData.frames[frameIndex][transform + 3]] : j[this.spriteData.frames[frameIndex][transform + 3]], 20);
                }
                break;
            }
        }
    }

    private void a(Graphics graphics, int n, int n2, int n3, int n4, int n5) {
        graphics.drawRegion(this.imageSheets[this.spriteData.modules[n * 5]], this.spriteData.modules[n * 5 + 1], this.spriteData.modules[n * 5 + 2], this.spriteData.modules[n * 5 + 3], this.spriteData.modules[n * 5 + 4], n4, n2, n3, 20);
    }

    public final boolean i() {
        return this.spriteData.attackRegions == null;
    }

    public final short[] j() {
        if (this.spriteData.attackRegions == null) {
            return null;
        }
        if (this.spriteData.hasExtendedAnimationSteps) {
            return this.spriteData.attackRegions[this.spriteData.animations[this.animationId][(this.animationStepIndex << 2) + 1]];
        }
        return this.spriteData.attackRegions[this.spriteData.animations[this.animationId][(this.animationStepIndex << 1) + 1]];
    }

    public final short[] k() {
        if (this.spriteData.collisionRegions == null) {
            return null;
        }
        if (this.spriteData.hasExtendedAnimationSteps) {
            return this.spriteData.collisionRegions[this.spriteData.animations[this.animationId][(this.animationStepIndex << 2) + 1]];
        }
        return this.spriteData.collisionRegions[this.spriteData.animations[this.animationId][(this.animationStepIndex << 1) + 1]];
    }
}

