/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
public final class SpriteData {
    public int referenceCount;
    public short[] modules;
    public short[][] attackRegions;
    public short[][] collisionRegions;
    public short[][] frames;
    public short[][] animations;
    public boolean hasExtendedAnimationSteps;
}

