/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import javax.microedition.lcdui.Graphics;

public interface UIComponent {
    public void setVisible(boolean var1);

    public void render(Graphics var1, boolean var2, boolean var3, UIComponent var4, int[] var5);

    public void a(boolean var1, boolean var2, UIComponent var3, int[] var4);

    public int getId();

    public int getX();

    public void setX(int var1, UIComponent var2);

    public int getY();

    public void setY(int var1, UIComponent var2);

    public int getWidth();

    public void setWidth(int var1, UIComponent var2);

    public int getHeight();

    public void setHeight(int var1, UIComponent var2);

    public UISelectionConfig getSelection();

    public UIComponent[] getChildren();

    public UIStyle getStyle();

    public void setStyle(UIStyle var1);

    public int getType();

    public int getParentId();

    public void updateLayout(UIComponent var1);

    public void release();
}

