/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.OutputStream;
import javax.microedition.lcdui.Graphics;
import javax.microedition.rms.RecordStore;
import javax.microedition.rms.RecordStoreException;
import javax.microedition.rms.RecordStoreNotOpenException;

public final class UILayoutView {
    private UIComponent[] components;
    private int componentCount;
    private MenuWidget root;
    private int[] d;
    private int[] e;
    private int[] f;
    private TextPainter textPainter;
    private ScriptEventListener eventListener;

    public UILayoutView(ScriptEventListener scriptEventListener) {
        this.components = new UIComponent[200];
        this.componentCount = 0;
        this.d = new int[]{0, 1, 2, 3, 5, 6, 7, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
        this.e = null;
        this.f = null;
        this.eventListener = scriptEventListener;
        this.resetLayout();
    }

    private void resetLayout() {
        this.root = new MenuWidget();
        this.root.a(0);
        this.root.c(-1);
        this.e = EngineUtils.b(100);
        this.f();
    }

    public final MenuWidget getRoot() {
        return this.root;
    }

    public final void setTextPainter(TextPainter textPainter) {
        this.textPainter = textPainter;
    }

    public final void loadLayout(String path, int spriteId) {
        this.resetLayout();
        byte[] byArray = new byte[20000];
        EngineUtils.b(byArray, path);
        Object object = new int[]{0};
        EngineUtils.readShort(byArray, (int[])object);
        EngineUtils.readShort(byArray, (int[])object);
        short s = EngineUtils.readByte(byArray, (int[])object);
        this.root.b(s);
        s = EngineUtils.readShort(byArray, (int[])object);
        this.root.a(s);
        s = EngineUtils.readShort(byArray, (int[])object);
        this.root.setX(s, this.root);
        s = EngineUtils.readShort(byArray, (int[])object);
        this.root.setY(s, this.root);
        s = EngineUtils.readShort(byArray, (int[])object);
        this.root.setWidth(s, this.root);
        s = EngineUtils.readShort(byArray, (int[])object);
        this.root.setHeight(s, this.root);
        this.components[this.componentCount] = this.root;
        this.componentCount = 1;
        this.a(byArray, (int[])object, this.root, spriteId, false);
        object = this;
        this.e = EngineUtils.b(50);
        super.a(((UILayoutView)object).root, -1);
    }

    private void a(byte[] byArray, int[] nArray, MenuWidget menuWidget, int n, boolean bl) {
        int n2;
        int n3;
        int n4 = EngineUtils.readByte(byArray, nArray);
        if (n4 > 0) {
            byte[][] byArray2 = new byte[n4][4];
            for (n3 = 0; n3 < n4; ++n3) {
                byArray2[n3][0] = EngineUtils.readByte(byArray, nArray);
                byArray2[n3][1] = EngineUtils.readByte(byArray, nArray);
                byArray2[n3][2] = EngineUtils.readByte(byArray, nArray);
                byArray2[n3][3] = EngineUtils.readByte(byArray, nArray);
            }
            menuWidget.a(byArray2);
        }
        int n5 = EngineUtils.readByte(byArray, nArray);
        for (n3 = 0; n3 < n5; ++n3) {
            int n6;
            int n7;
            int n8;
            n4 = EngineUtils.readByte(byArray, nArray);
            UISelectionConfig uISelectionConfig = new UISelectionConfig(n4);
            new UISelectionConfig(n4).wrapSelection = EngineUtils.readByte(byArray, nArray) != 0;
            uISelectionConfig.visibleItemCount = EngineUtils.readShort(byArray, nArray);
            uISelectionConfig.itemCount = EngineUtils.readShort(byArray, nArray);
            uISelectionConfig.h = EngineUtils.readByte(byArray, nArray);
            uISelectionConfig.i = EngineUtils.readByte(byArray, nArray);
            for (n8 = 0; n8 < uISelectionConfig.itemCount; ++n8) {
                n7 = EngineUtils.readShort(byArray, nArray);
                uISelectionConfig.itemIds[n8] = n7;
                n6 = EngineUtils.readShort(byArray, nArray);
                byte[] byArray3 = new byte[n6];
                for (int i = 0; i < n6; ++i) {
                    byArray3[i] = EngineUtils.readByte(byArray, nArray);
                }
                uISelectionConfig.j.addElement(EngineUtils.decodeUtf16(byArray3));
            }
            uISelectionConfig.c = new int[uISelectionConfig.visibleItemCount + this.d.length][][];
            for (n8 = 0; n8 < uISelectionConfig.c.length; ++n8) {
                uISelectionConfig.c[n8] = new int[0][];
            }
            n8 = EngineUtils.readShort(byArray, nArray);
            for (n7 = 0; n7 < n8; ++n7) {
                n6 = EngineUtils.readShort(byArray, nArray);
                int n9 = EngineUtils.readShort(byArray, nArray);
                int[][] nArrayArray = new int[n9][];
                for (n2 = 0; n2 < n9; ++n2) {
                    nArrayArray[n2] = new int[5];
                    nArrayArray[n2][0] = EngineUtils.readShort(byArray, nArray);
                    nArrayArray[n2][1] = EngineUtils.readShort(byArray, nArray);
                    nArrayArray[n2][2] = EngineUtils.readShort(byArray, nArray);
                    nArrayArray[n2][3] = EngineUtils.readShort(byArray, nArray);
                    nArrayArray[n2][4] = EngineUtils.readShort(byArray, nArray);
                }
                uISelectionConfig.c[n6] = nArrayArray;
            }
            if (n4 == 0) {
                menuWidget.a = uISelectionConfig;
                continue;
            }
            menuWidget.b = uISelectionConfig;
        }
        n3 = EngineUtils.readShort(byArray, nArray);
        for (n4 = 0; n4 < n3; ++n4) {
            short s;
            int n10;
            UIComponent uIComponent;
            int n11 = EngineUtils.readByte(byArray, nArray);
            if (n11 == 0) {
                uIComponent = new MenuWidget();
                ((MenuWidget)uIComponent).b(n11);
                ((MenuWidget)uIComponent).a(EngineUtils.readShort(byArray, nArray));
                ((MenuWidget)uIComponent).setX(EngineUtils.readShort(byArray, nArray), this.root);
                ((MenuWidget)uIComponent).setY(EngineUtils.readShort(byArray, nArray), this.root);
                ((MenuWidget)uIComponent).setWidth(EngineUtils.readShort(byArray, nArray), this.root);
                ((MenuWidget)uIComponent).setHeight(EngineUtils.readShort(byArray, nArray), this.root);
                ((MenuWidget)uIComponent).c(menuWidget.getId());
                if (menuWidget.a != null) {
                    for (int i = 0; i < menuWidget.a.itemIds.length; ++i) {
                        if (menuWidget.a.itemIds[i] != ((MenuWidget)uIComponent).getId()) continue;
                        ((MenuWidget)uIComponent).a(menuWidget.a);
                        break;
                    }
                }
                if (menuWidget.b != null) {
                    for (int i = 0; i < menuWidget.b.itemIds.length; ++i) {
                        if (menuWidget.b.itemIds[i] != ((MenuWidget)uIComponent).getId()) continue;
                        ((MenuWidget)uIComponent).a(menuWidget.b);
                        break;
                    }
                }
                this.components[this.componentCount] = uIComponent;
                ++this.componentCount;
                menuWidget.getChildren()[n4] = uIComponent;
                this.a(byArray, nArray, (MenuWidget)menuWidget.getChildren()[n4], n, bl);
                continue;
            }
            if (n11 == 1) {
                uIComponent = new ItemListWidget();
                ((ItemListWidget)uIComponent).b(n11);
                ((ItemListWidget)uIComponent).a(EngineUtils.readShort(byArray, nArray));
                ((ItemListWidget)uIComponent).setX(EngineUtils.readShort(byArray, nArray), this.root);
                ((ItemListWidget)uIComponent).setY(EngineUtils.readShort(byArray, nArray), this.root);
                ((ItemListWidget)uIComponent).setWidth(EngineUtils.readShort(byArray, nArray), this.root);
                ((ItemListWidget)uIComponent).setHeight(EngineUtils.readShort(byArray, nArray), this.root);
                ((ItemListWidget)uIComponent).l();
                ((ItemListWidget)uIComponent).textPainter = this.textPainter;
                int n12 = EngineUtils.readShort(byArray, nArray);
                byte[] byArray4 = new byte[n12];
                for (n10 = 0; n10 < n12; ++n10) {
                    byArray4[n10] = EngineUtils.readByte(byArray, nArray);
                }
                ((ItemListWidget)uIComponent).getStyle().text = EngineUtils.decodeUtf16(byArray4);
                ((ItemListWidget)uIComponent).getStyle().b = EngineUtils.readByte(byArray, nArray);
                ((ItemListWidget)uIComponent).getStyle().c = EngineUtils.readByte(byArray, nArray);
                ((ItemListWidget)uIComponent).getStyle().d = EngineUtils.readByte(byArray, nArray) != 0;
                ((ItemListWidget)uIComponent).getStyle().e = EngineUtils.readInt(byArray, nArray);
                ((ItemListWidget)uIComponent).getStyle().f = EngineUtils.readInt(byArray, nArray);
                ((ItemListWidget)uIComponent).getStyle().g = EngineUtils.readInt(byArray, nArray);
                n10 = EngineUtils.readShort(byArray, nArray);
                s = EngineUtils.readByte(byArray, nArray);
                if (n10 < 0) {
                    ((ItemListWidget)uIComponent).getStyle().i = null;
                } else {
                    ((ItemListWidget)uIComponent).getStyle().i = new SpriteWidget();
                    ((ItemListWidget)uIComponent).getStyle().i.a = s;
                    ((ItemListWidget)uIComponent).getStyle().i.a(n10);
                }
                ((ItemListWidget)uIComponent).getStyle().j = EngineUtils.readInt(byArray, nArray);
                ((ItemListWidget)uIComponent).getStyle().k = EngineUtils.readInt(byArray, nArray);
                ((ItemListWidget)uIComponent).getStyle().l = EngineUtils.readInt(byArray, nArray);
                n2 = EngineUtils.readShort(byArray, nArray);
                n5 = EngineUtils.readByte(byArray, nArray);
                if (n2 < 0) {
                    ((ItemListWidget)uIComponent).getStyle().m = null;
                } else {
                    ((ItemListWidget)uIComponent).getStyle().m = new SpriteWidget();
                    ((ItemListWidget)uIComponent).getStyle().m.a(n2);
                    ((ItemListWidget)uIComponent).getStyle().m.a = n5;
                }
                ((ItemListWidget)uIComponent).getStyle().h = EngineUtils.readByte(byArray, nArray);
                if (((ItemListWidget)uIComponent).getStyle().i != null) {
                    ((ItemListWidget)uIComponent).getStyle().i.a(n, bl, ((ItemListWidget)uIComponent).getStyle().h);
                }
                if (((ItemListWidget)uIComponent).getStyle().m != null) {
                    ((ItemListWidget)uIComponent).getStyle().m.a(n, bl, ((ItemListWidget)uIComponent).getStyle().h);
                }
                ((ItemListWidget)uIComponent).c(menuWidget.getId());
                if (menuWidget.a != null) {
                    for (n11 = 0; n11 < menuWidget.a.itemIds.length; ++n11) {
                        if (menuWidget.a.itemIds[n11] != ((ItemListWidget)uIComponent).getId()) continue;
                        ((ItemListWidget)uIComponent).a(menuWidget.a);
                        break;
                    }
                }
                if (menuWidget.b != null) {
                    for (n11 = 0; n11 < menuWidget.b.itemIds.length; ++n11) {
                        if (menuWidget.b.itemIds[n11] != ((ItemListWidget)uIComponent).getId()) continue;
                        ((ItemListWidget)uIComponent).a(menuWidget.b);
                        break;
                    }
                }
                this.components[this.componentCount] = uIComponent;
                ++this.componentCount;
                menuWidget.getChildren()[n4] = uIComponent;
                ((ItemListWidget)uIComponent).a = EngineUtils.readByte(byArray, nArray);
                ((ItemListWidget)uIComponent).b = EngineUtils.readByte(byArray, nArray);
                continue;
            }
            if (n11 != 2) continue;
            uIComponent = new MessageBox();
            ((MessageBox)uIComponent).q(EngineUtils.readShort(byArray, nArray));
            ((MessageBox)uIComponent).setX(EngineUtils.readShort(byArray, nArray), this.root);
            ((MessageBox)uIComponent).setY(EngineUtils.readShort(byArray, nArray), this.root);
            ((MessageBox)uIComponent).a((int)EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).b(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).c(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).d(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).e(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).f(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).g(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).h(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).k(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).l(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).m(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).n(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).o(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).p(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).i(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).j(EngineUtils.readByte(byArray, nArray));
            ((MessageBox)uIComponent).a = EngineUtils.readInt(byArray, nArray);
            short s2 = EngineUtils.readShort(byArray, nArray);
            int n13 = EngineUtils.readByte(byArray, nArray);
            if (s2 < 0) {
                ((MessageBox)uIComponent).b = null;
            } else {
                ((MessageBox)uIComponent).b = new SpriteWidget();
                ((MessageBox)uIComponent).b.a(s2);
                ((MessageBox)uIComponent).b.a = n13;
                ((MessageBox)uIComponent).b.a(n, bl, (byte)n13);
            }
            s2 = EngineUtils.readShort(byArray, nArray);
            n13 = EngineUtils.readByte(byArray, nArray);
            if (s2 < 0) {
                ((MessageBox)uIComponent).c = null;
            } else {
                ((MessageBox)uIComponent).c = new SpriteWidget();
                ((MessageBox)uIComponent).c.a(s2);
                ((MessageBox)uIComponent).c.a = n13;
                ((MessageBox)uIComponent).c.a(n, bl, (byte)n13);
            }
            ((MessageBox)uIComponent).r(EngineUtils.readShort(byArray, nArray));
            byte by = EngineUtils.readByte(byArray, nArray);
            n10 = by;
            if (by == 0) {
                ((MessageBox)uIComponent).e = ((MessageBox)uIComponent).n();
            } else if (n10 == 1) {
                n11 = ((MessageBox)uIComponent).m();
                n5 = ((MessageBox)uIComponent).l();
                UIHotspot[] uIHotspotArray = new UIHotspot[n5 * n11];
                for (n13 = 0; n13 != n5 * n11; ++n13) {
                    uIHotspotArray[n13] = new UIHotspot();
                }
                ((MessageBox)uIComponent).e = uIHotspotArray;
                s = EngineUtils.readShort(byArray, nArray);
                for (n2 = 0; n2 < s; ++n2) {
                    n5 = EngineUtils.readShort(byArray, nArray);
                    n11 = EngineUtils.readShort(byArray, nArray);
                    byte by2 = EngineUtils.readByte(byArray, nArray);
                    n13 = EngineUtils.readShort(byArray, nArray);
                    n10 = EngineUtils.readShort(byArray, nArray);
                    short s3 = EngineUtils.readShort(byArray, nArray);
                    short s4 = EngineUtils.readShort(byArray, nArray);
                    ((MessageBox)uIComponent).e[n5] = new UIHotspot(n11, by2, n13, n10, s3, s4);
                }
            }
            ((MessageBox)uIComponent).s(menuWidget.getId());
            this.components[this.componentCount] = uIComponent;
            ++this.componentCount;
            menuWidget.getChildren()[n4] = uIComponent;
        }
    }

    private Rectangle a(UIComponent uIComponent) {
        if (uIComponent.getType() != 0) {
            return new Rectangle(uIComponent.getX(), uIComponent.getY(), uIComponent.getWidth(), uIComponent.getHeight());
        }
        MenuWidget menuWidget = (MenuWidget)uIComponent;
        if (menuWidget.getChildren() == null || menuWidget.getChildren()[0] == null) {
            return new Rectangle(uIComponent.getX(), uIComponent.getY(), uIComponent.getWidth(), uIComponent.getHeight());
        }
        int n = this.a((UIComponent)menuWidget.getChildren()[0]).x;
        int n2 = this.a((UIComponent)menuWidget.getChildren()[0]).x + this.a((UIComponent)menuWidget.getChildren()[0]).width;
        int n3 = this.a((UIComponent)menuWidget.getChildren()[0]).y;
        int n4 = this.a((UIComponent)menuWidget.getChildren()[0]).y + this.a((UIComponent)menuWidget.getChildren()[0]).height;
        for (int i = 0; i < menuWidget.getChildren().length && menuWidget.getChildren()[i] != null; ++i) {
            Rectangle rectangle = this.a(menuWidget.getChildren()[i]);
            if (n > rectangle.x) {
                n = rectangle.x;
            }
            if (n2 < rectangle.x + rectangle.width) {
                n2 = rectangle.x + rectangle.width;
            }
            if (n3 > rectangle.y) {
                n3 = rectangle.y;
            }
            if (n4 >= rectangle.y + rectangle.height) continue;
            n4 = rectangle.y + rectangle.height;
        }
        return new Rectangle(n, n3, n2 - n, n4 - n3);
    }

    /*
     * Unable to fully structure code
     */
    public final void render(Graphics graphics) {
        var3_2 = this.root;
        var2_3 = graphics;
        var1_1 = this;
        var6_4 = var3_2;
        var5_6 = var2_3;
        var4_8 = var1_1;
        if (var6_4.a == null && var6_4.b == null) ** GOTO lbl-1000
        if (var6_4.a == null && var6_4.b != null) {
            v0 = var6_4.b;
        } else if (var6_4.a != null && var6_4.b == null) {
            v0 = var6_4.a;
        } else lbl-1000:
        // 2 sources

        {
            v0 = var6_4 = null;
        }
        if (v0 != null && var6_4.visibleItemCount < var6_4.itemCount) {
            v1 = var7_10 = var4_8;
            var4_8 = var6_4;
            var6_4 = v1;
            var8_11 = 0;
            var9_12 = 0;
            var10_13 = 0;
            var11_14 = 0;
            if (var4_8.itemIds[0] != -1) {
                var12_15 = super.a(var7_10.getComponent(var4_8.itemIds[0]));
                var8_11 = var12_15.x;
                var9_12 = var12_15.x + var12_15.width;
                var10_13 = var12_15.y;
                var11_14 = var12_15.y + var12_15.height;
                for (var13_16 = 1; var13_16 != var4_8.visibleItemCount; ++var13_16) {
                    var12_15 = super.a(var7_10.getComponent(var4_8.itemIds[var13_16]));
                    if (var8_11 > var12_15.x) {
                        var8_11 = var12_15.x;
                    }
                    if (var9_12 < var12_15.x + var12_15.width) {
                        var9_12 = var12_15.x + var12_15.width;
                    }
                    if (var10_13 > var12_15.y) {
                        var10_13 = var12_15.y;
                    }
                    if (var11_14 >= var12_15.y + var12_15.height) continue;
                    var11_14 = var12_15.y + var12_15.height;
                }
            }
            new Rectangle(var8_11, var10_13, var9_12 - var8_11, var11_14 - var10_13);
            var4_8 = new Rectangle();
            var6_4 = new Rectangle();
            var5_6.setColor(255, 255, 255);
            var5_6.fillRect(var4_8.x, var4_8.y, var4_8.width, var4_8.height);
            var5_6.setColor(245, 222, 179);
            var5_6.drawRect(var4_8.x, var4_8.y, var4_8.width, var4_8.height);
            var5_6.setColor(95, 158, 160);
            var5_6.fillRect(var6_4.x, var6_4.y, var6_4.width, var6_4.height);
        }
        for (var4_9 = 0; var4_9 < var3_2.getChildren().length && var3_2.getChildren()[var4_9] != null; ++var4_9) {
            if (var3_2.getChildren()[var4_9].getSelection() != null) {
                var5_7 = false;
                var6_5 = EngineUtils.a(var1_1.f);
                if (var6_5 > 0 && var1_1.f[var6_5 - 1] == var3_2.getId()) {
                    var5_7 = true;
                }
                var3_2.getChildren()[var4_9].getSelection().a(var2_3, var3_2.getChildren()[var4_9].getId(), var5_7, var1_1.f, true, var1_1.root);
                continue;
            }
            var3_2.getChildren()[var4_9].render(var2_3, false, true, var1_1.root, var1_1.f);
        }
    }

    public final void update() {
        MenuWidget menuWidget = this.root;
        UILayoutView uILayoutView = this;
        for (int i = 0; i < menuWidget.getChildren().length && menuWidget.getChildren()[i] != null; ++i) {
            if (menuWidget.getChildren()[i].getSelection() != null) {
                menuWidget.getChildren()[i].getSelection().a(menuWidget.getChildren()[i].getId(), uILayoutView.f, true, uILayoutView.root);
                continue;
            }
            menuWidget.getChildren()[i].a(false, true, uILayoutView.root, uILayoutView.f);
        }
    }

    public final UIComponent getComponent(int componentId) {
        return EngineUtils.a(this.root, componentId);
    }

    /*
     * WARNING - void declaration
     */
    public final boolean navigateSelection(int direction) {
        boolean bl;
        UIComponent uIComponent;
        int n = 0;
        int[] nArray = this.e;
        UIComponent uIComponent2 = this.root;
        UILayoutView uILayoutView = this;
        while (true) {
            int n2;
            if ((n2 = EngineUtils.a(nArray)) == 0) {
                uIComponent = uIComponent2;
                break;
            }
            if (n == n2 - 1) {
                uIComponent = uIComponent2.getChildren()[nArray[n]];
                break;
            }
            UIComponent uIComponent3 = uIComponent2.getChildren()[nArray[n]];
            ++n;
            uIComponent2 = uIComponent3;
        }
        MenuWidget menuWidget = uIComponent;
        if (uIComponent.getType() == 2) {
            uIComponent2 = (MessageBox)((Object)menuWidget);
            int n3 = direction;
            UILayoutView uILayoutView2 = this;
            boolean bl2 = false;
            switch (n3) {
                case 0: {
                    bl2 = ((MessageBox)uIComponent2).a((byte)0);
                    int[] nArray2 = new int[]{-1, -1, -1, -1};
                    uILayoutView2.eventListener.onScriptEvent(new int[]{-1, -1, 0});
                    break;
                }
                case 1: {
                    bl2 = ((MessageBox)uIComponent2).a((byte)1);
                    int[] nArray3 = new int[]{-1, -1, -1, -1};
                    uILayoutView2.eventListener.onScriptEvent(new int[]{-1, -1, 1});
                    break;
                }
                case 2: {
                    bl2 = ((MessageBox)uIComponent2).a((byte)2);
                    int[] nArray4 = new int[]{-1, -1, -1, -1};
                    uILayoutView2.eventListener.onScriptEvent(new int[]{-1, -1, 2});
                    break;
                }
                case 3: {
                    bl2 = ((MessageBox)uIComponent2).a((byte)3);
                    int[] nArray5 = new int[]{-1, -1, -1, -1};
                    uILayoutView2.eventListener.onScriptEvent(new int[]{-1, -1, 3});
                    break;
                }
                case 5: {
                    int[] nArray6 = new int[]{-1, -1, -1, -1};
                    uILayoutView2.eventListener.onScriptEvent(new int[]{-1, -1, 4});
                    bl2 = true;
                    break;
                }
                case 7: {
                    bl2 = uILayoutView2.e();
                    if (bl2) {
                        ((MessageBox)uIComponent2).d = false;
                        int[] nArray7 = new int[]{-1, -1, -1, -1};
                        uILayoutView2.eventListener.onScriptEvent(new int[]{-1, -1, 7});
                        break;
                    }
                    int[] nArray8 = new int[]{-1, -1, -1, -1};
                    uILayoutView2.eventListener.onScriptEvent(new int[]{-1, -1, 5});
                }
            }
            bl = bl2;
        } else {
            void var1_1;
            uIComponent2 = menuWidget;
            void var2_14 = var1_1;
            UILayoutView uILayoutView3 = this;
            boolean bl3 = false;
            n = 0;
            Object object = ((MenuWidget)uIComponent2).l() != null ? ((MenuWidget)uIComponent2).l() : (Object)new byte[][]{{0, 0, 1, -1}, {1, 1, 1, -1}, {2, 2, 1, -1}, {3, 3, 1, -1}, {5, 4, -1, -1}, {7, 5, -1, -1}};
            int[] nArray9 = new int[3];
            nArray9[1] = ((MenuWidget)uIComponent2).b != null ? ((MenuWidget)uIComponent2).b.selectedIndex : -1;
            nArray9[0] = ((MenuWidget)uIComponent2).a != null ? ((MenuWidget)uIComponent2).a.selectedIndex : -1;
            for (int i = 0; i < ((byte[][])object).length; ++i) {
                if (object[i][0] != var2_14) continue;
                n = 1;
                bl3 = false;
                switch (object[i][1]) {
                    case 0: {
                        nArray9[2] = 0;
                        if (((MenuWidget)uIComponent2).a != null) {
                            if (object[i][3] != -1 && ((MenuWidget)uIComponent2).a.selectedIndex % (object[i][3] + 1) == 0) {
                                ((MenuWidget)uIComponent2).a.a(object[i][3], uILayoutView3.root);
                            } else {
                                ((MenuWidget)uIComponent2).a.b(object[i][2], uILayoutView3.root);
                            }
                            bl3 = true;
                            nArray9[0] = ((MenuWidget)uIComponent2).a.selectedIndex;
                            int[] nArray10 = new int[]{-1, -1, -1, -1};
                            uILayoutView3.eventListener.onScriptEvent(nArray9);
                            break;
                        }
                        int[] nArray11 = new int[]{-1, -1, -1, -1};
                        uILayoutView3.eventListener.onScriptEvent(nArray9);
                        break;
                    }
                    case 1: {
                        nArray9[2] = 1;
                        if (((MenuWidget)uIComponent2).a != null) {
                            if (object[i][3] != -1 && (((MenuWidget)uIComponent2).a.selectedIndex + 1) % (object[i][3] + 1) == 0) {
                                ((MenuWidget)uIComponent2).a.b(object[i][3], uILayoutView3.root);
                            } else {
                                ((MenuWidget)uIComponent2).a.a(object[i][2], uILayoutView3.root);
                            }
                            bl3 = true;
                            nArray9[0] = ((MenuWidget)uIComponent2).a.selectedIndex;
                            int[] nArray12 = new int[]{-1, -1, -1, -1};
                            uILayoutView3.eventListener.onScriptEvent(nArray9);
                            break;
                        }
                        int[] nArray13 = new int[]{-1, -1, -1, -1};
                        uILayoutView3.eventListener.onScriptEvent(nArray9);
                        break;
                    }
                    case 2: {
                        nArray9[2] = 2;
                        if (((MenuWidget)uIComponent2).b != null) {
                            if (object[i][3] != -1 && ((MenuWidget)uIComponent2).b.selectedIndex % (object[i][3] + 1) == 0) {
                                ((MenuWidget)uIComponent2).b.a(object[i][3], uILayoutView3.root);
                            } else {
                                ((MenuWidget)uIComponent2).b.b(object[i][2], uILayoutView3.root);
                            }
                            bl3 = true;
                            nArray9[1] = ((MenuWidget)uIComponent2).b.selectedIndex;
                            int[] nArray14 = new int[]{-1, -1, -1, -1};
                            uILayoutView3.eventListener.onScriptEvent(nArray9);
                            break;
                        }
                        int[] nArray15 = new int[]{-1, -1, -1, -1};
                        uILayoutView3.eventListener.onScriptEvent(nArray9);
                        break;
                    }
                    case 3: {
                        nArray9[2] = 3;
                        if (((MenuWidget)uIComponent2).b != null) {
                            if (object[i][3] != -1 && (((MenuWidget)uIComponent2).b.selectedIndex + 1) % (object[i][3] + 1) == 0) {
                                ((MenuWidget)uIComponent2).b.b(object[i][3], uILayoutView3.root);
                            } else {
                                ((MenuWidget)uIComponent2).b.a(object[i][2], uILayoutView3.root);
                            }
                            bl3 = true;
                            nArray9[1] = ((MenuWidget)uIComponent2).b.selectedIndex;
                            int[] nArray16 = new int[]{-1, -1, -1, -1};
                            uILayoutView3.eventListener.onScriptEvent(nArray9);
                            break;
                        }
                        int[] nArray17 = new int[]{-1, -1, -1, -1};
                        uILayoutView3.eventListener.onScriptEvent(nArray9);
                        break;
                    }
                    case 4: {
                        if (((MenuWidget)uIComponent2).b != null) {
                            bl3 = ((MenuWidget)uIComponent2).b.selectedIndex >= EngineUtils.a(((MenuWidget)uIComponent2).b.itemIds) ? uILayoutView3.a(uIComponent2, ((MenuWidget)uIComponent2).b.itemIds[((MenuWidget)uIComponent2).b.selectedIndex - ((MenuWidget)uIComponent2).b.firstVisibleIndex]) : uILayoutView3.a(uIComponent2, ((MenuWidget)uIComponent2).b.itemIds[((MenuWidget)uIComponent2).b.selectedIndex]);
                        }
                        if (!bl3 && ((MenuWidget)uIComponent2).a != null) {
                            bl3 = ((MenuWidget)uIComponent2).a.selectedIndex >= EngineUtils.a(((MenuWidget)uIComponent2).a.itemIds) ? uILayoutView3.a(uIComponent2, ((MenuWidget)uIComponent2).a.itemIds[((MenuWidget)uIComponent2).a.selectedIndex - ((MenuWidget)uIComponent2).a.firstVisibleIndex]) : uILayoutView3.a(uIComponent2, ((MenuWidget)uIComponent2).a.itemIds[((MenuWidget)uIComponent2).a.selectedIndex]);
                        }
                        if (bl3) {
                            nArray9[2] = 6;
                            int[] nArray18 = new int[]{-1, -1, -1, -1};
                            uILayoutView3.eventListener.onScriptEvent(nArray9);
                            break;
                        }
                        nArray9[2] = 4;
                        int[] nArray19 = new int[]{-1, -1, -1, -1};
                        uILayoutView3.eventListener.onScriptEvent(nArray9);
                        break;
                    }
                    case 5: {
                        bl3 = uILayoutView3.e();
                        if (bl3) {
                            nArray9[2] = 7;
                            int[] nArray20 = new int[]{-1, -1, -1, -1};
                            uILayoutView3.eventListener.onScriptEvent(nArray9);
                            break;
                        }
                        nArray9[2] = 5;
                        int[] nArray21 = new int[]{-1, -1, -1, -1};
                        uILayoutView3.eventListener.onScriptEvent(nArray9);
                    }
                }
                if (bl3) break;
            }
            if (n == 0) {
                switch (var2_14) {
                    case 14:
                    case 15:
                    case 16:
                    case 17:
                    case 18:
                    case 19:
                    case 20:
                    case 21:
                    case 22:
                    case 23: {
                        nArray9[2] = var2_14 - 6;
                        int[] nArray22 = new int[]{-1, -1, -1, -1};
                        uILayoutView3.eventListener.onScriptEvent(nArray9);
                    }
                }
            }
            bl = bl3;
        }
        return bl;
    }

    private boolean e() {
        boolean bl = false;
        int n = -1;
        for (int i = EngineUtils.a(this.f) - 2; i >= 0; --i) {
            UIComponent uIComponent = EngineUtils.a(this.root, this.f[i]);
            if (((MenuWidget)uIComponent).a == null && ((MenuWidget)uIComponent).b == null) continue;
            bl = true;
            n = uIComponent.getId();
            break;
        }
        if (bl) {
            this.e = this.c(n);
            if (this.e == null) {
                this.e = EngineUtils.b(50);
            }
            this.f();
        }
        return bl;
    }

    private boolean a(UIComponent uIComponent, int n) {
        if (uIComponent.getType() == 1) {
            return false;
        }
        int n2 = this.a(uIComponent, n, true);
        if (n2 == -1) {
            return false;
        }
        this.e = this.c(n2);
        if (this.e == null) {
            this.e = EngineUtils.b(50);
        }
        this.f();
        return true;
    }

    private void f() {
        this.f = EngineUtils.b(50);
        UIComponent uIComponent = this.root;
        int n = 0;
        ++n;
        this.f[0] = uIComponent.getId();
        for (int i = 0; i < this.e.length && this.e[i] != -1; ++i) {
            uIComponent = uIComponent.getChildren()[this.e[i]];
            this.f[n++] = uIComponent.getId();
        }
    }

    private int a(UIComponent uIComponent, int n, boolean bl) {
        if (uIComponent.getType() == 2 && n == -1) {
            if (bl) {
                ((MessageBox)uIComponent).d = true;
            }
            return uIComponent.getId();
        }
        if ((((MenuWidget)uIComponent).a != null || ((MenuWidget)uIComponent).b != null) && n == -1) {
            return uIComponent.getId();
        }
        for (int i = 0; i < uIComponent.getChildren().length && uIComponent.getChildren()[i] != null; ++i) {
            int n2;
            if (uIComponent.getChildren()[i].getType() == 1 || n != -1 && uIComponent.getChildren()[i].getId() != n || (n2 = this.a(uIComponent.getChildren()[i], -1, bl)) == -1) continue;
            return n2;
        }
        return -1;
    }

    private int[] c(int n) {
        int[] nArray = EngineUtils.b(50);
        UIComponent uIComponent = EngineUtils.a(this.root, n);
        while (uIComponent.getParentId() != -1) {
            UIComponent uIComponent2 = EngineUtils.a(this.root, uIComponent.getParentId());
            for (int i = 0; i < uIComponent2.getChildren().length && uIComponent2.getChildren()[i] != null; ++i) {
                if (uIComponent2.getChildren()[i].getId() != uIComponent.getId()) continue;
                EngineUtils.b(nArray, i);
                break;
            }
            uIComponent = EngineUtils.a(this.root, uIComponent.getParentId());
        }
        return nArray;
    }

    public final void release() {
        this.root.release();
        this.d = null;
        this.e = null;
        this.f = null;
        this.eventListener = null;
        this.components = null;
    }

    public UILayoutView() {
    }

    private static RecordStore a(String string, String string2, String string3, String charSequence, int n) {
        RecordStore recordStore = null;
        try {
            if (string3 == null || string3.length() == 0) {
                string3 = "00";
            }
            if (charSequence != null) {
                ((String)charSequence).length();
            }
            charSequence = new StringBuffer();
            ((StringBuffer)charSequence).append("dcn").append(string).append(string2).append(string3).append(n);
            recordStore = RecordStore.openRecordStore(((StringBuffer)charSequence).toString(), true, 1, true);
        }
        catch (Exception exception) {
            exception.printStackTrace();
        }
        return recordStore;
    }

    public static void a(CarrierHelper object, String object2, String object3, String object4, String string, int n) {
        if ((object2 = UILayoutView.a((String)object2, (String)object3, (String)object4, string, n)) != null) {
            try {
                try {
                    object3 = new ByteArrayOutputStream();
                    object4 = new DataOutputStream((OutputStream)object3);
                    ((DataOutputStream)object4).writeInt(((CarrierHelper)object).i());
                    if (((CarrierHelper)object).i() < n) {
                        ((DataOutputStream)object4).writeInt(((CarrierHelper)object).d());
                        ((DataOutputStream)object4).writeUTF(((CarrierHelper)object).c());
                        ((DataOutputStream)object4).writeUTF(((CarrierHelper)object).b());
                        ((DataOutputStream)object4).writeUTF(((CarrierHelper)object).g());
                        ((DataOutputStream)object4).writeInt(((CarrierHelper)object).a());
                        ((DataOutputStream)object4).writeUTF(((CarrierHelper)object).f());
                        ((DataOutputStream)object4).writeUTF(((CarrierHelper)object).e());
                        ((DataOutputStream)object4).writeBoolean(((CarrierHelper)object).h());
                        ((DataOutputStream)object4).writeInt(((CarrierHelper)object).j());
                        ((DataOutputStream)object4).writeLong(((CarrierHelper)object).k());
                    }
                    object = ((ByteArrayOutputStream)object3).toByteArray();
                    if (((RecordStore)object2).getNumRecords() == 0) {
                        ((RecordStore)object2).addRecord((byte[])object, 0, ((Object)object).length);
                    } else {
                        ((RecordStore)object2).setRecord(1, (byte[])object, 0, ((Object)object).length);
                    }
                }
                catch (Exception exception) {
                    exception.printStackTrace();
                    try {
                        ((RecordStore)object2).closeRecordStore();
                        return;
                    }
                    catch (RecordStoreNotOpenException recordStoreNotOpenException) {
                        recordStoreNotOpenException.printStackTrace();
                        return;
                    }
                    catch (RecordStoreException recordStoreException) {
                        recordStoreException.printStackTrace();
                        return;
                    }
                }
            }
            catch (Throwable throwable) {
                try {
                    ((RecordStore)object2).closeRecordStore();
                }
                catch (RecordStoreNotOpenException recordStoreNotOpenException) {
                    recordStoreNotOpenException.printStackTrace();
                }
                catch (RecordStoreException recordStoreException) {
                    recordStoreException.printStackTrace();
                }
                throw throwable;
            }
            try {
                ((RecordStore)object2).closeRecordStore();
                return;
            }
            catch (RecordStoreNotOpenException recordStoreNotOpenException) {
                recordStoreNotOpenException.printStackTrace();
                return;
            }
            catch (RecordStoreException recordStoreException) {
                recordStoreException.printStackTrace();
            }
        }
    }
}

