/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
import game.WorldManager;
import javax.microedition.lcdui.Graphics;

public class WorldEntity
extends BaseEntity {
    public SpriteRenderer spriteRenderer = new SpriteRenderer();
    public WorldEntity targetEntity = null;

    public boolean loadSprite(int spriteId, boolean hasExtendedAnimationSteps) {
        return this.spriteRenderer.loadSprite(spriteId, hasExtendedAnimationSteps);
    }

    public final void replaceSpriteImage(int sheetIndex, int imageId) {
        this.spriteRenderer.replaceImage(sheetIndex, imageId, true);
    }

    public final boolean setAnimation(byte animationId, byte nextAnimationId, boolean resetStep) {
        return this.spriteRenderer.setAnimation(animationId, nextAnimationId, resetStep);
    }

    public final void setAnimationAndDirection(byte animationId, byte direction) {
        this.spriteRenderer.setAnimationWithoutReset(animationId, (byte)-1);
        this.facingDirection = animationId = direction;
    }

    public final boolean advanceAnimationIfVisible() {
        if (!this.visible) {
            return false;
        }
        return this.spriteRenderer.advanceAnimation();
    }

    public final boolean isLastAnimationStep() {
        return this.spriteRenderer.isLastAnimationStep();
    }

    public final void renderInWorld(Graphics graphics, int cameraX, int cameraY) {
        if (!this.visible) {
            return;
        }
        if (this.facingDirection == 3) {
            this.spriteRenderer.drawCurrentFrame(graphics, this.posX - cameraX, this.posY - cameraY, (byte)1);
            return;
        }
        this.spriteRenderer.drawCurrentFrame(graphics, this.posX - cameraX, this.posY - cameraY, (byte)0);
    }

    public void activate() {
        this.a(true);
        this.setVisible(true);
        this.c(true);
    }

    public void deactivate() {
        this.a(false);
        this.setVisible(false);
        this.c(false);
    }

    public final void deactivateTarget() {
        if (this.targetEntity != null) {
            this.targetEntity.deactivate();
        }
    }

    public void moveInFacingDirection(int distance) {
        switch (this.facingDirection) {
            case 3: {
                this.movePosX(-distance);
                break;
            }
            case 1: {
                this.movePosX(distance);
                break;
            }
            case 2: {
                this.movePosY(-distance);
                break;
            }
            case 0: {
                this.movePosY(distance);
            }
        }
        if (this.targetEntity != null) {
            this.targetEntity.setPosition(this.posX, this.posY);
        }
    }

    public final void b(int n) {
        switch (n) {
            case 3: {
                this.movePosX(-4);
                break;
            }
            case 1: {
                this.movePosX(4);
                break;
            }
            case 2: {
                this.movePosY(-4);
                break;
            }
            case 0: {
                this.movePosY(4);
            }
        }
        if (this.targetEntity != null) {
            this.targetEntity.setPosition(this.posX, this.posY);
        }
    }

    public final void f() {
        if (!this.visible) {
            return;
        }
        if (this.spriteRenderer.i()) {
            this.c(true);
            return;
        }
        if (EngineUtils.a(WorldManager.a().a.cameraX, WorldManager.a().a.cameraY, (int)BaseScreen.getScreenWidth(), (int)BaseScreen.getScreenHeight(), this.posX, this.posY, this.spriteRenderer.j())) {
            this.c(true);
            return;
        }
        this.c(false);
    }

    public final void c(int n) {
        this.spriteRenderer.a(n);
    }
}

