backlightcolor:Disabled
compatfantasyzonefix:off
compatignorevolumechanges:off
compatimmediaterepaints:off
compatmcv3horizfovfix:off
compatoverrideplatchecks:on
compatrepaintonsetcurrent:off
compatsiemensfriendlydrawing:off
compattranstooriginonreset:off
dojaversion:200
fontoffset:0
fps:60
fpshack:Disabled
m3gantialiasmode:app
m3gbilinearmode:app
m3gdisablefog:off
m3gditheringmode:app
m3gmipmapmode:app
m3gperspcorrmode:app
m3gperspcorrsubfactor:high
phone:Standard
rotate:0
scrheight:320
scrwidth:240
spdhackm3ghalfres:off
spdhackmcv3halfres:off
spdhackmcv3nolighting:off
spdhacknoalpha:off
