/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
package a;

import a.NetworkConfig;
import a.PropertyRef;
import a.SessionData;

public final class NetworkConnection {
    public SessionData a;
    public NetworkConfig b;
    public int c;
    public int d;
    int e;
    public int f;
    boolean g;
    public boolean h;
    boolean i;

    public NetworkConnection(SessionData sessionData) {
        this.a = sessionData;
    }

    public final void a(int n, Object object) {
        this.a.e[this.d + n] = object;
    }

    public final Object a(int n) {
        return this.a.e[this.d + n];
    }

    public final int a(Object object) {
        int n = this.a();
        this.c(n + 1);
        this.a(n, object);
        return 1;
    }

    public final void a(int n, int n2, int n3) {
        this.a.a(this.d + n, this.d + n2, n3);
    }

    public final void a(int n, int n2) {
        while (n <= n2) {
            this.a.e[this.d + n] = null;
            ++n;
        }
    }

    public final void b(int n) {
        if (this.a() < n) {
            this.c(n);
        }
        this.a(n, this.a() - 1);
    }

    public final void c(int n) {
        this.a.a(this.d + n);
    }

    public final void d(int n) {
        this.a.b(this.d + n);
    }

    public final PropertyRef e(int n) {
        PropertyRef propertyRef;
        int n2 = this.d + n;
        SessionData sessionData = this.a;
        int n3 = sessionData.d.size();
        while (--n3 >= 0) {
            propertyRef = (PropertyRef)sessionData.d.elementAt(n3);
            if (propertyRef.b == n2) {
                return propertyRef;
            }
            if (propertyRef.b < n2) break;
        }
        propertyRef = new PropertyRef();
        new PropertyRef().a = sessionData;
        propertyRef.b = n2;
        sessionData.d.insertElementAt(propertyRef, n3 + 1);
        return propertyRef;
    }

    public final int a() {
        return this.a.f - this.d;
    }

    public final void b() {
        if (this.e()) {
            this.c = 0;
            if (this.b.a.e) {
                this.d += this.f;
                this.c(this.b.a.g);
                int n = Math.min(this.f, this.b.a.d);
                this.a(-this.f, 0, n);
                return;
            }
            this.c(this.b.a.g);
        }
    }

    public final void c() {
        if (this.e()) {
            this.c(this.b.a.g);
        }
    }

    public final void b(int n, int n2) {
        int n3 = this.b.a.d;
        int n4 = this.f - n3;
        if (n4 < 0) {
            n4 = 0;
        }
        if (n2 == -1) {
            n2 = n4;
            this.c(n + n2);
        }
        if (n4 > n2) {
            n4 = n2;
        }
        this.a(-this.f + n3, n, n4);
        if (n2 - n4 > 0) {
            this.a(n + n4, n + n2 - 1);
        }
    }

    public final boolean d() {
        return !this.e();
    }

    public final boolean e() {
        return this.b != null;
    }
}

