/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
package a;

import a.SessionData;

public final class PropertyRef {
    public SessionData a;
    public int b;
    public Object c;

    public final Object a() {
        if (this.a == null) {
            return this.c;
        }
        return this.a.e[this.b];
    }

    public final void a(Object object) {
        if (this.a == null) {
            this.c = object;
            return;
        }
        this.a.e[this.b] = object;
    }
}

