/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
package a;

import a.BillingClient;
import a.NetworkConfig;
import a.NetworkConnection;
import a.PropertyRef;
import a.ProtocolEncoder;
import a.SecurityHelper;
import java.util.Vector;

public final class SessionData {
    public SecurityHelper a;
    public SessionData b;
    public String c = "";
    public Vector d;
    public Object[] e;
    public int f;
    private NetworkConnection[] h;
    private int i;
    public ProtocolEncoder g;

    public SessionData() {
    }

    public SessionData(ProtocolEncoder protocolEncoder, SecurityHelper securityHelper) {
        this.g = protocolEncoder;
        this.a = securityHelper;
        this.e = new Object[10];
        this.h = new NetworkConnection[10];
        this.d = new Vector();
    }

    public final NetworkConnection a(NetworkConfig networkConfig, int n, int n2, int n3, boolean bl, boolean bl2) {
        this.d(this.i + 1);
        NetworkConnection networkConnection = this.b();
        this.b().d = n;
        networkConnection.e = n2;
        networkConnection.f = n3;
        networkConnection.g = bl;
        networkConnection.h = bl2;
        networkConnection.b = networkConfig;
        return networkConnection;
    }

    public final void a() {
        if (this.c()) {
            throw new RuntimeException("Stack underflow");
        }
        this.d(this.i - 1);
    }

    private void d(int n) {
        if (n > this.i) {
            int n2;
            SessionData sessionData = this;
            if (n > 100) {
                throw new RuntimeException("Stack overflow");
            }
            int n3 = n2 = sessionData.h.length;
            while (n3 <= n) {
                n3 <<= 1;
            }
            if (n3 > n2) {
                NetworkConnection[] networkConnectionArray = new NetworkConnection[n3];
                System.arraycopy(sessionData.h, 0, networkConnectionArray, 0, n2);
                sessionData.h = networkConnectionArray;
            }
        } else {
            this.a(n, this.i - 1);
        }
        this.i = n;
    }

    private void a(int n, int n2) {
        while (n <= n2) {
            if (this.h[n] != null) {
                this.h[n].b = null;
            }
            ++n;
        }
    }

    public final void a(int n) {
        if (this.f < n) {
            int n2;
            SessionData sessionData = this;
            if (n > 1000) {
                throw new RuntimeException("Stack overflow");
            }
            int n3 = n2 = sessionData.e.length;
            while (n3 <= n) {
                n3 <<= 1;
            }
            if (n3 > n2) {
                Object[] objectArray = new Object[n3];
                System.arraycopy(sessionData.e, 0, objectArray, 0, n2);
                sessionData.e = objectArray;
            }
        } else {
            this.b(n, this.f - 1);
        }
        this.f = n;
    }

    public final void a(int n, int n2, int n3) {
        if (n3 > 0 && n != n2) {
            System.arraycopy(this.e, n, this.e, n2, n3);
        }
    }

    private void b(int n, int n2) {
        while (n <= n2) {
            this.e[n] = null;
            ++n;
        }
    }

    public final void b(int n) {
        int n2 = this.d.size();
        while (--n2 >= 0) {
            PropertyRef propertyRef = (PropertyRef)this.d.elementAt(n2);
            if (propertyRef.b < n) {
                return;
            }
            propertyRef.c = this.e[propertyRef.b];
            propertyRef.a = null;
            this.d.removeElementAt(n2);
        }
    }

    public final NetworkConnection b() {
        if (this.c()) {
            return null;
        }
        NetworkConnection networkConnection = this.h[this.i - 1];
        if (networkConnection == null) {
            this.h[this.i - 1] = networkConnection = new NetworkConnection(this);
        }
        return networkConnection;
    }

    public final NetworkConnection c(int n) {
        BillingClient.a(n >= 0, "Level must be non-negative");
        n = this.i - n - 1;
        BillingClient.a(n >= 0, "Level too high");
        return this.h[n];
    }

    public final boolean c() {
        return this.i == 0;
    }
}

