/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
package game;

import game.BattleScreen;
import game.Player;
import game.ScriptEngine;
import game.TitleScreen;
import game.WorldManager;
import java.io.InputStream;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;
import javax.microedition.media.Manager;
import javax.microedition.media.MediaException;
import javax.microedition.media.control.VolumeControl;
import org.recompile.mobile.PlatformGraphics;

public final class GameStateController
extends BaseScreen {
    private static GameStateController instance = null;
    private byte state;
    private byte previousState;
    private int k;
    private Image l;
    private BaseScreen activeScreen;
    private static int n = 0;
    private static int o = 10;
    private String[] p = new String[]{"H\u1ecfa h\u1ec7 kh\u1eafc m\u1ed9c h\u1ec7", "M\u1ed9c h\u1ec7 kh\u1eafc th\u1ed5 h\u1ec7", "Th\u1ed5 h\u1ec7 kh\u1eafc th\u1ee7y h\u1ec7", "Th\u1ee7y h\u1ec7 kh\u1eafc h\u1ecfa h\u1ec7", "Qu\u1ef7 h\u1ec7 kh\u1eafc phong h\u1ec7", "Phong h\u1ec7 kh\u1eafc \u0111i\u1ec7n h\u1ec7", "\u0110i\u1ec7n h\u1ec7 kh\u1eafc qu\u1ef7 h\u1ec7"};
    private String[] q = new String[]{"Thuy\u1ec1n c\u00e0ng \u0111i c\u00e0ng xa", "B\u01a1i... b\u01a1i...", "\u0110\u00edch \u0111\u1ebfn ng\u00e0y c\u00e0ng g\u1ea7n", "Thuy\u1ec1n nh\u1ecf \u0111ang ch\u1ea1y"};
    public long a = 0L;
    public long b = 0L;
    public long c = 0L;
    public long d = 0L;
    public long e = 0L;
    public long f = 0L;
    private boolean r = false;
    private String s = "";
    public byte g = 0;
    private javax.microedition.media.Player musicPlayer;
    private VolumeControl volumeControl;
    private static String v = null;

    public static GameStateController getInstance() {
        if (instance == null) {
            instance = new GameStateController();
            v = "0";
        }
        return instance;
    }

    public final void setInputEnabled(boolean bl) {
        if (bl) {
            this.c();
            return;
        }
        this.j();
    }

    public final void c() {
        this.f = System.currentTimeMillis();
        this.setScreenMode((byte)3);
        super.setInputEnabled(true);
    }

    private void j() {
        this.setScreenMode((byte)1);
        super.setInputEnabled(false);
    }

    public final void setScreenMode(byte by) {
        if (by >= 24) {
            return;
        }
        this.previousState = this.state;
        switch (this.state) {
            case 2: {
                break;
            }
            case 4: {
                break;
            }
            case 16: {
                break;
            }
            case 15: {
                break;
            }
            case 6: {
                break;
            }
            case 7:
            case 9:
            case 12:
            case 22:
            case 23: {
                n = 0;
                break;
            }
            case 10: {
                break;
            }
            case 8:
            case 11:
            case 13: {
                break;
            }
            case 3: {
                ScreenView.a().a = -1;
            }
        }
        this.state = by;
        switch (by) {
            case 3: {
                ScreenView.a().c(0, 19);
                break;
            }
            case 15: {
                this.l = EngineUtils.loadPng("/data/logo/", "0");
                break;
            }
            case 12:
            case 22: {
                GameStateController.resumeGame();
                n = 0;
                break;
            }
            case 23: {
                GameStateController.resumeGame();
                n = 0;
                by = (byte)EngineUtils.randomInt(this.q.length);
                this.s = this.q[by];
                break;
            }
            case 9: {
                GameStateController.resumeGame();
                n = 0;
                by = (byte)EngineUtils.randomInt(this.p.length);
                this.s = this.p[by];
                break;
            }
            case 11: {
                WorldManager.a().interactionController.g = true;
                break;
            }
            case 2: {
                if (WorldManager.a().c == null) break;
                WorldManager.a().c.J();
            }
        }
        this.k = 0;
    }

    public final byte getState() {
        return this.state;
    }

    public final void g() {
        if (this.state == 9 || this.state == 22 || this.state == 23) {
            this.n();
            this.r = true;
            this.resetInputState();
            return;
        }
        if (this.state != 2) {
            this.n();
            this.r = true;
            this.setScreenMode((byte)2);
            this.resetInputState();
        }
    }

    private void k() {
        this.a("0");
        this.setScreenMode(this.previousState);
        this.r = false;
        this.resetInputState();
    }

    public final boolean d() {
        this.s();
        this.interactionController = ScriptEngine.a();
        this.uiManager = UIManager.getInstance();
        this.interactionController.a(this);
        ImageCache.initialize();
        AnimationCache.initialize();
        GameDatabase.initialize();
        GameStateController.setKeyDelay(0);
        GameStateController.getSmallFont();
        WorldManager.a();
        WorldManager.i();
        GameStateController.t();
        return true;
    }

    public final void f() {
        if (this.activeScreen != null) {
            this.activeScreen.f();
            this.activeScreen = null;
        }
    }

    public final void b() {
        if (!this.inputEnabled) {
            return;
        }
        this.snapshotInput();
        switch (this.state) {
            case 3: {
                if (!GameStateController.isPaused()) {
                    this.d();
                }
                if (!ScreenView.a().b || !GameStateController.isPaused()) break;
                this.setScreenMode((byte)15);
                break;
            }
            case 2: {
                if (!this.isKeyPressed(262144)) break;
                this.k();
                break;
            }
            case 4: {
                if (this.isKeyPressed(131072)) {
                    this.j();
                    break;
                }
                if (!this.isKeyPressed(262144)) break;
                this.k();
                break;
            }
            case 16: {
                ++this.k;
                if (this.k < 10) break;
                this.l = null;
                this.setScreenMode((byte)6);
                break;
            }
            case 15: {
                ++this.k;
                if (this.k < 10) break;
                this.k = 0;
                this.l = null;
                this.l = EngineUtils.loadPng("/data/logo/", "cwalogo");
                this.setScreenMode((byte)16);
                break;
            }
            case 6: {
                if (this.isKeyPressed(131072)) {
                    this.g = (byte)2;
                    this.a(v);
                    this.setScreenMode((byte)7);
                    break;
                }
                if (!this.isKeyPressed(262144)) break;
                this.g = 0;
                this.setScreenMode((byte)7);
                break;
            }
            case 9:
            case 22:
            case 23: {
                this.f();
                this.activeScreen = WorldManager.a();
                this.activeScreen.d();
                Player.U = false;
                this.setScreenMode((byte)11);
                if (this.r) {
                    GameStateController gameStateController = this;
                    if (gameStateController.state != 2) {
                        gameStateController.setScreenMode((byte)2);
                    }
                }
                this.setInputDelegate(this.activeScreen);
                break;
            }
            case 10: {
                this.f();
                this.activeScreen = WorldManager.a();
                ((WorldManager)this.activeScreen).p();
                this.setInputDelegate(this.activeScreen);
                this.setScreenMode((byte)11);
                break;
            }
            case 7: {
                this.f();
                this.activeScreen = TitleScreen.a();
                this.activeScreen.d();
                this.setInputDelegate(this.activeScreen);
                this.setScreenMode((byte)8);
                break;
            }
            case 12: {
                if (!GameStateController.isPaused()) {
                    this.activeScreen = null;
                    this.activeScreen = BattleScreen.a();
                    this.activeScreen.d();
                    this.setInputDelegate(this.activeScreen);
                    if (((BattleScreen)this.activeScreen).b == 0) {
                        ScreenView.a().c(-2013265920, 6);
                    } else if (((BattleScreen)this.activeScreen).b == 2) {
                        ScreenView.a().c(-2013265920, 8);
                    } else if (((BattleScreen)this.activeScreen).b == 1) {
                        ScreenView.a().c(-2013265920, 7);
                    }
                }
                if (GameStateController.isPaused()) {
                    ScreenView.a().b();
                    Player.U = false;
                }
                if (!ScreenView.a().b) break;
                ((BattleScreen)this.activeScreen).g();
                this.setScreenMode((byte)13);
                break;
            }
            case 8:
            case 11:
            case 13:
            case 20: {
                if (this.activeScreen == null) break;
                this.activeScreen.b();
            }
        }
        if (WorldManager.a().f == 3 && WorldManager.a().g == 7 && this.c == 0L && this.a != 0L) {
            this.b = System.currentTimeMillis();
        }
        this.e = System.currentTimeMillis();
    }

    public final void b(Graphics object) {
        if (!this.inputEnabled) {
            return;
        }
        ((PlatformGraphics)object).setFont(GameStateController.getSmallFont());
        switch (this.state) {
            case 3: {
                ((PlatformGraphics)object).setColor(0xFFFFFF);
                ((PlatformGraphics)object).fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                ScreenView.a().a((Graphics)object);
                return;
            }
            case 2: {
                ((PlatformGraphics)object).setColor(0);
                ((PlatformGraphics)object).fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                ((PlatformGraphics)object).setColor(0xFFFFFF);
                ((PlatformGraphics)object).drawString("Tr\u00f2 ch\u01a1i t\u1ea1m d\u1eebng", GameStateController.getScreenWidth() >> 1, GameStateController.getHalfHeight(), 33);
                ((PlatformGraphics)object).drawString("Ph\u1ea3n h\u1ed3i", GameStateController.getScreenWidth() - 2, GameStateController.getScreenHeight() - 2, 40);
                return;
            }
            case 4: {
                return;
            }
            case 15: {
                ((PlatformGraphics)object).setColor(0xFFFFFF);
                ((PlatformGraphics)object).fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                ((PlatformGraphics)object).setColor(0xFFFFFF);
                ((PlatformGraphics)object).setFont(GameStateController.getSmallFont());
                if (this.l == null) break;
                ((PlatformGraphics)object).drawImage(this.l, GameStateController.getHalfWidth(), GameStateController.getHalfHeight(), 3);
                return;
            }
            case 16: {
                ((PlatformGraphics)object).setColor(GameStateController.getKeyDelay());
                ((PlatformGraphics)object).fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                if (this.l == null) break;
                ((PlatformGraphics)object).drawImage(this.l, (GameStateController.getScreenWidth() - this.l.getWidth()) / 2, (GameStateController.getScreenHeight() - this.l.getHeight()) / 2, 20);
                return;
            }
            case 6: {
                ((PlatformGraphics)object).setColor(0);
                ((PlatformGraphics)object).fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                ((PlatformGraphics)object).setFont(GameStateController.getSmallFont());
                ((PlatformGraphics)object).setColor(0xFFFFFF);
                ((PlatformGraphics)object).drawString(GameStateController.getString(8), GameStateController.getScreenWidth() >> 1, GameStateController.getHalfHeight() - 12, 17);
                ((PlatformGraphics)object).drawString(GameStateController.getString(4), 2, GameStateController.getScreenHeight() - 2, 36);
                ((PlatformGraphics)object).drawString(GameStateController.getString(5), GameStateController.getScreenWidth() - 2, GameStateController.getScreenHeight() - 2, 40);
                ((PlatformGraphics)object).setColor(16739328);
                ((PlatformGraphics)object).drawString(GameStateController.getString(9), GameStateController.getScreenWidth() >> 1, GameStateController.getHalfHeight() + 12, 17);
                return;
            }
            case 7: {
                return;
            }
            case 12: {
                WorldManager.a().b.a((Graphics)object);
                if (!GameStateController.isPaused()) break;
                ScreenView.a().a((Graphics)object);
                Player.U = false;
                return;
            }
            case 9: {
                Graphics graphics = object;
                object = this;
                if (Player.U) {
                    byte by;
                    graphics.setColor(0);
                    graphics.fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                    if (n % 4 == 3) {
                        Player.getInstance().setAnimation((byte)1, (byte)-1, false);
                    } else {
                        Player.getInstance().setAnimation((byte)(n % 4), (byte)-1, false);
                    }
                    Player.getInstance().facingDirection = by = (byte)(n % 4);
                    Player.getInstance().renderInWorld(graphics, MapEngine.getInstance().cameraX, MapEngine.getInstance().cameraY - n);
                } else {
                    graphics.setColor(0);
                    graphics.fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                }
                if (n < 148) {
                    n += o;
                }
                if (n > 148) {
                    n = 148;
                }
                if (!Player.U) {
                    graphics.setColor(0);
                    graphics.fillRect(45, GameStateController.getScreenHeight() - 48, 150, 5);
                    graphics.setColor(7877410);
                    graphics.fillRect(46, GameStateController.getScreenHeight() - 47, 148, 3);
                    graphics.setColor(16707204);
                    graphics.fillRect(46, GameStateController.getScreenHeight() - 47, n, 3);
                    graphics.setColor(0xFFFFFF);
                    graphics.drawString(((GameStateController)object).s, GameStateController.getScreenWidth() >> 1, GameStateController.getScreenHeight() - 70, 17);
                }
                return;
            }
            case 23: {
                Graphics graphics = object;
                object = this;
                graphics.setColor(0);
                graphics.fillRect(0, 0, GameStateController.getScreenWidth(), GameStateController.getScreenHeight());
                graphics.setColor(0xFFFFFF);
                graphics.drawString(((GameStateController)object).s, GameStateController.getScreenWidth() >> 1, GameStateController.getScreenHeight() >> 1, 17);
                return;
            }
            case 10: {
                return;
            }
            case 8:
            case 11:
            case 13:
            case 20: {
                if (this.activeScreen == null) break;
                this.activeScreen.b((Graphics)object);
            }
        }
    }

    private void a(String string) {
        v = string;
        if (this.g == 0) {
            return;
        }
        try {
            if (this.musicPlayer != null) {
                if (this.o()) {
                    this.musicPlayer.start();
                    return;
                }
            } else {
                GameStateController.getInstance().getClass();
                InputStream inputStream = ResourceStream.openResource("/data/sound/" + string + ".mid");
                this.musicPlayer = Manager.createPlayer(inputStream, "audio/midi");
                this.musicPlayer.realize();
                this.volumeControl = (VolumeControl)this.musicPlayer.getControl("VolumeControl");
                this.volumeControl.setLevel(this.g * 30);
                this.musicPlayer.prefetch();
                this.musicPlayer.setLoopCount(-1);
                this.musicPlayer.start();
                inputStream.close();
            }
            return;
        }
        catch (MediaException mediaException) {
            DebugLogger.a(mediaException, "startMusic");
            return;
        }
        catch (Exception exception) {
            DebugLogger.a(exception, "/data/sound" + string + ".mid");
            return;
        }
    }

    private void n() {
        if (this.musicPlayer == null) {
            return;
        }
        this.musicPlayer.deallocate();
        this.musicPlayer.close();
        this.musicPlayer = null;
    }

    private boolean o() {
        try {
            this.musicPlayer.prefetch();
            if (this.musicPlayer.getState() == 300) {
                return true;
            }
        }
        catch (Exception exception) {}
        return false;
    }

    private void p() {
        if (this.volumeControl != null) {
            this.volumeControl.setLevel(this.g * 30);
        }
    }

    public final void h() {
        this.g = (byte)(this.g + 1);
        if (this.g > 3) {
            this.g = (byte)3;
        }
        if (this.g > 0) {
            this.p();
            this.a(v);
        }
    }

    public final void i() {
        this.g = (byte)(this.g - 1);
        if (this.g < 0) {
            this.g = 0;
        }
        if (this.g == 0) {
            this.n();
            return;
        }
        this.p();
    }
}

