/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
package game;

import game.BattleScreen;
import game.GameStateController;
import game.NpcEntity;
import game.Pet;
import game.Player;
import game.TileMapRenderer;
import game.WorldManager;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.Vector;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

public final class OverworldScreen
extends BaseScreen {
    private static OverworldScreen v = null;
    private WorldManager w;
    private Player x;
    private BaseScreen y;
    public ScriptSequence[] a;
    private Vector z;
    private byte A = (byte)-1;
    public byte[][] b;
    private int B = 0;
    public int c = -1;
    private static Vector C;
    public static Vector d;
    private TileMapRenderer D = TileMapRenderer.a();
    public static boolean e;
    public static boolean f;
    public static boolean g;
    public static boolean h;
    public boolean i = true;
    public static boolean j;
    public boolean k = true;
    public byte l = 0;
    public static byte m;
    private short[] E;
    private byte[] F;
    private short[] G;
    private short[] H;
    private short[][] I;
    private short[][] J;
    private short[] K;
    private short[] L;
    public byte n = 0;
    public static Image o;
    private String[] M = new String[]{"ikon_1", "ikon_2", "ikon_3", "ikon_4", "ikon_5"};
    private int N;
    private int O;
    private int Z = 0;
    private int aa = 0;
    private byte[] ab;
    private String[] ac;
    private int[] ad;
    private int[] ae;
    private String[] af = null;
    private WorldEntity ag = null;
    private int ah = -1;
    private Calendar ai = null;
    private int[] aj;
    public byte p = 0;
    public static String[] q;
    public static String[] r;
    public static short[][] s;
    public static byte t;
    public static byte u;
    private static byte[][] ak;
    private static byte[][] al;

    public OverworldScreen() {
        if (this.w == null) {
            this.w = WorldManager.a();
        }
        if (this.x == null) {
            this.x = Player.getInstance();
        }
        if (this.b == null) {
            this.b = new byte[127][];
        }
        if (s == null) {
            s = new short[200][2];
        }
        if (this.ai == null) {
            this.ai = Calendar.getInstance(TimeZone.getDefault());
        }
        try {
            int n;
            Object object = EngineUtils.readStringRows(EngineUtils.openResource("/data/script/bTask.mid"));
            q = new String[((String[][])object).length];
            for (n = 0; n < ((String[][])object).length; ++n) {
                System.arraycopy(object[n], 0, q, n, object[n].length);
            }
            object = EngineUtils.readStringRows(EngineUtils.openResource("/data/script/mTask.mid"));
            r = new String[((String[][])object).length];
            for (n = 0; n < ((String[][])object).length; ++n) {
                System.arraycopy(object[n], 0, r, n, object[n].length);
            }
            object = EngineUtils.openResource("/data/script/bqTask.mid");
            ak = EngineUtils.readByteRows((InputStream)object);
            al = EngineUtils.readByteRows((InputStream)object);
            ((InputStream)object).close();
            return;
        }
        catch (IOException iOException) {
            iOException.printStackTrace();
            return;
        }
    }

    public static OverworldScreen a() {
        if (v == null) {
            v = new OverworldScreen();
        }
        return v;
    }

    public final void a(BaseScreen baseScreen) {
        if (this.y != null) {
            this.y = null;
        }
        this.y = baseScreen;
    }

    /*
     * Unable to fully structure code
     * Could not resolve type clashes
     */
    public final void b() {
        if (this.a == null) {
            return;
        }
        ScreenView.a().b();
        this.D.d();
        var1_1 = this;
        for (var2_2 = 0; var2_2 < var1_1.a.length; ++var2_2) {
            if (var1_1.a[var2_2].getState() != 0 && var1_1.a[var2_2].getState() != 4) continue;
            var3_3 = var1_1.a[var2_2].getFirstCommand();
            var4_5 = false;
            switch (var3_3.getOpcode()) {
                case 43: {
                    if (WorldManager.a((int)var3_3.getNumericArguments()[2], var3_3.getNumericArguments()[3]) != WorldManager.a(var1_1.w.f, var1_1.w.g) || var3_3.getNumericArguments()[4] != WorldManager.u || !var1_1.a((ScriptCommand)var3_3)) break;
                    OverworldScreen.g = true;
                    if (!OverworldScreen.h || var1_1.a(-1) != -1) break;
                    var6_7 = var2_2;
                    var5_6 = var1_1;
                    for (var7_12 = 0; var7_12 < var5_6.a.length; ++var7_12) {
                        if (var5_6.a[var7_12].getState() == 3 || var6_7 == var7_12 || (var8_13 = var5_6.a[var7_12].getFirstCommand()).getOpcode() != 43 || WorldManager.a((int)var8_13.getNumericArguments()[2], var8_13.getNumericArguments()[3]) != WorldManager.a(var5_6.w.f, var5_6.w.g) || var8_13.getNumericArguments()[4] != WorldManager.u || !super.a(var8_13)) continue;
                        v0 = (byte)var7_12;
                        ** GOTO lbl22
                    }
                    v0 = -1;
lbl22:
                    // 2 sources

                    if (var2_2 < v0) break;
                    var4_5 = true;
                    OverworldScreen.g = false;
                    var1_1.x.b((byte)0, var1_1.x.facingDirection);
                    if (var3_3.getNumericArguments()[1] != 1) break;
                    OverworldScreen.s[OverworldScreen.u][0] = var3_3.getNumericArguments()[0];
                    break;
                }
                case 44: {
                    if (WorldManager.a((int)var3_3.getNumericArguments()[2], var3_3.getNumericArguments()[3]) != WorldManager.a(var1_1.w.f, var1_1.w.g) || var3_3.getNumericArguments()[4] != WorldManager.u || !var1_1.b((ScriptCommand)var3_3)) break;
                    OverworldScreen.g = true;
                    if (!OverworldScreen.h || var2_2 < var1_1.a(var2_2)) break;
                    var1_1.x.b((byte)0, var1_1.x.facingDirection);
                    OverworldScreen.g = false;
                    ** GOTO lbl109
                }
                case 13: {
                    if (!EngineUtils.a(var3_3.getNumericArguments()[0], (int)var3_3.getNumericArguments()[1], (int)var3_3.getNumericArguments()[2], (int)var3_3.getNumericArguments()[3], var1_1.x.posX, var1_1.x.posY, var1_1.x.spriteRenderer.k())) break;
                    var1_1.x.b((byte)0, var1_1.x.facingDirection);
                    ** GOTO lbl109
                }
                case 15: {
                    if (var1_1.b[WorldManager.a((int)var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1])] == null || var1_1.b[WorldManager.a((int)var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1])][var3_3.getNumericArguments()[2]] != 3 && var1_1.b[WorldManager.a((int)var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1])][var3_3.getNumericArguments()[2]] != 4) break;
                    var4_5 = true;
                    break;
                }
                case 16: {
                    if (var3_3.getNumericArguments()[0] != WorldManager.u) break;
                    OverworldScreen.g = true;
                    if (!OverworldScreen.h) break;
                    var1_1.x.b((byte)0, var1_1.x.facingDirection);
                    OverworldScreen.h = false;
                    ** GOTO lbl109
                }
                case 69: {
                    if (var3_3.getNumericArguments()[0] != WorldManager.u) break;
                    ** GOTO lbl109
                }
                case 57: {
                    if (var1_1.x.ownerEntity == null || ((NpcEntity)var1_1.x.ownerEntity).t != 0 || ((NpcEntity)var1_1.x.ownerEntity).v != 11 || ((NpcEntity)var1_1.x.ownerEntity).I != var3_3.getNumericArguments()[3] || !OverworldScreen.h) break;
                    if (var1_1.w.d[var3_3.getNumericArguments()[0]].posX == var3_3.getNumericArguments()[1] && var1_1.w.d[var3_3.getNumericArguments()[0]].posY == var3_3.getNumericArguments()[2]) {
                        ((NpcEntity)var1_1.x.ownerEntity).d((byte)0);
                    } else {
                        var4_5 = true;
                    }
                    OverworldScreen.h = false;
                    break;
                }
                case 59: {
                    var5_6 = new int[EngineUtils.a(var3_3.getTextArguments()[0], ',').length];
                    for (var6_8 = 0; var6_8 < ((byte[])var5_6).length; ++var6_8) {
                        var5_6[var6_8] = EngineUtils.b(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var6_8]);
                        if (var1_1.w.d[var5_6[var6_8]].getActionState() == 0) break;
                    }
                    if (var6_8 < ((byte[])var5_6).length) break;
                    var4_5 = true;
                    break;
                }
                case 61: {
                    var5_6 = new int[EngineUtils.a(var3_3.getTextArguments()[0], ',').length];
                    for (var6_9 = 0; var6_9 < ((byte[])var5_6).length; ++var6_9) {
                        var5_6[var6_9] = EngineUtils.b(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var6_9]);
                        if (var1_1.w.d[var5_6[var6_9]].getActionState() == 0) break;
                    }
                    if (var6_9 < ((byte[])var5_6).length) break;
                    var1_1.x.b((byte)0, var1_1.x.facingDirection);
                    var4_5 = true;
                    break;
                }
                case 73: {
                    var5_6 = EngineUtils.a(var3_3.getTextArguments()[1], ',');
                    var6_10 = EngineUtils.a(var3_3.getTextArguments()[0], ',');
                    for (var3_4 = 0; var3_4 < ((byte[])var5_6).length && var1_1.x.a(EngineUtils.d(var6_10[var3_4]), (int)EngineUtils.d((String)var5_6[var3_4])) >= 2; ++var3_4) {
                    }
                    if (var3_4 < ((byte[])var5_6).length) break;
                    var4_5 = true;
                    break;
                }
                case 75: {
                    if (var1_1.x.L.size() <= 0) break;
                    ** GOTO lbl109
                }
                case 78: {
                    var5_6 = EngineUtils.e(var3_3.getTextArguments()[0]);
                    var6_11 = EngineUtils.e(var3_3.getTextArguments()[1]);
                    var3_3 = EngineUtils.e(var3_3.getTextArguments()[2]);
                    for (var7_12 = 0; var7_12 < ((Object)var3_3).length && var1_1.b[WorldManager.a((int)var5_6[var7_12], var6_11[var7_12])] != null && (var1_1.b[WorldManager.a((int)var5_6[var7_12], var6_11[var7_12])][var3_3[var7_12]] == 3 || var1_1.b[WorldManager.a((int)var5_6[var7_12], var6_11[var7_12])][var3_3[var7_12]] == 4); ++var7_12) {
                    }
                    if (var7_12 < ((Object)var3_3).length) break;
                    var4_5 = true;
                    break;
                }
                case 79: {
                    if (var1_1.b[WorldManager.a((int)var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1])] == null || var1_1.b[WorldManager.a((int)var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1])][var3_3.getNumericArguments()[2]] != 3 || var1_1.x.k(0) || WorldManager.u != var3_3.getNumericArguments()[3]) break;
                    OverworldScreen.g = true;
                    if (!OverworldScreen.h) break;
                    OverworldScreen.h = false;
                    ** GOTO lbl109
                }
                case 86: {
                    if (var1_1.b[WorldManager.a((int)var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1])] == null || var1_1.b[WorldManager.a((int)var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1])][var3_3.getNumericArguments()[2]] != 3) break;
                }
lbl109:
                // 8 sources

                default: {
                    var4_5 = true;
                }
            }
            if (!var4_5) continue;
            var1_1.A = (byte)var2_2;
            var1_1.a[var2_2].setCommandIndex((byte)0);
            var1_1.z.addElement(var1_1.a[var2_2]);
            var1_1.a[var2_2].setState((byte)1);
        }
        this.n();
    }

    public static void a(Graphics graphics) {
        int n;
        if (C != null) {
            for (n = 0; n < C.size(); ++n) {
                WorldEntity worldEntity = (WorldEntity)C.elementAt(n);
                worldEntity.setPosition(worldEntity.ownerEntity.posX, worldEntity.ownerEntity.posY - 40);
                worldEntity.renderInWorld(graphics, MapEngine.getInstance().cameraX, MapEngine.getInstance().cameraY);
            }
        }
        if (d != null) {
            for (n = 0; n < d.size(); ++n) {
                ((WorldEntity)d.elementAt(n)).renderInWorld(graphics, MapEngine.getInstance().cameraX, MapEngine.getInstance().cameraY);
            }
        }
    }

    public final void c() {
        int n;
        if (C != null) {
            for (n = 0; n < C.size(); ++n) {
                WorldEntity worldEntity = (WorldEntity)C.elementAt(n);
                worldEntity.advanceAnimationIfVisible();
                if (!worldEntity.spriteRenderer.isLastAnimationStep()) continue;
                worldEntity.deactivate();
                C.removeElementAt(n);
                --n;
            }
        }
        if (d != null) {
            for (n = 0; n < d.size(); ++n) {
                ((WorldEntity)d.elementAt(n)).advanceAnimationIfVisible();
            }
        }
        if (this.ag != null) {
            this.ag.advanceAnimationIfVisible();
        }
    }

    public final void b(Graphics graphics) {
        ScreenView.a().a(graphics);
        Graphics graphics2 = graphics;
        OverworldScreen overworldScreen = this;
        if (overworldScreen.ag != null && overworldScreen.ah == WorldManager.a(overworldScreen.w.f, overworldScreen.w.g)) {
            overworldScreen.ag.renderInWorld(graphics2, MapEngine.getInstance().cameraX, MapEngine.getInstance().cameraY);
        }
        this.D.a(graphics);
    }

    public final boolean d() {
        return true;
    }

    public final boolean a(DataInputStream dataInputStream, int n, int n2, int n3, String[] stringArray) {
        try {
            this.a = new ScriptSequence[n3];
            this.z = new Vector();
            C = new Vector();
            int n4 = n << 8 | n2;
            if (this.b[WorldManager.l[n] + n2] == null) {
                this.b[WorldManager.l[n] + n2] = new byte[n3];
            }
            for (byte by = 0; by < n3; by = (byte)(by + 1)) {
                this.a[by] = new ScriptSequence();
                this.a[by].read(dataInputStream, by, n4, stringArray);
                this.a[by].setState(this.b[WorldManager.l[n] + n2][by]);
            }
        }
        catch (IOException iOException) {
            System.out.println(" ex = " + iOException.toString() + " event init ");
        }
        this.i();
        return false;
    }

    public final void e() {
        this.x = null;
        this.w = null;
        this.b = null;
        s = null;
        this.ai = null;
        v = null;
    }

    public final void f() {
        if (C != null) {
            C.removeAllElements();
            C = null;
        }
        if (d != null) {
            d.removeAllElements();
            d = null;
        }
        this.a = null;
        this.E = null;
        this.F = null;
        this.G = null;
        this.H = null;
        this.I = null;
        this.J = null;
        this.K = null;
        this.L = null;
        this.ab = null;
        this.ac = null;
    }

    public final void setScreenMode(byte by) {
    }

    private byte a(int n) {
        for (int i = 0; i < this.a.length; ++i) {
            ScriptCommand scriptCommand;
            if (this.a[i].getState() == 3 || n == i || (scriptCommand = this.a[i].getFirstCommand()).getOpcode() != 44 || WorldManager.a((int)scriptCommand.getNumericArguments()[2], scriptCommand.getNumericArguments()[3]) != WorldManager.a(this.w.f, this.w.g) || scriptCommand.getNumericArguments()[4] != WorldManager.u || !this.b(scriptCommand)) continue;
            return (byte)i;
        }
        return -1;
    }

    private static void b(int n) {
        for (int i = 0; i < u; ++i) {
            if (s[i][0] != n) continue;
            OverworldScreen.s[i][1] = 3;
            return;
        }
    }

    private static int c(int n) {
        for (int i = 0; i < u; ++i) {
            if (s[i][0] != n) continue;
            return i;
        }
        return -1;
    }

    /*
     * Unable to fully structure code
     */
    private void n() {
        var1_1 = 0;
        while (var1_1 < this.z.size()) {
            var2_2 = (ScriptSequence)this.z.elementAt(var1_1);
            var3_3 = var2_2.getCurrentCommand();
            switch (var3_3.getOpcode()) {
                case 0: {
                    break;
                }
                case 1: {
                    if (var2_2.getState() != 5) {
                        ScreenView.a().c(0, 9);
                        this.D.a(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]);
                        this.D.a((byte)(var3_3.getNumericArguments()[0] / 10 - 1), var3_3.getTextArguments()[0], var3_3.getNumericArguments()[0] % 10);
                        this.D.a(true);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!TileMapRenderer.a || !this.y.isKeyPressed(1)) break;
                    this.D.b();
                    if (TileMapRenderer.b) break;
                    ScreenView.a().a = -1;
                    this.D.c();
                    ** GOTO lbl1044
                }
                case 2: {
                    if (var3_3.getNumericArguments()[0] == -1) {
                        this.x.activate();
                        this.x.b((byte)0, EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[0]));
                        break;
                    }
                    for (var4_4 = 0; var4_4 < var3_3.getNumericArguments()[0]; ++var4_4) {
                        this.w.d[EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var4_4])].setFacingDirection(EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var4_4]));
                        if (this.w.d[EngineUtils.c((String)EngineUtils.a((String)var3_3.getTextArguments()[0], (char)',')[var4_4])].v == 1) {
                            this.w.d[EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var4_4])].d((byte)0);
                        }
                        this.w.d[EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var4_4])].activate();
                    }
                    break;
                }
                case 3: {
                    if (var3_3.getNumericArguments()[0] == -1) {
                        this.x.deactivate();
                        break;
                    }
                    for (var5_29 = 0; var5_29 < var3_3.getNumericArguments()[0]; ++var5_29) {
                        var4_5 = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var5_29]);
                        this.w.d[var4_5].deactivate();
                    }
                    break;
                }
                case 4: {
                    if (var2_2.getState() != 5) {
                        this.x.b((byte)0, this.x.facingDirection);
                        this.w.interactionController.a(var3_3.getTextArguments()[0], var3_3.getTextArguments()[1], (int)var3_3.getNumericArguments()[1]);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.w.interactionController.c(var3_3.getNumericArguments()[1], -1) || !this.y.isKeyPressed(196640)) break;
                    WorldManager.a().e();
                    if (EngineUtils.b < EngineUtils.b()) {
                        EngineUtils.c();
                        this.w.interactionController.b(EngineUtils.b);
                        break;
                    }
                    if (WorldManager.u != -1 && this.w.d[WorldManager.u].spriteRenderer.spriteId <= 85 && this.w.d[WorldManager.u].u() == 0) {
                        WorldManager.a().a(WorldManager.a().d[WorldManager.u].posX, WorldManager.a().d[WorldManager.u].posY - 40, WorldManager.a().d[WorldManager.u]);
                    }
                    OverworldScreen.g = false;
                    OverworldScreen.h = false;
                    this.w.interactionController.aC();
                    var2_2.setState((byte)1);
                    break;
                }
                case 5: {
                    var4_6 = new WorldEntity();
                    var4_6.loadSprite(259, false);
                    var4_6.setAnimation((byte)var3_3.getNumericArguments()[2], (byte)-1, true);
                    if (var3_3.getNumericArguments()[0] == 0) {
                        var4_6.setPosition(this.x.getPosX(), this.x.getPosY() - this.x.spriteRenderer.getFrameBounds(this.x.getActionState(), this.x.facingDirection)[3]);
                        var4_6.setOwnerEntity(this.x);
                    } else if (var3_3.getNumericArguments()[0] == 1) {
                        if (var3_3.getNumericArguments()[3] != 0 || var3_3.getNumericArguments()[4] != 0) {
                            var4_6.setPosition(var3_3.getNumericArguments()[3], var3_3.getNumericArguments()[4]);
                        } else {
                            var4_6.setPosition(this.w.d[var3_3.getNumericArguments()[1]].getPosX(), this.w.d[var3_3.getNumericArguments()[1]].getPosY());
                            var4_6.setOwnerEntity(this.w.d[var3_3.getNumericArguments()[1]]);
                        }
                    }
                    var4_6.activate();
                    OverworldScreen.C.addElement(var4_6);
                    break;
                }
                case 6: {
                    this.b[WorldManager.l[this.w.f] + this.w.g][var2_2.getEventId()] = 3;
                    WorldManager.a().f = var3_3.getNumericArguments()[0];
                    WorldManager.a().g = var3_3.getNumericArguments()[1];
                    this.w.j = var3_3.getNumericArguments()[3] == 1 ? var3_3.getNumericArguments()[2] : -1;
                    GameStateController.getInstance().setScreenMode((byte)22);
                    break;
                }
                case 7: {
                    if (var2_2.getState() != 5) {
                        this.E = new short[var3_3.getNumericArguments()[0]];
                        for (var4_7 = 0; var4_7 < this.E.length; ++var4_7) {
                            this.E[var4_7] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var4_7]);
                            var5_30 = EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[2], ',')[var4_7]);
                            if (this.E[var4_7] == -1) {
                                this.x.b(EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[0]), var5_30);
                                continue;
                            }
                            this.w.d[this.E[var4_7]].setFacingDirection(var5_30);
                            this.w.d[this.E[var4_7]].d(EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var4_7]));
                        }
                        this.B = 0;
                        var2_2.setState((byte)5);
                        break;
                    }
                    for (var4_8 = 0; var4_8 < this.E.length; ++var4_8) {
                        if (this.E[var4_8] == -1) {
                            if (!this.x.isLastAnimationStep()) continue;
                            this.x.b((byte)0, this.x.facingDirection);
                            ++this.B;
                            continue;
                        }
                        if (!this.w.d[this.E[var4_8]].isLastAnimationStep()) continue;
                        this.w.d[this.E[var4_8]].d((byte)0);
                        ++this.B;
                    }
                    if (this.B < this.E.length) break;
                    this.B = 0;
                    ** GOTO lbl1044
                }
                case 8: {
                    this.x.activate();
                    WorldManager.u = (short)-1;
                    this.x.setPosition(var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1]);
                    this.x.targetEntity.setPosition(var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1]);
                    this.x.b((byte)0, this.x.facingDirection);
                    break;
                }
                case 9: {
                    if (var2_2.getState() != 5) {
                        var4_9 = false;
                        if (var3_3.getNumericArguments()[0] == 12 || var3_3.getNumericArguments()[0] == 13) {
                            ScreenView.a().c(0, var3_3.getNumericArguments()[0]);
                            ScreenView.a().a(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], var3_3.getNumericArguments()[3], var3_3.getNumericArguments()[4], var3_3.getNumericArguments()[5]);
                        } else if (var3_3.getNumericArguments()[0] == 10) {
                            ScreenView.a().c(0, var3_3.getNumericArguments()[0]);
                            ScreenView.a().d(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]);
                        } else if (var3_3.getNumericArguments()[0] == 15 || var3_3.getNumericArguments()[0] == 14) {
                            ScreenView.a().c(0, var3_3.getNumericArguments()[0]);
                            ScreenView.a().a(this.M[var3_3.getNumericArguments()[1]], (int)var3_3.getNumericArguments()[2], (int)var3_3.getNumericArguments()[3], (int)var3_3.getNumericArguments()[4]);
                        } else if (var3_3.getNumericArguments()[0] == 16) {
                            if (var3_3.getNumericArguments()[1] == 0) {
                                var5_31 = new String[]{"star0", "star1", "star2", "star3"};
                                ScreenView.a().a(16, (byte)var3_3.getNumericArguments()[2], (byte)7, var5_31);
                            } else if (var3_3.getNumericArguments()[1] == 1) {
                                var5_32 = new String[]{"fire0", "fire1", "fire2"};
                                ScreenView.a().a(16, (byte)var3_3.getNumericArguments()[2], (byte)0, var5_32);
                            } else if (var3_3.getNumericArguments()[1] == 2) {
                                var5_33 = new String[]{"fire0", "fire1", "fire2"};
                                ScreenView.a().a(17, (byte)var3_3.getNumericArguments()[2], (byte)0, var5_33);
                            } else {
                                var4_9 = true;
                                ScreenView.a().a(-1, (byte)var3_3.getNumericArguments()[2], (byte)0, null);
                                var2_2.setState((byte)1);
                            }
                        } else if (var3_3.getNumericArguments()[0] == 17) {
                            ScreenView.a().c(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[0]);
                            ScreenView.a().a((int)var3_3.getNumericArguments()[2], (int)var3_3.getNumericArguments()[3], (int)var3_3.getNumericArguments()[4], (int)var3_3.getNumericArguments()[5]);
                        } else {
                            var5_34 = var3_3.getNumericArguments()[1] << 24 | var3_3.getNumericArguments()[2] << 16 | var3_3.getNumericArguments()[3] << 8 | var3_3.getNumericArguments()[4];
                            ScreenView.a().c(var5_34, var3_3.getNumericArguments()[0]);
                        }
                        if (var4_9) break;
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (ScreenView.a().c && (var3_3.getNumericArguments()[0] == 12 || var3_3.getNumericArguments()[0] == 13)) {
                        var2_2.setState((byte)1);
                        break;
                    }
                    if (var3_3.getNumericArguments()[0] != 16 && !ScreenView.a().b) break;
                    ** GOTO lbl1044
                }
                case 10: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[0] == -1) {
                            this.F = new byte[1];
                            this.x.setFacingDirection(EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[0]));
                            this.x.b((byte)0, this.x.facingDirection);
                            this.x.setCurrentStat((byte)0, EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[2], ',')[0]));
                            this.F[0] = EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[3], ',')[0]);
                        } else {
                            this.E = new short[var3_3.getNumericArguments()[0]];
                            this.F = new byte[var3_3.getNumericArguments()[0]];
                            for (var4_10 = 0; var4_10 < this.E.length; ++var4_10) {
                                this.E[var4_10] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var4_10]);
                                if (this.E[var4_10] != -1) {
                                    this.w.d[this.E[var4_10]].setFacingDirection(EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var4_10]));
                                    this.w.d[this.E[var4_10]].setCurrentStat((byte)0, EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[2], ',')[var4_10]));
                                    this.w.d[this.E[var4_10]].d((byte)0);
                                } else {
                                    this.x.setFacingDirection(EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var4_10]));
                                    this.x.setCurrentStat((byte)0, EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[2], ',')[var4_10]));
                                    this.x.b((byte)0, this.x.facingDirection);
                                }
                                this.F[var4_10] = EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[3], ',')[var4_10]);
                            }
                        }
                        this.B = 0;
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (var3_3.getNumericArguments()[0] == -1) {
                        if (this.x.getActionState() == 0) {
                            this.x.b((byte)1, this.x.facingDirection);
                            break;
                        }
                        this.F[0] = (byte)(this.F[0] - 1);
                        if (this.F[0] > 0) break;
                        this.x.b((byte)0, this.x.facingDirection);
                        if (this.x.P[0] == 2 || this.x.P[1] == 2) {
                            this.x.setCurrentStat((byte)0, (short)8);
                        } else {
                            this.x.setCurrentStat((byte)0, (short)4);
                        }
                        var2_2.setState((byte)1);
                        break;
                    }
                    for (var4_11 = 0; var4_11 < this.E.length; ++var4_11) {
                        if (this.E[var4_11] != -1 && this.w.d[this.E[var4_11]].getActionState() == 0 || this.E[var4_11] == -1 && this.x.getActionState() == 0) {
                            if (this.F[var4_11] <= 0) continue;
                            if (this.E[var4_11] != -1) {
                                this.w.d[this.E[var4_11]].d((byte)3);
                                continue;
                            }
                            this.x.b((byte)1, this.x.facingDirection);
                            continue;
                        }
                        v0 = var4_11;
                        this.F[v0] = (byte)(this.F[v0] - 1);
                        if (this.F[var4_11] > 0) continue;
                        ++this.B;
                        this.F[var4_11] = 0;
                        if (this.E[var4_11] != -1) {
                            this.w.d[this.E[var4_11]].d((byte)0);
                            this.w.d[this.E[var4_11]].setCurrentStat((byte)0, (short)4);
                            continue;
                        }
                        this.x.b((byte)0, this.x.facingDirection);
                        if (this.x.P[0] == 2 || this.x.P[1] == 2) {
                            this.x.setCurrentStat((byte)0, (short)8);
                            continue;
                        }
                        this.x.setCurrentStat((byte)0, (short)4);
                    }
                    if (this.B < this.E.length) break;
                    ** GOTO lbl1044
                }
                case 11: {
                    if (var2_2.getState() != 5) {
                        var4_12 = false;
                        if (var3_3.getNumericArguments()[6] == 0) {
                            var4_12 = true;
                        }
                        ParticleEffect.a().a(var3_3.getNumericArguments()[7]);
                        if (var3_3.getNumericArguments()[2] == 1) {
                            v1 = ParticleEffect.a();
                            v2 = var3_3.getNumericArguments()[4];
                            v3 = var3_3.getNumericArguments()[5];
                            var3_3.getNumericArguments();
                            var3_3.getNumericArguments();
                            v1.a(v2, v3, var4_12);
                        } else if (var3_3.getNumericArguments()[2] == 0) {
                            if (var3_3.getNumericArguments()[3] == -1) {
                                v4 = ParticleEffect.a();
                                var3_3.getNumericArguments();
                                var3_3.getNumericArguments();
                                v4.a(this.x, var4_12);
                            } else {
                                v5 = ParticleEffect.a();
                                v6 = this.w.d[var3_3.getNumericArguments()[3]];
                                var3_3.getNumericArguments();
                                var3_3.getNumericArguments();
                                v5.a(v6, var4_12);
                            }
                        }
                        this.x.b((byte)0, this.x.facingDirection);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!ParticleEffect.a().c()) break;
                    ** GOTO lbl1044
                }
                case 12: {
                    ++this.B;
                    if (var2_2.getState() != 5) {
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (this.B < var3_3.getNumericArguments()[0]) break;
                    this.B = 0;
                    ** GOTO lbl1044
                }
                case 13: {
                    if (EngineUtils.a(var3_3.getNumericArguments()[0], (int)var3_3.getNumericArguments()[1], (int)var3_3.getNumericArguments()[2], (int)var3_3.getNumericArguments()[3], this.x.posX, this.x.posY, this.x.spriteRenderer.k())) {
                        var2_2.setState((byte)1);
                        this.x.b((byte)0, this.x.facingDirection);
                        break;
                    }
                    var2_2.setState((byte)6);
                    break;
                }
                case 14: {
                    var2_2.setState((byte)3);
                    break;
                }
                case 16: {
                    if (var3_3.getNumericArguments()[0] == WorldManager.u) {
                        OverworldScreen.g = true;
                        if (!OverworldScreen.h) break;
                        OverworldScreen.h = false;
                        var2_2.setState((byte)2);
                        break;
                    }
                    var2_2.setState((byte)6);
                    break;
                }
                case 17: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[0] == 0) {
                            if (this.x.a(var3_3.getNumericArguments()[1], (int)var3_3.getNumericArguments()[2], (byte)0)) {
                                var4_13 = GameDatabase.gameDatabase[4][var3_3.getNumericArguments()[1]][0];
                                this.y.interactionController.a("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + BaseScreen.getString(var4_13), (int)var3_3.getNumericArguments()[2]);
                                this.x.c(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], (byte)0);
                            } else {
                                this.y.interactionController.b("Ba l\u00f4 \u0111\u00e3 \u0111\u1ee7 \u0111\u1ea1o c\u1ee5 n\u00e0y");
                            }
                        } else if (this.x.b((int)var3_3.getNumericArguments()[1], (int)var3_3.getNumericArguments()[2], (byte)0)) {
                            var4_14 = GameDatabase.gameDatabase[4][var3_3.getNumericArguments()[1]][0];
                            this.y.interactionController.a("M\u1ea5t: " + BaseScreen.getString(var4_14), (int)var3_3.getNumericArguments()[2]);
                            this.x.d(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], (byte)0);
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ax()) break;
                    ** GOTO lbl1044
                }
                case 18: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[0] == 0) {
                            if (this.x.a(var3_3.getNumericArguments()[1], (int)var3_3.getNumericArguments()[2], (byte)2)) {
                                var4_15 = GameDatabase.gameDatabase[3][var3_3.getNumericArguments()[1]][0];
                                this.y.interactionController.a("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + BaseScreen.getString(var4_15), (int)var3_3.getNumericArguments()[2]);
                                this.x.c(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], (byte)2);
                            } else {
                                this.y.interactionController.b("Ba l\u00f4 \u0111\u00e3 \u0111\u1ee7 \u0111\u1ea1o c\u1ee5 n\u00e0y");
                            }
                        } else if (var3_3.getNumericArguments()[0] == 1) {
                            var4_16 = GameDatabase.gameDatabase[3][var3_3.getNumericArguments()[1]][0];
                            this.y.interactionController.a("M\u1ea5t: " + BaseScreen.getString(var4_16), (int)var3_3.getNumericArguments()[2]);
                            this.x.d(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], (byte)2);
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ax()) break;
                    ** GOTO lbl1044
                }
                case 19: {
                    if (var2_2.getState() != 5) {
                        var4_17 = GameDatabase.gameDatabase[5][var3_3.getNumericArguments()[0]][0];
                        this.y.interactionController.a("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + BaseScreen.getString(var4_17), (int)var3_3.getNumericArguments()[1]);
                        var5_35 = this.x.d(var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1]);
                        if (var5_35 != -1) {
                            if (var5_35 == 1) {
                                this.y.interactionController.b("Ba l\u00f4 \u0111\u00e3 \u0111\u1ee7 lo\u1ea1i \u0111\u1ea1o c\u1ee5 n\u00e0y");
                            } else {
                                this.x.c(var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1]);
                            }
                        } else if (var3_3.getNumericArguments()[0] == 0) {
                            this.x.e(var3_3.getNumericArguments()[0], -1);
                        } else {
                            this.x.i(var3_3.getNumericArguments()[0]);
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ax()) break;
                    ** GOTO lbl1044
                }
                case 20: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[0] == 1) {
                            this.y.interactionController.b("M\u1ea5t: " + var3_3.getTextArguments()[0]);
                            this.x.T[var3_3.getNumericArguments()[1]] = false;
                        } else {
                            this.y.interactionController.b("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + var3_3.getTextArguments()[0]);
                            this.x.T[var3_3.getNumericArguments()[1]] = true;
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ax()) break;
                    ** GOTO lbl1044
                }
                case 21: {
                    WorldManager.x = false;
                    WorldManager.y = var3_3.getNumericArguments()[2];
                    if (var3_3.getNumericArguments()[1] != 1) break;
                    WorldManager.z = var3_3.getNumericArguments()[3];
                    WorldManager.A = var3_3.getNumericArguments()[4];
                    WorldManager.B = var3_3.getNumericArguments()[5];
                    WorldManager.C = var3_3.getNumericArguments()[6];
                    break;
                }
                case 22: {
                    WorldManager.x = true;
                    WorldManager.w = (byte)var3_3.getNumericArguments()[1];
                    WorldManager.a().h = var3_3.getNumericArguments()[2];
                    WorldManager.a().i = var3_3.getNumericArguments()[3];
                    WorldManager.B = var3_3.getNumericArguments()[4];
                    WorldManager.C = var3_3.getNumericArguments()[5];
                    WorldManager.a().j = -1;
                    break;
                }
                case 23: {
                    this.b[WorldManager.a((int)var3_3.getNumericArguments()[0], (int)var3_3.getNumericArguments()[1])][var3_3.getNumericArguments()[2]] = 3;
                    if (var3_3.getNumericArguments()[0] != this.w.f || var3_3.getNumericArguments()[1] != this.w.g) break;
                    this.a[var3_3.getNumericArguments()[2]].setState((byte)3);
                    if (this.z.size() <= 0) break;
                    this.z.removeElement(this.a[var3_3.getNumericArguments()[2]]);
                    --var1_1;
                    break;
                }
                case 24: {
                    if (var2_2.getState() != 5) {
                        ScreenView.a().c(0, 11);
                        ScreenView.a().a(var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!ScreenView.a().b) break;
                    ** GOTO lbl1044
                }
                case 25: {
                    OverworldScreen.f = var3_3.getNumericArguments()[0] == 0;
                    break;
                }
                case 29: {
                    if (var2_2.getState() != 5) {
                        var4_18 = var3_3.getNumericArguments()[0];
                        if (var3_3.getNumericArguments()[0] == -1) {
                            var4_18 = 1;
                        }
                        this.E = new short[var4_18];
                        this.K = new short[var4_18];
                        this.L = new short[var4_18];
                        this.G = new short[var4_18];
                        this.H = new short[var4_18];
                        for (var5_36 = 0; var5_36 < this.E.length; ++var5_36) {
                            this.E[var5_36] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var5_36]);
                            this.K[var5_36] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var5_36]);
                            this.L[var5_36] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[2], ',')[var5_36]);
                            this.G[var5_36] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[3], ',')[var5_36]);
                            this.H[var5_36] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[4], ',')[var5_36]);
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    var4_19 = true;
                    for (var7_59 = 0; var7_59 < this.E.length; ++var7_59) {
                        if (this.G[var7_59] <= 0 && this.H[var7_59] <= 0) continue;
                        var4_19 = false;
                        v7 = var7_59;
                        this.G[v7] = (short)(this.G[v7] - 1);
                        v8 = var7_59;
                        this.H[v8] = (short)(this.H[v8] - 1);
                        if (var3_3.getNumericArguments()[0] == -1) {
                            var5_37 = this.x.getPosX() + this.K[var7_59];
                            var6_44 = this.x.getPosY() + this.L[var7_59];
                            this.x.setPosition(var5_37, var6_44);
                            if (this.x.targetEntity == null) continue;
                            this.x.targetEntity.setPosition(var5_37, var6_44);
                            continue;
                        }
                        var5_37 = this.w.d[this.E[var7_59]].getPosX() + this.K[var7_59];
                        var6_44 = this.w.d[this.E[var7_59]].getPosY() + this.L[var7_59];
                        this.w.d[this.E[var7_59]].setPosition(var5_37, var6_44);
                        if (this.w.d[this.E[var7_59]].targetEntity == null) continue;
                        this.w.d[this.E[var7_59]].targetEntity.setPosition(var5_37, var6_44);
                    }
                    if (!var4_19) break;
                    var2_2.setState((byte)1);
                    break;
                }
                case 30: {
                    if (var2_2.getState() != 5) {
                        this.E = new short[var3_3.getNumericArguments()[0]];
                        var4_20 = EngineUtils.a(var3_3.getTextArguments()[2], ',');
                        for (var5_38 = 0; var5_38 < this.E.length; ++var5_38) {
                            this.E[var5_38] = EngineUtils.c(var4_20[var5_38]);
                        }
                        var5_39 = new String[this.E.length][];
                        var6_45 = new String[this.E.length][];
                        for (var7_60 = 0; var7_60 < var6_45.length; ++var7_60) {
                            var5_39[var7_60] = EngineUtils.a(EngineUtils.a(var3_3.getTextArguments()[0], '#')[var7_60], ',');
                            var6_45[var7_60] = EngineUtils.a(EngineUtils.a(var3_3.getTextArguments()[1], '#')[var7_60], ',');
                        }
                        this.I = new short[this.E.length][];
                        this.J = new short[this.E.length][];
                        for (var7_60 = 0; var7_60 < this.E.length; ++var7_60) {
                            this.I[var7_60] = new short[var5_39[var7_60].length];
                            this.J[var7_60] = new short[var6_45[var7_60].length];
                            for (var8_68 = 0; var8_68 < this.I[var7_60].length; ++var8_68) {
                                this.I[var7_60][var8_68] = EngineUtils.c(var5_39[var7_60][var8_68]);
                                this.J[var7_60][var8_68] = EngineUtils.c(var6_45[var7_60][var8_68]);
                            }
                        }
                        this.B = 0;
                        var2_2.setState((byte)5);
                        break;
                    }
                    for (var4_21 = 0; var4_21 < this.E.length; ++var4_21) {
                        this.w.d[this.E[var4_21]].setPosition(this.I[var4_21][this.B], this.J[var4_21][this.B]);
                    }
                    ++this.B;
                    if (this.B < this.I[0].length) break;
                    ** GOTO lbl1044
                }
                case 31: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[0] == 0) {
                            if (var3_3.getNumericArguments()[1] == 0) {
                                this.x.addGold(var3_3.getNumericArguments()[2]);
                                this.y.interactionController.b("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + var3_3.getNumericArguments()[2] + " kim ti\u1ec1n");
                            } else if (var3_3.getNumericArguments()[1] == 1) {
                                this.x.addArenaPoints(var3_3.getNumericArguments()[2]);
                                this.y.interactionController.b("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + var3_3.getNumericArguments()[2] + "Huy hi\u1ec7u");
                            }
                        } else if (var3_3.getNumericArguments()[0] == 1) {
                            if (var3_3.getNumericArguments()[1] == 0) {
                                this.x.addGold(-var3_3.getNumericArguments()[2]);
                                this.y.interactionController.b("M\u1ea5t: " + var3_3.getNumericArguments()[2] + " kim ti\u1ec1n");
                            } else if (var3_3.getNumericArguments()[1] == 1) {
                                this.x.addArenaPoints(-var3_3.getNumericArguments()[2]);
                                this.y.interactionController.b("M\u1ea5t: " + var3_3.getNumericArguments()[2] + " huy hi\u1ec7u");
                            }
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.w.interactionController.ax()) break;
                    ** GOTO lbl1044
                }
                case 32: {
                    this.w.e();
                    BattleScreen.a().a = var3_3.getNumericArguments()[0];
                    BattleScreen.a().b = (byte)var3_3.getNumericArguments()[1];
                    BattleScreen.a().c = Image.createImage(BaseScreen.getScreenWidth(), BaseScreen.getScreenHeight());
                    var4_22 = BattleScreen.a().c.getGraphics();
                    this.w.b.b(var4_22);
                    this.x.b((byte)0, this.x.facingDirection);
                    var2_2.setState((byte)1);
                    GameStateController.getInstance().setScreenMode((byte)12);
                    break;
                }
                case 33: {
                    break;
                }
                case 34: {
                    if (var2_2.getState() != 5) {
                        var3_3.getNumericArguments();
                        this.N = var3_3.getNumericArguments()[2];
                        this.O = var3_3.getNumericArguments()[3];
                        this.B = var3_3.getNumericArguments()[4];
                        var2_2.setState((byte)5);
                        break;
                    }
                    --this.B;
                    this.N -= this.O;
                    if (this.B > 0) break;
                    this.B = 0;
                    ** GOTO lbl1044
                }
                case 35: {
                    if (var2_2.getState() != 5) {
                        this.Z = var3_3.getNumericArguments()[0];
                        this.aa = var3_3.getNumericArguments()[1];
                        this.ac = EngineUtils.a(var3_3.getTextArguments()[0], ',');
                        this.ab = new byte[EngineUtils.a(var3_3.getTextArguments()[1], ',').length];
                        var5_40 = var3_3.getTextArguments()[2];
                        for (var6_46 = 0; var6_46 < this.ab.length; ++var6_46) {
                            this.ab[var6_46] = EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var6_46]);
                        }
                        this.y.interactionController.a(this.aa, this.Z, this.ac, var5_40);
                        var2_2.setState((byte)5);
                        break;
                    }
                    var5_41 = this.y.interactionController.c(this.aa);
                    if (var5_41 == -1) break;
                    var2_2.setCommandIndex((byte)(this.ab[var5_41] - 2));
                    var2_2.setState((byte)1);
                    break;
                }
                case 36: {
                    if (var2_2.getState() != 5) {
                        var5_42 = this.x.y();
                        if (var3_3.getNumericArguments()[0] == 0) {
                            if (var5_42 == 0) {
                                this.x.a(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], (byte)var3_3.getNumericArguments()[4], (byte)var3_3.getNumericArguments()[3], new int[]{1, var3_3.getNumericArguments()[5], var3_3.getNumericArguments()[6]});
                            } else if (var5_42 == 1) {
                                this.y.interactionController.b("Ba l\u00f4 \u0111\u00e3 \u0111\u1ee7, \u0111\u00e3 \u0111\u1ec3 v\u00e0o ng\u00e2n h\u00e0ng");
                                var6_47 = Pet.b(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], var3_3.getNumericArguments()[3]);
                                this.x.a(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], (byte)var3_3.getNumericArguments()[4], (byte)var3_3.getNumericArguments()[3], var6_47, 0, new int[]{1, var3_3.getNumericArguments()[5], var3_3.getNumericArguments()[6]});
                            } else {
                                this.y.interactionController.b("Kh\u00f4ng c\u00f3 kh\u00f4ng gian, \u0111\u00e3 ph\u00f3ng sinh");
                            }
                        } else if (var3_3.getNumericArguments()[0] == 1) {
                            this.x.n(var3_3.getNumericArguments()[1]);
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ax()) break;
                    ** GOTO lbl1044
                }
                case 37: {
                    BattleScreen.a().a(new int[][]{{var3_3.getNumericArguments()[0], var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]}});
                    break;
                }
                case 38: {
                    OverworldScreen.g = false;
                    for (var6_48 = 0; var6_48 < EngineUtils.a(var3_3.getTextArguments()[0], ',').length; ++var6_48) {
                        if (EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var6_48]) != WorldManager.u) continue;
                        OverworldScreen.g = true;
                        if (!OverworldScreen.h) break;
                        WorldManager.u = (short)-1;
                        var5_43 = EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var6_48]);
                        var2_2.setCommandIndex((byte)(var5_43 - 1));
                        WorldManager.a().e();
                        OverworldScreen.g = false;
                        OverworldScreen.h = false;
                        break;
                    }
                    var2_2.setState((byte)6);
                    break;
                }
                case 39: {
                    for (var6_49 = 0; var6_49 < this.x.partyPetCount; ++var6_49) {
                        this.x.petParty[var6_49].I();
                    }
                    break;
                }
                case 40: {
                    if (var2_2.getState() != 5) {
                        this.y.interactionController.c(var3_3.getTextArguments()[0]);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ay()) break;
                    ** GOTO lbl1044
                }
                case 41: {
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[0] - 2));
                    break;
                }
                case 42: {
                    var2_2.setState((byte)4);
                    break;
                }
                case 45: {
                    if (var2_2.getState() != 5) {
                        this.y.interactionController.c(var3_3.getTextArguments()[0]);
                        OverworldScreen.t = (byte)var3_3.getNumericArguments()[0];
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ay()) break;
                    ** GOTO lbl1044
                }
                case 46: {
                    if (var2_2.getState() != 5) {
                        this.y.interactionController.H();
                        this.y.interactionController.a(var3_3.getTextArguments()[0]);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (this.y.interactionController.f == 0) {
                        if (this.y.isKeyPressed(196640)) {
                            this.y.interactionController.f = 1;
                            this.y.interactionController.a("\u0110ang l\u01b0u...");
                            this.y.interactionController.J();
                            break;
                        }
                        if (!this.y.isKeyPressed(262144)) break;
                        var2_2.setState((byte)1);
                        this.y.interactionController.I();
                        this.y.interactionController.f = 0;
                        break;
                    }
                    if (this.y.interactionController.f == 1) {
                        this.b[WorldManager.a((int)this.w.f, (int)this.w.g)][var2_2.getEventId()] = 3;
                        if (!((WorldManager)this.y).k()) break;
                        this.y.interactionController.a("L\u01b0u th\u00e0nh c\u00f4ng");
                        this.y.interactionController.f = 2;
                        break;
                    }
                    if (this.y.interactionController.f != 2) break;
                    this.y.interactionController.I();
                    this.y.interactionController.f = 0;
                    ** GOTO lbl1044
                }
                case 47: {
                    if (this.l == -1) break;
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[this.l] - 2));
                    break;
                }
                case 48: {
                    if (var2_2.getState() != 5) {
                        this.D.a(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]);
                        this.D.a((byte)(var3_3.getNumericArguments()[0] / 10 - 1), var3_3.getTextArguments()[0], var3_3.getNumericArguments()[0] % 10);
                        if (var3_3.getNumericArguments()[5] == 1) {
                            this.D.a(true);
                        }
                        this.D.b(var3_3.getNumericArguments()[3], var3_3.getNumericArguments()[4]);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.D.e()) ** GOTO lbl663
                    if (!TileMapRenderer.a || !this.y.isKeyPressed(1)) break;
                    this.D.b();
                    if (TileMapRenderer.b) break;
                    ScreenView.a().a = -1;
                    this.D.c();
                    ** GOTO lbl1044
lbl663:
                    // 1 sources

                    var2_2.setState((byte)1);
                    break;
                }
                case 49: {
                    if (var2_2.getState() != 5) {
                        this.ad = new int[2];
                        this.ae = new int[2];
                        this.af = new String[2];
                        this.ac = new String[2];
                        for (var6_50 = 0; var6_50 < 2; ++var6_50) {
                            this.ad[var6_50] = var3_3.getNumericArguments()[var6_50 << 1];
                            this.ae[var6_50] = var3_3.getNumericArguments()[(var6_50 << 1) + 1];
                            this.af[var6_50] = var3_3.getTextArguments()[var6_50];
                        }
                        this.ab = new byte[EngineUtils.a(var3_3.getTextArguments()[2], ',').length];
                        for (var6_50 = 0; var6_50 < this.ab.length; ++var6_50) {
                            this.ab[var6_50] = EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[2], ',')[var6_50]);
                            this.ac[var6_50] = EngineUtils.a(var3_3.getTextArguments()[3], ',')[var6_50];
                        }
                        this.y.interactionController.a(this.ad, this.ae, this.af, this.ac);
                        var2_2.setState((byte)5);
                        break;
                    }
                    var6_51 = this.y.interactionController.aD();
                    if (var6_51 == -1) break;
                    if (var6_51 == 0 && var2_2.getFirstCommand().getNumericArguments()[1] == 1) {
                        OverworldScreen.s[OverworldScreen.u][1] = 1;
                        OverworldScreen.u = (byte)(OverworldScreen.u + 1);
                    }
                    var2_2.setCommandIndex((byte)(this.ab[var6_51] - 2));
                    var2_2.setState((byte)1);
                    break;
                }
                case 50: {
                    if (var3_3.getNumericArguments()[0] == 0) {
                        this.x.u();
                        break;
                    }
                    this.x.t();
                    break;
                }
                case 51: {
                    this.w.interactionController.aB();
                    this.D.a(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]);
                    this.D.a((byte)(var3_3.getNumericArguments()[0] / 10 - 1), var3_3.getTextArguments()[0], var3_3.getNumericArguments()[0] % 10);
                    this.D.b(var3_3.getNumericArguments()[3], var3_3.getNumericArguments()[4]);
                    break;
                }
                case 52: {
                    this.i = var3_3.getNumericArguments()[0] == 0;
                    if (var3_3.getNumericArguments()[1] == 0) {
                        OverworldScreen.j = true;
                        break;
                    }
                    OverworldScreen.j = false;
                    break;
                }
                case 53: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[1] == 0) {
                            this.x.a((byte)var3_3.getNumericArguments()[0], (byte)var3_3.getNumericArguments()[1], (byte)2);
                            for (var6_52 = 0; var6_52 < WorldManager.a().d.length; ++var6_52) {
                                if (WorldManager.a().d[var6_52].t != 0 || WorldManager.a().d[var6_52].v != 1) continue;
                                WorldManager.a().d[var6_52].v();
                            }
                        } else if (var3_3.getNumericArguments()[1] == 1) {
                            this.x.a((byte)var3_3.getNumericArguments()[0], (byte)var3_3.getNumericArguments()[1], (byte)1);
                        }
                        this.y.interactionController.a(var3_3.getNumericArguments()[0]);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.w.isKeyPressed(1)) break;
                    this.y.interactionController.V();
                    ** GOTO lbl1044
                }
                case 54: {
                    var6_53 = var3_3.getNumericArguments()[0];
                    var7_61 = new int[var6_53][3];
                    for (var8_69 = 0; var8_69 < var6_53; ++var8_69) {
                        var7_61[var8_69][0] = EngineUtils.b(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var8_69]);
                        var7_61[var8_69][1] = EngineUtils.b(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var8_69]);
                        var7_61[var8_69][2] = EngineUtils.b(EngineUtils.a(var3_3.getTextArguments()[2], ',')[var8_69]);
                    }
                    BattleScreen.a().a(var7_61);
                    break;
                }
                case 55: {
                    if (var3_3.getNumericArguments()[0] == 0) {
                        if (this.ag == null) {
                            this.ag = new WorldEntity();
                            this.ag.loadSprite(340, false);
                            this.ag.activate();
                            this.ah = WorldManager.a((int)var3_3.getNumericArguments()[3], var3_3.getNumericArguments()[4]);
                        }
                        this.ag.setPosition(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]);
                        break;
                    }
                    if (var3_3.getNumericArguments()[0] != 1 || this.ag == null) break;
                    this.ag.deactivate();
                    this.ag = null;
                    this.ah = -1;
                    break;
                }
                case 56: {
                    var6_54 = var3_3.getNumericArguments()[1];
                    if (var3_3.getNumericArguments()[0] == 0) {
                        for (var7_62 = 0; var7_62 < var6_54; ++var7_62) {
                            var8_70 = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var7_62]);
                            var4_23 = EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var7_62]);
                            this.w.d[var8_70].setFacingDirection(var4_23);
                            if (this.w.d[var8_70].v == 1) {
                                this.w.d[var8_70].d((byte)0);
                            }
                            this.w.d[var8_70].activate();
                            this.w.a(var8_70, 1, (byte)1, true);
                            this.w.a(var8_70, 2, var4_23, true);
                            this.w.d[var8_70].r();
                        }
                    } else {
                        if (var3_3.getNumericArguments()[0] != 1) break;
                        for (var7_63 = 0; var7_63 < var6_54; ++var7_63) {
                            var8_71 = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var7_63]);
                            if (this.w.d[var8_71].v == 1) {
                                this.w.d[var8_71].d((byte)0);
                            }
                            this.w.d[var8_71].deactivate();
                            this.w.a(var8_71, 1, (byte)0, true);
                            this.w.d[var8_71].r();
                        }
                    }
                    break;
                }
                case 58: {
                    if (((NpcEntity)this.x.ownerEntity).getActionState() != 1 || !((NpcEntity)this.x.ownerEntity).spriteRenderer.isLastAnimationStep()) break;
                    ((NpcEntity)this.x.ownerEntity).d((byte)0);
                    this.w.d[var3_3.getNumericArguments()[0]].setPosition(var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2]);
                    if ((NpcEntity)this.w.d[var3_3.getNumericArguments()[0]].ownerEntity == null) break;
                    ((NpcEntity)this.w.d[var3_3.getNumericArguments()[0]].ownerEntity).q();
                    this.w.d[var3_3.getNumericArguments()[0]].setOwnerEntity(null);
                    break;
                }
                case 60: {
                    if (var2_2.getState() != 5) {
                        this.E = new short[var3_3.getNumericArguments()[0]];
                        for (var6_55 = 0; var6_55 < this.E.length; ++var6_55) {
                            this.E[var6_55] = EngineUtils.c(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var6_55]);
                            this.w.d[this.E[var6_55]].d(EngineUtils.d(EngineUtils.a(var3_3.getTextArguments()[1], ',')[var6_55]));
                            if (this.w.d[this.E[var6_55]].t != 0 || this.w.d[this.E[var6_55]].v != 6 || this.w.d[this.E[var6_55]].getActionState() != 2) continue;
                            WorldManager.a().b.c(WorldManager.a().d[this.E[var6_55]]);
                        }
                        this.B = 0;
                        var2_2.setState((byte)5);
                        break;
                    }
                    for (var6_56 = 0; var6_56 < this.E.length; ++var6_56) {
                        if (!this.w.d[this.E[var6_56]].isLastAnimationStep()) continue;
                        ++this.B;
                    }
                    if (this.B < this.E.length) break;
                    this.B = 0;
                    ** GOTO lbl1044
                }
                case 62: {
                    var6_57 = new int[EngineUtils.a(var3_3.getTextArguments()[0], ',').length];
                    var8_72 = -1;
                    var2_2.setState((byte)6);
                    for (var7_64 = 0; var7_64 < var6_57.length; ++var7_64) {
                        var6_57[var7_64] = EngineUtils.b(EngineUtils.a(var3_3.getTextArguments()[0], ',')[var7_64]);
                        if (this.w.d[var6_57[var7_64]].getActionState() != 2) continue;
                        var8_72 = var6_57[var7_64];
                        break;
                    }
                    if (var8_72 < 0) break;
                    if (var8_72 == var3_3.getNumericArguments()[0]) ** GOTO lbl818
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[2] - 2));
                    ** GOTO lbl1044
lbl818:
                    // 1 sources

                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[1] - 2));
                    var2_2.setState((byte)1);
                    break;
                }
                case 63: {
                    if (var3_3.getNumericArguments()[0] == 0) {
                        this.x.h(var3_3.getNumericArguments()[1]);
                    } else {
                        this.x.s();
                    }
                    this.k = var3_3.getNumericArguments()[2] != 0;
                    break;
                }
                case 64: {
                    if (var3_3.getNumericArguments()[0] == 0) {
                        this.w.a(var3_3.getNumericArguments()[1]);
                        if (var3_3.getNumericArguments()[2] == -1) {
                            this.w.a((WorldEntity)this.x);
                            break;
                        }
                        this.w.a(this.w.d[var3_3.getNumericArguments()[2]]);
                        break;
                    }
                    this.w.g();
                    break;
                }
                case 65: {
                    if (var2_2.getState() != 5 && !OverworldScreen.isVipUnlocked) {
                        this.y.setScreenMode((byte)100);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (OverworldScreen.isVipUnlocked) {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[0] - 2));
                    } else {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[1] - 2));
                    }
                    ** GOTO lbl1044
                }
                case 66: {
                    BaseScreen.U = (byte)var3_3.getNumericArguments()[0];
                    BaseScreen.c(0, 3);
                    break;
                }
                case 67: {
                    WorldManager.v = var3_3.getNumericArguments()[0];
                    break;
                }
                case 70: {
                    if (var2_2.getState() != 5) {
                        OverworldScreen.e = false;
                        this.c = var3_3.getNumericArguments()[0];
                        switch (var3_3.getNumericArguments()[0]) {
                            case 0:
                            case 1: {
                                this.w.setScreenMode((byte)1);
                                break;
                            }
                            case 2: {
                                this.w.setScreenMode((byte)16);
                            }
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!OverworldScreen.e) break;
                    this.c = -1;
                    ** GOTO lbl1044
                }
                case 71: {
                    if (this.x.F >= var3_3.getNumericArguments()[0]) {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[1] - 2));
                        break;
                    }
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[2] - 2));
                    break;
                }
                case 72: {
                    var6_58 = EngineUtils.a(var3_3.getTextArguments()[0], ',');
                    var7_65 = EngineUtils.a(var3_3.getTextArguments()[1], ',');
                    var8_73 = new WorldEntity[var6_58.length];
                    for (var4_24 = 0; var4_24 < var6_58.length; ++var4_24) {
                        var8_73[var4_24] = new WorldEntity();
                        var8_73[var4_24].loadSprite(259, false);
                        if (EngineUtils.b(var6_58[var4_24]) == -1) {
                            var8_73[var4_24].setAnimation(EngineUtils.d(var7_65[var4_24]), (byte)-1, true);
                            var8_73[var4_24].activate();
                            var8_73[var4_24].setPosition(this.x.getPosX(), this.x.getPosY() - 40);
                            var8_73[var4_24].setOwnerEntity(this.x);
                        } else {
                            var8_73[var4_24].setAnimation(EngineUtils.d(var7_65[var4_24]), (byte)-1, true);
                            var8_73[var4_24].activate();
                            var8_73[var4_24].setPosition(this.w.d[EngineUtils.b(var6_58[var4_24])].getPosX(), this.w.d[EngineUtils.b(var6_58[var4_24])].getPosY() - 40);
                            var8_73[var4_24].setOwnerEntity(this.w.d[EngineUtils.b(var6_58[var4_24])]);
                        }
                        OverworldScreen.C.addElement(var8_73[var4_24]);
                    }
                    break;
                }
                case 74: {
                    if (((int[])this.x.K.elementAt(0))[1] > 0) {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[0] - 2));
                        break;
                    }
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[1] - 2));
                    break;
                }
                case 76: {
                    this.b[WorldManager.l[this.w.f] + this.w.g][var2_2.getEventId()] = 3;
                    WorldManager.a().f = var3_3.getNumericArguments()[0];
                    WorldManager.a().g = var3_3.getNumericArguments()[1];
                    WorldManager.a().j = -1;
                    this.w.setScreenMode((byte)29);
                    break;
                }
                case 77: {
                    this.b[WorldManager.a((int)var3_3.getNumericArguments()[0], (int)var3_3.getNumericArguments()[1])][var3_3.getNumericArguments()[2]] = 4;
                    if (var3_3.getNumericArguments()[0] != this.w.f || var3_3.getNumericArguments()[1] != this.w.g) break;
                    this.a[var3_3.getNumericArguments()[2]].setState((byte)4);
                    break;
                }
                case 80: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[0] == 0) {
                            this.B = 0;
                            this.n = (byte)4;
                        } else if (var3_3.getNumericArguments()[0] == 1) {
                            GameStateController.getInstance().c = GameStateController.getInstance().b;
                            var7_66 = GameStateController.getInstance().c - GameStateController.getInstance().a;
                            if (EngineUtils.a(var7_66)[2] <= 70L) {
                                var4_25 = this.x.y();
                                if (var4_25 == 0) {
                                    this.y.interactionController.b("\u0110\u1ea1t \u0111\u01b0\u1ee3c #2L\u1ee5c h\u00e0nh \u0111i\u1ec3u");
                                    this.x.a(54, 5, (byte)2, (short)-1, new int[]{1, 30, 45});
                                } else if (var4_25 == 1) {
                                    this.y.interactionController.b("\u0110\u1ea1t \u0111\u01b0\u1ee3c #2L\u1ee5c h\u00e0nh \u0111i\u1ec3u#0 ba l\u00f4 \u0111\u00e3 \u0111\u1ee7, \u0111\u00e3 \u0111\u1ec3 v\u00e0o ng\u00e2n h\u00e0ng");
                                    var4_25 = EngineUtils.randomRange(GameDatabase.gameDatabase[0][54][3], GameDatabase.gameDatabase[0][54][3]);
                                    this.x.a(54, 5, (byte)2, (byte)var4_25, 0, 0, new int[]{1, 30, 45});
                                } else {
                                    this.y.interactionController.b("Kh\u00f4ng c\u00f3 kh\u00f4ng gian, \u0111\u00e3 ph\u00f3ng sinh");
                                }
                            } else if (EngineUtils.a(var7_66)[2] <= 80L) {
                                this.x.addGold(1000);
                                this.y.interactionController.b("Th\u01b0\u1edfng 1000 kim");
                            } else if (EngineUtils.a(var7_66)[2] <= 130L) {
                                this.x.addGold(750);
                                this.y.interactionController.b("Th\u01b0\u1edfng 750 kim");
                            } else if (EngineUtils.a(var7_66)[2] <= 200L) {
                                this.x.addGold(600);
                                this.y.interactionController.b("Th\u01b0\u1edfng 600 kim");
                            }
                            GameStateController.getInstance().b = 0L;
                            GameStateController.getInstance().a = 0L;
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (var3_3.getNumericArguments()[0] == 0) {
                        ++this.B;
                        if (this.n > 0) {
                            if (this.B / 10 == 0 || this.B % 10 != 0) break;
                            this.n = (byte)(this.n - 1);
                            break;
                        }
                        this.n = 0;
                        GameStateController.getInstance().b = GameStateController.getInstance().a = System.currentTimeMillis();
                        GameStateController.getInstance().c = 0L;
                    } else {
                        if (var3_3.getNumericArguments()[0] != 1 || !this.y.interactionController.ax()) break;
                        if (this.p == 0) {
                            this.aj = this.j();
                        }
                        this.p = (byte)(this.p + 1);
                    }
                    ** GOTO lbl1044
                }
                case 81: {
                    if (var3_3.getNumericArguments()[0] == 0) {
                        if (this.x.hasGold(var3_3.getNumericArguments()[1])) {
                            var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[2] - 2));
                            break;
                        }
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[3] - 2));
                        break;
                    }
                    if (var3_3.getNumericArguments()[0] != 1) break;
                    if (this.x.hasArenaPoints(var3_3.getNumericArguments()[1])) {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[2] - 2));
                        break;
                    }
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[3] - 2));
                    break;
                }
                case 82: {
                    var7_67 = var3_3.getNumericArguments()[0];
                    var8_74 = EngineUtils.e(var3_3.getTextArguments()[0]);
                    for (var4_26 = 0; var4_26 < var7_67; ++var4_26) {
                        this.w.d[var8_74[var4_26]].r();
                        this.w.d[var8_74[var4_26]].s();
                    }
                    break;
                }
                case 83: {
                    if (var2_2.getState() != 5) {
                        this.y.setScreenMode((byte)30);
                        var2_2.setState((byte)5);
                        break;
                    }
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[OverworldScreen.m] - 2));
                    ** GOTO lbl1044
                }
                case 84: {
                    if (var2_2.getState() != 5) {
                        var4_27 = null;
                        if (var3_3.getNumericArguments()[2] == 1) {
                            var4_27 = new int[]{this.p, 5 - this.p};
                        } else if (var3_3.getNumericArguments()[2] == 0) {
                            var4_27 = new int[]{this.x.I, this.x.quickItemSlots.length - this.x.I};
                        }
                        var4_27 = OverworldScreen.a(var3_3.getTextArguments()[1], var4_27);
                        this.w.interactionController.a(var3_3.getTextArguments()[0], (String)var4_27, (int)var3_3.getNumericArguments()[1]);
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.w.interactionController.c(var3_3.getNumericArguments()[1], -1) || !this.y.isKeyPressed(196640)) break;
                    WorldManager.a().e();
                    if (EngineUtils.b < EngineUtils.b()) {
                        EngineUtils.c();
                        this.w.interactionController.b(EngineUtils.b);
                        break;
                    }
                    if (WorldManager.u != -1 && this.w.d[WorldManager.u].spriteRenderer.spriteId <= 85 && this.w.d[WorldManager.u].u() == 0) {
                        WorldManager.a().a(WorldManager.a().d[WorldManager.u].posX, WorldManager.a().d[WorldManager.u].posY - 40, WorldManager.a().d[WorldManager.u]);
                    }
                    OverworldScreen.g = false;
                    OverworldScreen.h = false;
                    this.w.interactionController.aC();
                    var2_2.setState((byte)1);
                    break;
                }
                case 85: {
                    if (this.p >= 0 && this.p < 5) {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[0] - 2));
                        break;
                    }
                    var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[1] - 2));
                    break;
                }
                case 87: {
                    if (var2_2.getState() != 5) {
                        if (var3_3.getNumericArguments()[0] == 0) {
                            this.x.a(var3_3.getNumericArguments()[7], var3_3.getNumericArguments()[1], var3_3.getNumericArguments()[2], (byte)var3_3.getNumericArguments()[4], (byte)var3_3.getNumericArguments()[3], new int[]{1, var3_3.getNumericArguments()[5], var3_3.getNumericArguments()[6]});
                        } else if (var3_3.getNumericArguments()[0] == 1) {
                            this.x.n(var3_3.getNumericArguments()[1]);
                        }
                        var2_2.setState((byte)5);
                        break;
                    }
                    if (!this.y.interactionController.ax()) break;
                    ** GOTO lbl1044
                }
                case 88: {
                    if (this.x.y() == 2) {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[0] - 2));
                    } else {
                        var2_2.setCommandIndex((byte)(var3_3.getNumericArguments()[1] - 2));
                    }
lbl1044:
                    // 31 sources

                    var2_2.setState((byte)1);
                }
            }
            if (var2_2.getState() != 5 && var2_2.getState() != 6) {
                var2_2.advance();
            }
            if (var2_2.getState() == 3 || var2_2.getState() == 4) {
                OverworldScreen.h = false;
                this.z.removeElement(var2_2);
                var4_28 = WorldManager.a(var2_2.getSourceRoom()[0], var2_2.getSourceRoom()[1]);
                if (this.b[var4_28] != null) {
                    this.b[var4_28][var2_2.getEventId()] = var2_2.getState();
                }
                if (var2_2.getState() == 3 && var2_2.getFirstCommand().getOpcode() == 44 && var2_2.getFirstCommand().getNumericArguments()[1] == 1) {
                    OverworldScreen.b(var2_2.getFirstCommand().getNumericArguments()[0]);
                }
                this.i();
                continue;
            }
            ++var1_1;
        }
    }

    public final byte g() {
        return this.A;
    }

    public final boolean h() {
        if (this.a == null) {
            return false;
        }
        for (int i = 0; i < this.z.size(); ++i) {
            ScriptSequence scriptSequence = (ScriptSequence)this.z.elementAt(i);
            if (scriptSequence.getState() == 2 || scriptSequence.getState() == 6) continue;
            return true;
        }
        return false;
    }

    /*
     * Enabled aggressive block sorting
     */
    private boolean a(ScriptCommand scriptCommand) {
        boolean bl = false;
        if (scriptCommand.getNumericArguments()[7] != -1) {
            if (scriptCommand.getNumericArguments()[7] == -1) return bl;
            if (this.b[WorldManager.a((int)scriptCommand.getNumericArguments()[5], scriptCommand.getNumericArguments()[6])] == null) return bl;
            if (this.b[WorldManager.a((int)scriptCommand.getNumericArguments()[5], scriptCommand.getNumericArguments()[6])][scriptCommand.getNumericArguments()[7]] != 3) return bl;
        }
        switch (scriptCommand.getNumericArguments()[8]) {
            case 0: {
                if (!this.x.T[scriptCommand.getNumericArguments()[9]]) return bl;
                break;
            }
            case 1: {
                return true;
            }
            case 2: {
                int n;
                if (this.x.O.size() + this.x.partyPetCount < scriptCommand.getNumericArguments()[9]) return bl;
                for (n = 0; n < this.x.partyPetCount; ++n) {
                    if (this.x.petParty[n].getLevel() != scriptCommand.getNumericArguments()[10]) continue;
                    bl = true;
                    break;
                }
                if (bl) return bl;
                n = 0;
                while (n < this.x.O.size()) {
                    if (((int[])this.x.O.elementAt(n))[1] == scriptCommand.getNumericArguments()[10]) return true;
                    ++n;
                }
                return bl;
            }
            case 3: {
                if (this.x.F < scriptCommand.getNumericArguments()[9]) return bl;
                break;
            }
            case 4: {
                if (this.x.a((byte)scriptCommand.getNumericArguments()[9], scriptCommand.getNumericArguments()[10]) != 2) return bl;
                break;
            }
            case 5: {
                if (t <= scriptCommand.getNumericArguments()[9]) return bl;
                break;
            }
            case 6: {
                if (t != scriptCommand.getNumericArguments()[9]) return bl;
            }
        }
        return true;
    }

    private boolean b(ScriptCommand object) {
        boolean bl = false;
        if (((ScriptCommand)object).getNumericArguments()[7] == -1 || ((ScriptCommand)object).getNumericArguments()[7] != -1 && this.b[WorldManager.a((int)((ScriptCommand)object).getNumericArguments()[5], ((ScriptCommand)object).getNumericArguments()[6])] != null && this.b[WorldManager.a((int)((ScriptCommand)object).getNumericArguments()[5], ((ScriptCommand)object).getNumericArguments()[6])][((ScriptCommand)object).getNumericArguments()[7]] == 3) {
            switch (((ScriptCommand)object).getNumericArguments()[8]) {
                case 0: {
                    if (this.x.a((byte)((ScriptCommand)object).getNumericArguments()[9], ((ScriptCommand)object).getNumericArguments()[10]) != 2) break;
                    bl = true;
                    break;
                }
                case 1: {
                    if (!this.x.T[((ScriptCommand)object).getNumericArguments()[9]]) break;
                    bl = true;
                    break;
                }
                case 2:
                case 4: {
                    if (this.b[WorldManager.a((int)((ScriptCommand)object).getNumericArguments()[5], ((ScriptCommand)object).getNumericArguments()[6])] == null || this.b[WorldManager.a((int)((ScriptCommand)object).getNumericArguments()[5], ((ScriptCommand)object).getNumericArguments()[6])][((ScriptCommand)object).getNumericArguments()[7]] != 3) break;
                    bl = true;
                    break;
                }
                case 3: {
                    if (!this.x.b((int)((ScriptCommand)object).getNumericArguments()[9], (int)((ScriptCommand)object).getNumericArguments()[10], (byte)0)) break;
                    bl = true;
                    break;
                }
                case 5: {
                    if (this.x.F < ((ScriptCommand)object).getNumericArguments()[9]) break;
                    bl = true;
                    break;
                }
                case 6: {
                    int n;
                    object = new byte[]{0, 1, 2, 3};
                    block8: for (n = 0; n < this.x.partyPetCount; ++n) {
                        for (int i = 0; i < ((Object)object).length; ++i) {
                            if (object[i] == -1 || object[i] != GameDatabase.getValue((byte)0, (short)this.x.petParty[n].getPetId(), (byte)1)) continue;
                            object[i] = -1;
                            continue block8;
                        }
                    }
                    for (n = 0; n < ((Object)object).length && object[n] == -1; ++n) {
                    }
                    if (n < ((Object)object).length) break;
                    bl = true;
                }
            }
        }
        return bl;
    }

    public final void i() {
        NpcEntity npcEntity;
        WorldEntity worldEntity;
        ScriptCommand scriptCommand;
        int n;
        if (d == null) {
            d = new Vector();
        }
        d.removeAllElements();
        Vector<String> vector = new Vector<String>();
        for (n = 0; n < al.length; ++n) {
            if (WorldManager.a((int)al[n][0], al[n][1]) != WorldManager.a(WorldManager.a().f, WorldManager.a().g) || this.a[al[n][2]].getState() != 0 && this.a[al[n][2]].getState() != 4 || vector.contains("" + (scriptCommand = this.a[al[n][2]].getFirstCommand()).getNumericArguments()[4])) continue;
            if (this.b(scriptCommand)) {
                worldEntity = new WorldEntity();
                worldEntity.loadSprite(259, false);
                worldEntity.setAnimation((byte)1, (byte)-1, true);
                worldEntity.setPosition(this.w.d[scriptCommand.getNumericArguments()[4]].posX, this.w.d[scriptCommand.getNumericArguments()[4]].posY - 40);
                this.w.d[scriptCommand.getNumericArguments()[4]].t();
                npcEntity = this.w.d[scriptCommand.getNumericArguments()[4]];
                worldEntity.ownerEntity = npcEntity;
                worldEntity.activate();
                d.addElement(worldEntity);
                vector.addElement("" + scriptCommand.getNumericArguments()[4]);
                continue;
            }
            int n2 = OverworldScreen.c(scriptCommand.getNumericArguments()[0]);
            if ((scriptCommand.getNumericArguments()[1] != 0 || this.b[WorldManager.a((int)ak[n][0], ak[n][1])][ak[n][2]] != 3 || this.b[WorldManager.a((int)al[n][0], al[n][1])][al[n][2]] == 3) && (scriptCommand.getNumericArguments()[1] != 1 || n2 == -1 || s[n2][1] != 1)) continue;
            WorldEntity worldEntity2 = new WorldEntity();
            worldEntity2.loadSprite(259, false);
            worldEntity2.setAnimation((byte)15, (byte)-1, true);
            worldEntity2.setPosition(this.w.d[scriptCommand.getNumericArguments()[4]].posX, this.w.d[scriptCommand.getNumericArguments()[4]].posY - 40);
            this.w.d[scriptCommand.getNumericArguments()[4]].t();
            npcEntity = this.w.d[scriptCommand.getNumericArguments()[4]];
            worldEntity2.ownerEntity = npcEntity;
            worldEntity2.activate();
            d.addElement(worldEntity2);
            vector.addElement("" + scriptCommand.getNumericArguments()[4]);
        }
        for (n = 0; n < ak.length; ++n) {
            if (WorldManager.a((int)ak[n][0], ak[n][1]) != WorldManager.a(WorldManager.a().f, WorldManager.a().g) || this.a[ak[n][2]].getState() != 0 && this.a[ak[n][2]].getState() != 4 || vector.contains("" + (scriptCommand = this.a[ak[n][2]].getFirstCommand()).getNumericArguments()[4]) || !this.a(scriptCommand)) continue;
            worldEntity = new WorldEntity();
            worldEntity.loadSprite(259, false);
            worldEntity.setAnimation((byte)7, (byte)-1, true);
            worldEntity.setPosition(this.w.d[scriptCommand.getNumericArguments()[4]].posX, this.w.d[scriptCommand.getNumericArguments()[4]].posY - 40);
            this.w.d[scriptCommand.getNumericArguments()[4]].t();
            npcEntity = this.w.d[scriptCommand.getNumericArguments()[4]];
            worldEntity.ownerEntity = npcEntity;
            worldEntity.activate();
            d.addElement(worldEntity);
        }
    }

    public final int[] j() {
        int[] nArray = new int[4];
        int[] nArray2 = nArray;
        nArray[0] = this.ai.get(1);
        nArray2[1] = this.ai.get(2);
        nArray2[2] = this.ai.get(5);
        nArray2[3] = this.ai.get(11);
        return this.aj;
    }

    public final int[] k() {
        return this.aj;
    }

    public final void a(int[] nArray) {
        this.aj = nArray;
    }

    static {
        e = false;
        f = true;
        g = false;
        h = false;
        j = true;
        m = (byte)-1;
        s = null;
        t = 0;
        u = 0;
    }
}

