/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
package game;

import game.GameStateController;
import game.NpcEntity;
import game.OverworldScreen;
import game.Pet;
import game.WorldManager;
import java.util.Vector;

public final class Player
extends WorldEntity {
    private static Player instance;
    public int t;
    private int Z;
    private int aa;
    public byte u;
    private int ab;
    private boolean ac;
    public int v;
    private int ad;
    private int ae;
    public int w;
    public int x;
    public boolean y;
    public Pet[] petParty;
    public int partyPetCount;
    public byte[][] B;
    public byte[][] collectionFlags;
    public byte[][] collectionOrder;
    public byte[] E;
    public byte F;
    public byte G;
    public byte H;
    public byte I;
    public Vector J;
    public Vector K;
    public Vector L;
    public Vector M;
    public Vector N;
    public Vector O;
    public byte[] P;
    public byte[] Q;
    public short[] quickItemSlots;
    public Vector S;
    public boolean[] T;
    public static boolean U;
    public Vector V;
    private int gold;
    private int arenaPoints;
    public int[] elementStartIds = new int[]{0, 16, 32, 48, 64, 76, 88};
    public int[] elementSpeciesCounts = new int[]{16, 16, 16, 16, 12, 12, 12};
    private static byte[][] ah;
    private static short[][] ai;
    private Vector aj = null;

    public static Player getInstance() {
        if (instance == null) {
            instance = new Player();
        }
        return instance;
    }

    public final void releaseParty() {
        this.partyPetCount = 0;
        instance = null;
    }

    public Player() {
        int n;
        this.baseStats = new short[3];
        this.currentStats = new short[3];
        this.petParty = new Pet[6];
        this.B = new byte[8][2];
        this.T = new boolean[21];
        this.J = new Vector();
        this.K = new Vector();
        int[] nArray = new int[]{0, 0, 1};
        this.K.addElement(nArray);
        this.L = new Vector();
        this.M = new Vector();
        this.N = new Vector();
        this.O = new Vector();
        this.V = new Vector();
        this.collectionFlags = new byte[7][];
        this.E = new byte[7];
        this.collectionOrder = new byte[7][];
        this.quickItemSlots = new short[]{-1, -1, -1, -1, -1};
        for (n = 0; n < this.collectionOrder.length; ++n) {
            this.collectionOrder[n] = new byte[this.elementSpeciesCounts[n]];
            for (int i = 0; i < this.collectionOrder[n].length; ++i) {
                this.collectionOrder[n][i] = -1;
            }
        }
        this.collectionFlags[0] = new byte[16];
        this.collectionFlags[1] = new byte[16];
        this.collectionFlags[2] = new byte[16];
        this.collectionFlags[3] = new byte[16];
        this.collectionFlags[4] = new byte[12];
        this.collectionFlags[5] = new byte[12];
        this.collectionFlags[6] = new byte[12];
        this.P = new byte[4];
        this.Q = new byte[4];
        this.u = 0;
        for (n = 0; n < 8; ++n) {
            this.B[n][0] = 0;
            this.B[n][1] = 0;
        }
        for (n = 0; n < 4; ++n) {
            this.P[n] = 0;
        }
        this.gold = 1000;
        this.arenaPoints = 0;
        this.t = -1;
        this.y = false;
    }

    public final void a(short[] sArray) {
        short s;
        if (this.t == -1) {
            this.loadSprite(0, false);
        }
        this.h(this.t);
        this.posX = sArray[0];
        this.posY = sArray[1];
        this.b((byte)0, (byte)sArray[2]);
        this.baseStats[0] = s = sArray[3];
        this.baseStats[1] = s = sArray[4];
        this.baseStats[2] = s = sArray[5];
        if (this.t == -1) {
            this.resetCurrentStats();
        }
        this.s = 1;
        this.ad = sArray[6];
        this.ae = sArray[7];
        this.v = this.C();
        if (this.u == 1) {
            this.replaceSpriteImage(0, 107);
        }
        if (this.targetEntity == null) {
            this.targetEntity = new WorldEntity();
            this.targetEntity.loadSprite(337, false);
        }
        this.targetEntity.setPosition(this.posX, this.posY);
        if (this.spriteRenderer.spriteId == 4) {
            this.targetEntity.setAnimation((byte)0, (byte)0, false);
        } else {
            this.targetEntity.setAnimation((byte)1, (byte)0, false);
        }
        this.targetEntity.activate();
        this.ownerEntity = null;
        this.y = true;
    }

    public final void q() {
        if (this.isFollowing() && this.ownerEntity.getActionState() != 0) {
            this.updateFollowing(((WorldEntity)this.ownerEntity).spriteRenderer, this.spriteRenderer);
            return;
        }
        switch (this.actionState) {
            case 0: {
                if (this.P[2] == 2 || !this.N()) break;
                this.b((byte)3, this.facingDirection);
                return;
            }
            case 1: {
                if (this.P[2] == 2) {
                    boolean bl;
                    int n = this.posY;
                    int n2 = this.posX;
                    Player player = this;
                    switch (player.facingDirection) {
                        case 2: {
                            bl = MapEngine.getInstance().isOutOfBounds(n2, n - 25 - player.Z);
                            break;
                        }
                        case 0: {
                            bl = MapEngine.getInstance().isOutOfBounds(n2, n - 25 + player.Z);
                            break;
                        }
                        case 3: {
                            bl = MapEngine.getInstance().isOutOfBounds(n2 - player.Z, n - 25);
                            break;
                        }
                        case 1: {
                            bl = MapEngine.getInstance().isOutOfBounds(n2 + player.Z, n - 25);
                            break;
                        }
                        default: {
                            bl = false;
                        }
                    }
                    if (bl) break;
                    WorldManager.u = this.K();
                    this.ownerEntity = null;
                    for (int i = 0; i < WorldManager.a().d.length; ++i) {
                        this.w(i);
                    }
                    this.moveInFacingDirection(this.currentStats[0]);
                    this.aa = this.aa < 8 ? (this.aa += this.currentStats[0]) : 4;
                    this.O();
                    return;
                }
                WorldManager.u = this.K();
                if (this.L() && this.M()) {
                    this.moveInFacingDirection(this.Z);
                    this.aa = this.aa < 8 ? (this.aa += this.Z) : 4;
                    this.O();
                    return;
                }
                this.aa = 0;
                return;
            }
            case 2: {
                if (this.L() && this.M()) {
                    this.moveInFacingDirection(this.Z);
                    this.aa = this.aa < 8 ? (this.aa += this.Z) : 4;
                    this.O();
                    return;
                }
                this.aa = 0;
                return;
            }
            case 4: {
                return;
            }
            case 5: {
                int n;
                if (this.ab < 16) {
                    int n3;
                    switch (this.m) {
                        case 1:
                        case 3: {
                            if (this.m == 3) {
                                if (this.posX > this.ownerEntity.posX) {
                                    this.b(this.m);
                                }
                            } else if (this.posX < this.ownerEntity.posX) {
                                this.b(this.m);
                            }
                            if (this.l > this.ownerEntity.posY - 16) {
                                if (this.posY <= this.ownerEntity.posY - 16) {
                                    this.posY = n3 = this.ownerEntity.posY - 16;
                                    break;
                                }
                                this.b(2);
                                break;
                            }
                            if (this.l >= this.ownerEntity.posY - 16) break;
                            if (this.posY >= this.ownerEntity.posY - 16) {
                                this.posY = n3 = this.ownerEntity.posY - 16;
                                break;
                            }
                            this.b(0);
                            break;
                        }
                        case 0:
                        case 2: {
                            if (this.m == 2) {
                                if (this.posY > this.ownerEntity.posY - 16) {
                                    this.b(this.m);
                                }
                            } else if (this.posY < this.ownerEntity.posY - 16) {
                                this.b(this.m);
                            }
                            if (this.k > this.ownerEntity.posX) {
                                if (this.posX <= this.ownerEntity.posX) {
                                    this.posX = n3 = this.ownerEntity.posX;
                                    break;
                                }
                                this.b(3);
                                break;
                            }
                            if (this.k >= this.ownerEntity.posX) break;
                            if (this.posX >= this.ownerEntity.posX) {
                                this.posX = n3 = this.ownerEntity.posX;
                                break;
                            }
                            this.b(1);
                        }
                    }
                    if (this.ab % 4 == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(this.ab % 4), (byte)-1, false);
                    }
                    this.facingDirection = n3 = (int)(this.ab % 4);
                    ++this.ab;
                    return;
                }
                int n4 = 0;
                for (n = 0; n < ah.length; ++n) {
                    if (WorldManager.a().f != ah[n][0] || WorldManager.a().g != ah[n][1]) continue;
                    WorldManager.a().f = ah[n][2];
                    WorldManager.a().g = ah[n][3];
                    n4 = ah[n][4];
                    break;
                }
                for (n = 0; n < ai[n4].length / 4; ++n) {
                    if (((NpcEntity)this.ownerEntity).I < ai[n4][n << 2] || ((NpcEntity)this.ownerEntity).I > ai[n4][(n << 2) + 1]) continue;
                    WorldManager.a().h = ai[n4][(n << 2) + 2];
                    WorldManager.a().i = ai[n4][(n << 2) + 3];
                    break;
                }
                U = true;
                WorldManager.a().j = -1;
                GameStateController.getInstance().setScreenMode((byte)9);
                return;
            }
            case 6: {
                Player player = this;
                boolean bl = true;
                switch (player.facingDirection) {
                    case 3: {
                        bl = player.d(MapEngine.getInstance().getCollisionTile(player.posX - 16, player.posY));
                        break;
                    }
                    case 1: {
                        bl = player.d(MapEngine.getInstance().getCollisionTile(player.posX + 16, player.posY));
                        break;
                    }
                    case 2: {
                        bl = player.d(MapEngine.getInstance().getCollisionTile(player.posX, player.posY - 16));
                        break;
                    }
                    case 0: {
                        bl = player.d(MapEngine.getInstance().getCollisionTile(player.posX, player.posY + 16));
                    }
                }
                if (bl && MapEngine.getInstance().getCollisionTile(player.posX, player.posY) != 3 ? false : bl) {
                    this.moveInFacingDirection(this.baseStats[2]);
                    return;
                }
                this.moveInFacingDirection(this.currentStats[1]);
                this.b((byte)0, this.facingDirection);
                return;
            }
            case 7: {
                if (((NpcEntity)this.ownerEntity).z == 0) {
                    byte by;
                    if (this.ab < 7) {
                        this.moveInFacingDirection(4);
                        ++this.ab;
                        return;
                    }
                    if (this.ab != 7) break;
                    if (this.facingDirection == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation(this.facingDirection, (byte)-1, false);
                    }
                    this.facingDirection = by = this.facingDirection;
                    ((NpcEntity)this.ownerEntity).p();
                    ++this.ab;
                    return;
                }
                if (((NpcEntity)this.ownerEntity).z != 2) break;
                if (this.ab < 8 && this.ab > 0) {
                    this.moveInFacingDirection(4);
                    --this.ab;
                    return;
                }
                if (this.ab == 8) {
                    this.b((byte)7, this.facingDirection);
                    --this.ab;
                    return;
                }
                ((NpcEntity)this.ownerEntity).z = 0;
                ((NpcEntity)this.ownerEntity).ownerEntity = null;
                this.ownerEntity = null;
                this.b((byte)0, this.facingDirection);
                return;
            }
            case 8: {
                if (this.ab < 16) {
                    byte by;
                    if (this.ab % 4 == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(this.ab % 4), (byte)-1, false);
                    }
                    this.facingDirection = by = (byte)(this.ab % 4);
                    ++this.ab;
                    return;
                }
                int n = WorldManager.a().d[WorldManager.a().j].posX - WorldManager.a().d[WorldManager.a().j].posX % this.baseStats[2];
                int n5 = WorldManager.a().d[WorldManager.a().j].posY - WorldManager.a().d[WorldManager.a().j].posY % this.baseStats[2];
                this.setPosition(n, n5);
                this.targetEntity.setPosition(n, n5);
                this.b((byte)0, WorldManager.a().d[WorldManager.a().j].C);
                this.moveInFacingDirection(32);
                ParticleEffect.a().a(8);
                ParticleEffect.a().b();
                return;
            }
            case 9: {
                if (this.ab < 16) {
                    byte by;
                    if (this.ab % 4 == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(this.ab % 4), (byte)-1, false);
                    }
                    this.facingDirection = by = (byte)(this.ab % 4);
                    ++this.ab;
                    return;
                }
                int n = WorldManager.a().d[WorldManager.a().j].posX - WorldManager.a().d[WorldManager.a().j].posX % this.baseStats[2];
                int n6 = WorldManager.a().d[WorldManager.a().j].posY - WorldManager.a().d[WorldManager.a().j].posY % this.baseStats[2];
                this.setPosition(n, n6);
                this.targetEntity.setPosition(n, n6);
                this.b((byte)10, this.facingDirection);
                ParticleEffect.a().a(8);
                ParticleEffect.a().b();
                return;
            }
            case 10: {
                if (this.ab > 0) {
                    byte by;
                    if (this.ab % 4 == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(this.ab % 4), (byte)-1, false);
                    }
                    this.facingDirection = by = (byte)(this.ab % 4);
                    --this.ab;
                    return;
                }
                this.b((byte)0, WorldManager.a().d[WorldManager.a().j].C);
                this.moveInFacingDirection(32);
            }
        }
    }

    public final void b(byte by, byte by2) {
        block11: while (true) {
            switch (by) {
                case 0: {
                    if (this.P[2] != 2 && this.N()) {
                        by = (byte)3;
                        continue block11;
                    }
                    if (by2 == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation(by2, (byte)-1, false);
                    }
                    this.facingDirection = by2;
                    break block11;
                }
                case 1: {
                    if (this.P[2] != 2 && this.N()) {
                        by = (byte)2;
                        continue block11;
                    }
                    if (this.spriteRenderer.getAnimationId() < 6) {
                        if (by2 == 3) {
                            this.setAnimationAndDirection((byte)4, by2);
                            break block11;
                        }
                        this.setAnimationAndDirection((byte)(by2 + 3), by2);
                        break block11;
                    }
                    if (by2 == 3) {
                        this.setAnimation((byte)(by * 3 + 1), (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(by * 3 + by2), (byte)-1, false);
                    }
                    this.facingDirection = by2;
                    break block11;
                }
                case 2: {
                    if (this.N()) {
                        if (this.spriteRenderer.getAnimationId() < 9) {
                            if (by2 == 3) {
                                this.setAnimationAndDirection((byte)7, by2);
                            } else {
                                this.setAnimationAndDirection((byte)(by2 + 6), by2);
                            }
                        } else if (by2 == 3) {
                            this.setAnimation((byte)(by * 3 + 1), (byte)-1, false);
                        } else {
                            this.setAnimation((byte)(by * 3 + by2), (byte)-1, false);
                        }
                    } else if (by2 == 3) {
                        this.setAnimation((byte)(this.actionState * 3 + 1), (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(this.actionState * 3 + by2), (byte)-1, false);
                    }
                    this.facingDirection = by2;
                    break block11;
                }
                case 3: {
                    if (by2 == 3) {
                        this.setAnimation((byte)(by * 3 + 1), (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(by * 3 + by2), (byte)-1, false);
                    }
                    this.facingDirection = by2;
                    break block11;
                }
                case 4: {
                    this.setAnimation((byte)(by * 3), (byte)-2, false);
                    this.facingDirection = by2;
                    this.aa = 0;
                    break block11;
                }
                case 5: {
                    this.ab = 0;
                    this.m = by2;
                    int n = this.posY;
                    int n2 = this.posX;
                    Player player = this;
                    this.k = n2;
                    player.l = n;
                    if (by2 == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation(by2, (byte)-1, false);
                    }
                    this.facingDirection = by2;
                    break block11;
                }
                case 6: {
                    if (by2 == 3) {
                        this.setAnimation((byte)1, (byte)-1, false);
                    } else {
                        this.setAnimation(by2, (byte)-1, false);
                    }
                    this.facingDirection = by2;
                    break block11;
                }
                case 7: {
                    if (by2 == 3) {
                        this.setAnimation((byte)4, (byte)-1, false);
                    } else {
                        this.setAnimation((byte)(by2 + 3), (byte)-1, false);
                    }
                    this.facingDirection = by2;
                    break block11;
                }
                case 8:
                case 9: {
                    this.ab = 0;
                    this.facingDirection = by2;
                }
            }
            break;
        }
        this.actionState = by;
        if (this.actionState == 0 || this.actionState == 1) {
            if (WorldManager.a().o != null) {
                WorldManager.a().o.a(true);
                return;
            }
        } else if (WorldManager.a().o != null) {
            WorldManager.a().o.a(false);
        }
    }

    public final boolean f(int n) {
        return this.P[n] != 0;
    }

    public final boolean g(int n) {
        return this.Q[n] != 1;
    }

    public final boolean r() {
        return this.t != 2 || MapEngine.getInstance().getCollisionTile(this.posX + 7, this.posY + 7) == 0 && MapEngine.getInstance().getCollisionTile(this.posX - 8, this.posY - 8) == 0;
    }

    public final void h(int n) {
        if (n == -1) {
            return;
        }
        this.P[n] = 2;
        this.spriteRenderer.evictSprite();
        this.loadSprite(n + 1, false);
        if (this.u == 1) {
            this.replaceSpriteImage(1, 107);
        }
        this.b((byte)0, this.facingDirection);
        this.currentStats[0] = this.P[n] == 2 && n == 0 || this.P[n] == 2 && n == 1 ? 8 : 4;
        if (this.P[2] == 2 && WorldManager.a().o != null) {
            WorldManager.a().o.deactivate();
        }
        this.Z = this.currentStats[0];
        this.t = n;
    }

    public final void s() {
        int n;
        this.spriteRenderer.evictSprite();
        this.loadSprite(0, false);
        for (n = 0; n < 4; ++n) {
            if (this.P[n] != 2) continue;
            this.P[n] = 1;
        }
        if (this.u == 1) {
            this.replaceSpriteImage(0, 107);
        }
        if (WorldManager.a().o != null) {
            WorldManager.a().o.activate();
        }
        this.currentStats[0] = n = this.baseStats[0];
        this.t = -1;
    }

    public final void t() {
        this.u = 1;
        boolean bl = false;
        for (int i = 0; i < 4; ++i) {
            if (this.P[i] != 2) continue;
            bl = true;
            break;
        }
        if (bl) {
            this.replaceSpriteImage(1, 107);
            return;
        }
        this.replaceSpriteImage(0, 107);
    }

    public final void u() {
        this.u = 0;
        boolean bl = false;
        for (int i = 0; i < 4; ++i) {
            if (this.P[i] != 2) continue;
            bl = true;
            break;
        }
        if (bl) {
            this.replaceSpriteImage(1, 100);
            return;
        }
        this.replaceSpriteImage(0, 100);
    }

    private short K() {
        for (short s = 0; s < WorldManager.a().d.length; s = (short)((short)(s + 1))) {
            if (!WorldManager.a().d[s].isVisible() || WorldManager.a().d[s].spriteRenderer.spriteId > 85 && WorldManager.a().d[s].spriteRenderer.spriteId != 226 && WorldManager.a().d[s].spriteRenderer.spriteId != 92 && WorldManager.a().d[s].spriteRenderer.spriteId != 102 && WorldManager.a().d[s].spriteRenderer.spriteId != 137 || WorldManager.a().d[s].t != 0 || WorldManager.a().d[s].v != 1 && WorldManager.a().d[s].v != 18 || !this.a(WorldManager.a().d[s], this.spriteRenderer.k(), WorldManager.a().d[s].spriteRenderer.k())) continue;
            if (WorldManager.a().d[s].u() == 0) {
                WorldManager.a().a(WorldManager.a().d[s].posX, WorldManager.a().d[s].posY - 40, WorldManager.a().d[s]);
                if (WorldManager.a().d[s].G != null) {
                    WorldManager.a().d[s].G.deactivate();
                }
            } else if (WorldManager.a().d[s].u() == 1) {
                WorldManager.a().a(WorldManager.a().d[s].posX, WorldManager.a().d[s].posY - 40, WorldManager.a().d[s]);
                if (OverworldScreen.d != null && OverworldScreen.d.size() > 0) {
                    for (int i = 0; i < OverworldScreen.d.size(); ++i) {
                        if (!((WorldEntity)OverworldScreen.d.elementAt((int)i)).ownerEntity.equals(WorldManager.a().d[s])) continue;
                        ((WorldEntity)OverworldScreen.d.elementAt(i)).deactivate();
                        break;
                    }
                }
            } else {
                WorldManager.a().a(WorldManager.a().d[s].posX, WorldManager.a().d[s].posY - 40, WorldManager.a().d[s]);
                if (WorldManager.a().d[s].w != 0) {
                    WorldManager.a().d[s].w();
                }
            }
            return s;
        }
        WorldManager.a().e();
        OverworldScreen.g = false;
        return -1;
    }

    private boolean w(int n) {
        switch (WorldManager.a().d[n].t) {
            case 3: {
                short[] sArray = WorldManager.a().d[n].spriteRenderer.k();
                short s = sArray[0];
                short s2 = sArray[1];
                short s3 = (short)(sArray[2] + 16);
                short s4 = (short)(sArray[3] + 16);
                if (!WorldManager.a().d[n].u || !this.a(WorldManager.a().d[n], this.spriteRenderer.k(), new short[]{s, s2, s3, s4})) break;
                NpcEntity npcEntity = WorldManager.a().d[n];
                this.ownerEntity = npcEntity;
            }
        }
        return true;
    }

    private boolean L() {
        WorldEntity worldEntity = null;
        this.ownerEntity = null;
        int n = 1;
        if (this.aj != null) {
            this.aj.removeAllElements();
        }
        block24: for (int i = 0; i < WorldManager.a().d.length; ++i) {
            this.w(i);
            if (!WorldManager.a().d[i].u || !this.a(WorldManager.a().d[i], this.spriteRenderer.k(), WorldManager.a().d[i].spriteRenderer.k())) continue;
            switch (WorldManager.a().d[i].t) {
                case 0: {
                    switch (WorldManager.a().d[i].v) {
                        case 0: {
                            return false;
                        }
                        case 4:
                        case 11: {
                            if (WorldManager.a().d[i].getActionState() == 2 || !WorldManager.a().d[i].isVisible()) break;
                            worldEntity = WorldManager.a().d[i];
                            this.ownerEntity = worldEntity;
                            return false;
                        }
                        case 5: {
                            if (WorldManager.a().d[i].getActionState() != 2) {
                                if (this.B[5][0] == 2) {
                                    worldEntity = WorldManager.a().d[i];
                                    this.ownerEntity = worldEntity;
                                }
                                return false;
                            }
                        }
                        case 6: {
                            if (WorldManager.a().d[i].getActionState() == 2) break;
                            if (this.P[3] != 2) {
                                if (this.B[2][0] == 2) {
                                    worldEntity = WorldManager.a().d[i];
                                    this.ownerEntity = worldEntity;
                                    if (this.aj == null) {
                                        this.aj = new Vector();
                                    }
                                    this.aj.addElement(WorldManager.a().d[i]);
                                    WorldManager.a().d[i].f(20);
                                }
                                n = 0;
                                break;
                            }
                            WorldManager.a().d[i].d((byte)1);
                            WorldManager.a().b.c(WorldManager.a().d[i]);
                            break;
                        }
                        case 15: {
                            if (WorldManager.a().d[i].getActionState() == 2) break;
                            if (this.T[6]) {
                                worldEntity = WorldManager.a().d[i];
                                this.ownerEntity = worldEntity;
                                return false;
                            }
                            WorldManager.a().d[i].d((byte)1);
                            WorldManager.a().b.c(WorldManager.a().d[i]);
                            break;
                        }
                        case 7: {
                            if (WorldManager.a().d[i].getActionState() == 2) break;
                            if (this.P[3] != 2) {
                                if (this.B[1][0] == 2) {
                                    worldEntity = WorldManager.a().d[i];
                                    this.ownerEntity = worldEntity;
                                    if (this.aj == null) {
                                        this.aj = new Vector();
                                    }
                                    this.aj.addElement(WorldManager.a().d[i]);
                                    WorldManager.a().d[i].f(30);
                                }
                                n = 0;
                                break;
                            }
                            WorldManager.a().d[i].d((byte)1);
                            WorldManager.a().b.c(WorldManager.a().d[i]);
                            break;
                        }
                        case 8: {
                            byte by;
                            if (!WorldManager.a().d[i].isVisible()) break;
                            if ((NpcEntity)WorldManager.a().d[i].ownerEntity != null && ((NpcEntity)WorldManager.a().d[i].ownerEntity).B > ((NpcEntity)WorldManager.a().d[i].ownerEntity).A) {
                                return false;
                            }
                            block25: for (n = 0; n < WorldManager.a().d.length; ++n) {
                                if (!WorldManager.a().d[n].u || WorldManager.a().d[n].equals(WorldManager.a().d[i]) || WorldManager.a().d[n].t != 0 || WorldManager.a().d[n].v != 8 && WorldManager.a().d[n].v != 11) continue;
                                switch (this.facingDirection) {
                                    case 2: {
                                        if (!EngineUtils.a(WorldManager.a().d[i].posX, WorldManager.a().d[i].posY - 8, WorldManager.a().d[n].posX, WorldManager.a().d[n].posY, WorldManager.a().d[i].spriteRenderer.k(), WorldManager.a().d[n].spriteRenderer.k())) continue block25;
                                        return false;
                                    }
                                    case 0: {
                                        if (!EngineUtils.a(WorldManager.a().d[i].posX, WorldManager.a().d[i].posY + 8, WorldManager.a().d[n].posX, WorldManager.a().d[n].posY, WorldManager.a().d[i].spriteRenderer.k(), WorldManager.a().d[n].spriteRenderer.k())) continue block25;
                                        return false;
                                    }
                                    case 3: {
                                        if (!EngineUtils.a(WorldManager.a().d[i].posX - 8, WorldManager.a().d[i].posY, WorldManager.a().d[n].posX, WorldManager.a().d[n].posY, WorldManager.a().d[i].spriteRenderer.k(), WorldManager.a().d[n].spriteRenderer.k())) continue block25;
                                        return false;
                                    }
                                    case 1: {
                                        if (!EngineUtils.a(WorldManager.a().d[i].posX + 8, WorldManager.a().d[i].posY, WorldManager.a().d[n].posX, WorldManager.a().d[n].posY, WorldManager.a().d[i].spriteRenderer.k(), WorldManager.a().d[n].spriteRenderer.k())) continue block25;
                                        return false;
                                    }
                                }
                            }
                            WorldManager.a().d[i].d((byte)1);
                            WorldManager.a().d[i].facingDirection = by = this.facingDirection;
                            return false;
                        }
                        case 9: {
                            if (MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 2 || MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 1) {
                                return false;
                            }
                            if (this.facingDirection != 3 && this.facingDirection != 1) break;
                            this.ab = 0;
                            this.b((byte)7, this.facingDirection);
                            worldEntity = this;
                            WorldManager.a().d[i].ownerEntity = worldEntity;
                            worldEntity = WorldManager.a().d[i];
                            this.ownerEntity = worldEntity;
                            return false;
                        }
                        case 10: {
                            if (MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 2 || MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 1) {
                                return false;
                            }
                            if (this.facingDirection != 0 && this.facingDirection != 2) break;
                            this.ab = 0;
                            this.b((byte)7, this.facingDirection);
                            worldEntity = this;
                            WorldManager.a().d[i].ownerEntity = worldEntity;
                            worldEntity = WorldManager.a().d[i];
                            this.ownerEntity = worldEntity;
                            return false;
                        }
                        case 14: {
                            return false;
                        }
                        case 16: {
                            worldEntity = WorldManager.a().d[i];
                            this.ownerEntity = worldEntity;
                        }
                    }
                    continue block24;
                }
                case 3: {
                    return false;
                }
                case 1: {
                    if (WorldManager.a().d[i].v != 3) continue block24;
                    return false;
                }
            }
        }
        return n != 0;
    }

    private boolean M() {
        this.Z = this.currentStats[0];
        int n = this.posX - 8;
        int n2 = this.posY - 8;
        int n3 = this.posX + 7;
        int n4 = this.posY + 7;
        byte[] byArray = new byte[]{-1, -1, -1, -1, -1};
        switch (this.facingDirection) {
            case 2: {
                if (MapEngine.getInstance().isOutOfBounds(this.posX, n2 - this.Z)) {
                    return false;
                }
                byArray[0] = MapEngine.getInstance().getCollisionTile(n, n2 - this.Z);
                byArray[1] = MapEngine.getInstance().getCollisionTile(n3, n2 - this.Z);
                byArray[2] = MapEngine.getInstance().getCollisionTile(this.posX, n2 - this.Z);
                if (!this.d(byArray[0]) && !this.d(byArray[1])) {
                    if (MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 3) {
                        return false;
                    }
                    byArray[0] = MapEngine.getInstance().getCollisionTile(this.posX - 16, n2 - this.Z);
                    byArray[1] = MapEngine.getInstance().getCollisionTile(this.posX + 16, n2 - this.Z);
                    byArray[3] = MapEngine.getInstance().getCollisionTile(this.posX - 16, this.posY);
                    byArray[4] = MapEngine.getInstance().getCollisionTile(this.posX + 16, this.posY);
                    this.Z = this.currentStats[1];
                    if (!this.d(byArray[0])) {
                        return this.d(byArray[1], (byte)1);
                    }
                    if (!this.d(byArray[1])) {
                        return this.d(byArray[0], (byte)3);
                    }
                    if (this.d(byArray[4])) {
                        return this.d(byArray[1], (byte)1);
                    }
                    if (this.d(byArray[3])) {
                        return this.d(byArray[0], (byte)3);
                    }
                } else {
                    if (!this.d(byArray[0])) {
                        this.Z = this.currentStats[1];
                        return this.d(byArray[1], (byte)1);
                    }
                    if (!this.d(byArray[1])) {
                        this.Z = this.currentStats[1];
                        return this.d(byArray[0], (byte)3);
                    }
                    return this.d(byArray[2], (byte)2);
                }
            }
            case 0: {
                if (MapEngine.getInstance().isOutOfBounds(this.posX, n4 + this.Z)) {
                    return false;
                }
                byArray[0] = MapEngine.getInstance().getCollisionTile(n, n4 + this.Z);
                byArray[1] = MapEngine.getInstance().getCollisionTile(n3, n4 + this.Z);
                byArray[2] = MapEngine.getInstance().getCollisionTile(this.posX, n4 + this.Z);
                if (!this.d(byArray[0]) && !this.d(byArray[1])) {
                    if (MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 3) {
                        return false;
                    }
                    byArray[0] = MapEngine.getInstance().getCollisionTile(n - 16, n4 + this.Z);
                    byArray[1] = MapEngine.getInstance().getCollisionTile(n3 + 16, n4 + this.Z);
                    byArray[3] = MapEngine.getInstance().getCollisionTile(this.posX - 16, this.posY);
                    byArray[4] = MapEngine.getInstance().getCollisionTile(this.posX + 16, this.posY);
                    this.Z = this.currentStats[1];
                    if (!this.d(byArray[0])) {
                        return this.d(byArray[1], (byte)1);
                    }
                    if (!this.d(byArray[1])) {
                        return this.d(byArray[0], (byte)3);
                    }
                    if (this.d(byArray[4])) {
                        return this.d(byArray[1], (byte)1);
                    }
                    if (this.d(byArray[3])) {
                        return this.d(byArray[0], (byte)3);
                    }
                } else {
                    if (!this.d(byArray[0])) {
                        this.Z = this.currentStats[1];
                        return this.d(byArray[1], (byte)1);
                    }
                    if (!this.d(byArray[1])) {
                        this.Z = this.currentStats[1];
                        return this.d(byArray[0], (byte)3);
                    }
                    return this.d(byArray[2], (byte)0);
                }
            }
            case 3: {
                if (MapEngine.getInstance().isOutOfBounds(n - this.Z, this.posY)) {
                    return false;
                }
                byArray[0] = MapEngine.getInstance().getCollisionTile(n - this.Z, n2);
                byArray[1] = MapEngine.getInstance().getCollisionTile(n - this.Z, n4);
                byArray[2] = MapEngine.getInstance().getCollisionTile(n - this.Z, this.posY);
                if (!this.d(byArray[0]) && !this.d(byArray[1])) {
                    if (MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 3) {
                        return false;
                    }
                    byArray[0] = MapEngine.getInstance().getCollisionTile(n - this.Z, n2 - 16);
                    byArray[1] = MapEngine.getInstance().getCollisionTile(n - this.Z, n4 + 16);
                    byArray[3] = MapEngine.getInstance().getCollisionTile(this.posX, this.posY - 16);
                    byArray[4] = MapEngine.getInstance().getCollisionTile(this.posX, this.posY + 16);
                    this.Z = this.currentStats[1];
                    if (!this.d(byArray[0])) {
                        return this.d(byArray[1], (byte)0);
                    }
                    if (!this.d(byArray[1])) {
                        return this.d(byArray[0], (byte)2);
                    }
                    if (this.d(byArray[4])) {
                        return this.d(byArray[1], (byte)0);
                    }
                    if (this.d(byArray[3])) {
                        return this.d(byArray[0], (byte)2);
                    }
                } else {
                    if (!this.d(byArray[0])) {
                        this.Z = this.currentStats[1];
                        return this.d(byArray[1], (byte)0);
                    }
                    if (!this.d(byArray[1])) {
                        this.Z = this.currentStats[1];
                        return this.d(byArray[0], (byte)2);
                    }
                    return this.d(byArray[2], (byte)3);
                }
            }
            case 1: {
                if (MapEngine.getInstance().isOutOfBounds(n3 + this.Z, this.posY)) {
                    return false;
                }
                byArray[0] = MapEngine.getInstance().getCollisionTile(n3 + this.Z, n2);
                byArray[1] = MapEngine.getInstance().getCollisionTile(n3 + this.Z, n4);
                byArray[2] = MapEngine.getInstance().getCollisionTile(n3 + this.Z, this.posY);
                if (!this.d(byArray[0]) && !this.d(byArray[1])) {
                    if (MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 3) {
                        return false;
                    }
                    byArray[0] = MapEngine.getInstance().getCollisionTile(n3 + this.Z, n2 - 16);
                    byArray[1] = MapEngine.getInstance().getCollisionTile(n3 + this.Z, n4 + 16);
                    byArray[3] = MapEngine.getInstance().getCollisionTile(this.posX, this.posY - 16);
                    byArray[4] = MapEngine.getInstance().getCollisionTile(this.posX, this.posY + 16);
                    this.Z = this.currentStats[1];
                    if (!this.d(byArray[0])) {
                        return this.d(byArray[1], (byte)0);
                    }
                    if (!this.d(byArray[1])) {
                        return this.d(byArray[0], (byte)2);
                    }
                    if (this.d(byArray[4])) {
                        return this.d(byArray[1], (byte)0);
                    }
                    if (!this.d(byArray[3])) break;
                    return this.d(byArray[0], (byte)2);
                }
                if (!this.d(byArray[0])) {
                    this.Z = this.currentStats[1];
                    return this.d(byArray[1], (byte)0);
                }
                if (!this.d(byArray[1])) {
                    this.Z = this.currentStats[1];
                    return this.d(byArray[0], (byte)2);
                }
                return this.d(byArray[2], (byte)1);
            }
        }
        return true;
    }

    private boolean d(byte by) {
        switch (by) {
            case 1: {
                return false;
            }
            case 2: {
                return this.B[3][0] == 2;
            }
        }
        return true;
    }

    public final boolean a(NpcEntity npcEntity, short[] sArray, short[] sArray2) {
        if (sArray2 == null) {
            return false;
        }
        switch (this.facingDirection) {
            case 3: {
                if (npcEntity.v == 14) {
                    return Player.a(npcEntity, sArray2, sArray, this.posX - this.currentStats[0], this.posY);
                }
                if (!EngineUtils.a(this.posX - this.currentStats[0], this.posY, npcEntity.posX, npcEntity.posY, sArray, sArray2)) break;
                return true;
            }
            case 1: {
                if (npcEntity.v == 14) {
                    return Player.a(npcEntity, sArray2, sArray, this.posX + this.currentStats[0], this.posY);
                }
                if (!EngineUtils.a(this.posX + this.currentStats[0], this.posY, npcEntity.posX, npcEntity.posY, sArray, sArray2)) break;
                return true;
            }
            case 2: {
                if (npcEntity.v == 14) {
                    return Player.a(npcEntity, sArray2, sArray, this.posX, this.posY - this.currentStats[0]);
                }
                if (!EngineUtils.a(this.posX, this.posY - this.currentStats[0], npcEntity.posX, npcEntity.posY, sArray, sArray2)) break;
                return true;
            }
            case 0: {
                if (npcEntity.v == 14) {
                    return Player.a(npcEntity, sArray2, sArray, this.posX, this.posY + this.currentStats[0]);
                }
                if (!EngineUtils.a(this.posX, this.posY + this.currentStats[0], npcEntity.posX, npcEntity.posY, sArray, sArray2)) break;
                return true;
            }
        }
        return false;
    }

    private static boolean a(NpcEntity npcEntity, short[] sArray, short[] sArray2, int n, int n2) {
        switch (npcEntity.spriteRenderer.getAnimationId()) {
            case 1: {
                if (!EngineUtils.a(npcEntity.posX + sArray[0], npcEntity.posY + sArray[1], sArray[2] + (npcEntity.A << 4), (int)sArray[3], n, n2, sArray2)) break;
                return true;
            }
            case 3: {
                if (!EngineUtils.a(npcEntity.posX + sArray[0] - (npcEntity.A << 4), npcEntity.posY + sArray[1], sArray[2] + (npcEntity.A << 4), (int)sArray[3], n, n2, sArray2)) break;
                return true;
            }
            case 2: {
                if (!EngineUtils.a(npcEntity.posX + sArray[0], npcEntity.posY + sArray[1] - (npcEntity.A << 4), (int)sArray[2], sArray[3] + (npcEntity.A << 4), n, n2, sArray2)) break;
                return true;
            }
            case 0: {
                if (!EngineUtils.a(npcEntity.posX + sArray[0], npcEntity.posY + sArray[1], (int)sArray[2], sArray[3] + (npcEntity.A << 4), n, n2, sArray2)) break;
                return true;
            }
        }
        return false;
    }

    private boolean N() {
        boolean bl = true;
        switch (this.facingDirection) {
            case 3: {
                bl = this.d(MapEngine.getInstance().getCollisionTile(this.posX - this.currentStats[0], this.posY));
                break;
            }
            case 1: {
                bl = this.d(MapEngine.getInstance().getCollisionTile(this.posX + this.currentStats[0], this.posY));
                break;
            }
            case 2: {
                bl = this.d(MapEngine.getInstance().getCollisionTile(this.posX, this.posY - this.currentStats[0]));
                break;
            }
            case 0: {
                bl = this.d(MapEngine.getInstance().getCollisionTile(this.posX, this.posY + this.currentStats[0]));
            }
        }
        if (bl && MapEngine.getInstance().getCollisionTile(this.posX, this.posY) != 2) {
            return false;
        }
        return bl;
    }

    private boolean d(byte by, byte by2) {
        switch (by) {
            case -1:
            case 0: {
                this.b((byte)1, by2);
                break;
            }
            case 1: {
                if (MapEngine.getInstance().getCollisionTile(this.posX, this.posY) == 2) {
                    this.b((byte)2, by2);
                }
                return false;
            }
            case 2: {
                if (this.d((byte)2)) {
                    this.b((byte)2, by2);
                    break;
                }
                return false;
            }
            case 3: {
                this.b((byte)6, by2);
            }
        }
        return true;
    }

    public final void v() {
        if (((NpcEntity)this.ownerEntity).getActionState() == 1) {
            WorldManager.a().interactionController.aw();
            WorldManager.a().interactionController.b("B\u1ea3o r\u01b0\u01a1ng n\u00e0y \u0111\u00e3 tr\u1ed1ng");
            return;
        }
        if (((NpcEntity)this.ownerEntity).v == 0) {
            ((NpcEntity)this.ownerEntity).d((byte)1);
            if (this.a(((NpcEntity)this.ownerEntity).F, (int)((NpcEntity)this.ownerEntity).D, (byte)((NpcEntity)this.ownerEntity).E)) {
                this.c(((NpcEntity)this.ownerEntity).F, ((NpcEntity)this.ownerEntity).D, (byte)((NpcEntity)this.ownerEntity).E);
                String string = null;
                if (((NpcEntity)this.ownerEntity).E == 0) {
                    string = BaseScreen.getString(GameDatabase.gameDatabase[4][((NpcEntity)this.ownerEntity).F][0]);
                } else if (((NpcEntity)this.ownerEntity).E == 2) {
                    string = BaseScreen.getString(GameDatabase.gameDatabase[3][((NpcEntity)this.ownerEntity).F][0]);
                }
                WorldManager.a().interactionController.a("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + string, (int)((NpcEntity)this.ownerEntity).D);
            } else {
                WorldManager.a().interactionController.av();
            }
            this.b((byte)0, this.facingDirection);
            return;
        }
        if (((NpcEntity)this.ownerEntity).v == 1) {
            if (this.b(17, 1, (byte)2)) {
                ((NpcEntity)this.ownerEntity).d((byte)1);
                this.d(17, 1, (byte)2);
                if (this.a(((NpcEntity)this.ownerEntity).F, (int)((NpcEntity)this.ownerEntity).D, (byte)((NpcEntity)this.ownerEntity).E)) {
                    this.c(((NpcEntity)this.ownerEntity).F, ((NpcEntity)this.ownerEntity).D, (byte)((NpcEntity)this.ownerEntity).E);
                    String string = null;
                    if (((NpcEntity)this.ownerEntity).E == 0) {
                        string = BaseScreen.getString(GameDatabase.gameDatabase[4][((NpcEntity)this.ownerEntity).F][0]);
                    } else if (((NpcEntity)this.ownerEntity).E == 2) {
                        string = BaseScreen.getString(GameDatabase.gameDatabase[3][((NpcEntity)this.ownerEntity).F][0]);
                    }
                    WorldManager.a().interactionController.a("\u0110\u1ea1t \u0111\u01b0\u1ee3c: " + string, (int)((NpcEntity)this.ownerEntity).D);
                } else {
                    WorldManager.a().interactionController.av();
                }
            } else {
                WorldManager.a().interactionController.au();
            }
            this.b((byte)0, this.facingDirection);
        }
    }

    public final boolean w() {
        if (this.ownerEntity == null) {
            return false;
        }
        if (((NpcEntity)this.ownerEntity).getActionState() == 0) {
            OverworldScreen.h = true;
            if (((NpcEntity)this.ownerEntity).v == 7 || ((NpcEntity)this.ownerEntity).v == 6) {
                for (int i = 0; i < this.aj.size(); ++i) {
                    NpcEntity npcEntity = (NpcEntity)this.aj.elementAt(i);
                    npcEntity.d((byte)1);
                    npcEntity.x();
                }
                this.aj.removeAllElements();
            } else if (((NpcEntity)this.ownerEntity).v != 16) {
                ((NpcEntity)this.ownerEntity).d((byte)1);
            }
            return true;
        }
        return false;
    }

    private static boolean a(int n, int n2, Vector vector) {
        for (int i = 0; i < vector.size(); ++i) {
            int[] nArray = (int[])vector.elementAt(i);
            if (nArray[0] != n) continue;
            return nArray[1] < 99;
        }
        return n2 <= 99;
    }

    private static boolean b(int n, int n2, Vector vector) {
        for (int i = 0; i < vector.size(); ++i) {
            int[] nArray = (int[])vector.elementAt(i);
            if (nArray[0] != n) continue;
            return nArray[1] - n2 >= 0;
        }
        return false;
    }

    private static boolean c(int n, int n2, Vector vector) {
        int[] nArray;
        for (int i = 0; i < vector.size(); ++i) {
            nArray = (int[])vector.elementAt(i);
            if (nArray[0] != n) continue;
            nArray[1] = nArray[1] + n2;
            if (nArray[1] >= 99) {
                nArray[1] = 99;
            }
            return true;
        }
        nArray = new int[]{n, n2, 0};
        vector.addElement(nArray);
        return false;
    }

    private static boolean d(int n, int n2, Vector vector) {
        for (int i = 0; i < vector.size(); ++i) {
            int[] nArray = (int[])vector.elementAt(i);
            if (nArray[0] != n) continue;
            nArray[1] = nArray[1] - n2;
            if (nArray[1] <= 0 && nArray[2] == 0) {
                vector.removeElementAt(i);
            }
            return true;
        }
        return false;
    }

    public final boolean a(int n, int n2, byte by) {
        switch (by) {
            case 0: {
                if (GameDatabase.gameDatabase[4][n][5] == 0) {
                    return Player.a(n, n2, this.K);
                }
                return Player.a(n, n2, this.J);
            }
            case 2: {
                if (n >= 12) {
                    return Player.a(n, n2, this.M);
                }
                n2 = n;
                Player player = this;
                for (by = 0; by < player.L.size(); by = (byte)(by + 1)) {
                    if (((int[])player.L.elementAt(by))[0] != n2) continue;
                    return false;
                }
                return true;
            }
        }
        return false;
    }

    public final boolean b(int n, int n2, byte by) {
        switch (by) {
            case 0: {
                if (GameDatabase.gameDatabase[4][n][5] == 0) {
                    return Player.b(n, n2, this.K);
                }
                return Player.b(n, n2, this.J);
            }
            case 2: {
                return Player.b(n, n2, this.M);
            }
        }
        return false;
    }

    public final boolean c(int n, int n2, byte by) {
        switch (by) {
            case 0: {
                if (GameDatabase.gameDatabase[4][n][5] == 0) {
                    return Player.c(n, n2, this.K);
                }
                return Player.c(n, n2, this.J);
            }
            case 2: {
                if (n >= 12) {
                    if (n == 17) {
                        return Player.c(n, n2 * 5, this.M);
                    }
                    return Player.c(n, n2, this.M);
                }
                n2 = n;
                Player player = this;
                int[] nArray = new int[]{n2, 0, 0};
                player.L.addElement(nArray);
                return true;
            }
        }
        return false;
    }

    public final boolean d(int n, int n2, byte by) {
        switch (by) {
            case 0: {
                if (GameDatabase.gameDatabase[4][n][5] == 0) {
                    return Player.d(n, n2, this.K);
                }
                return Player.d(n, n2, this.J);
            }
            case 2: {
                return Player.d(n, n2, this.M);
            }
        }
        return false;
    }

    public final int a(int n, byte by) {
        switch (by) {
            case 0: {
                if (GameDatabase.gameDatabase[4][n][5] == 0) {
                    for (int i = 0; i < this.K.size(); ++i) {
                        int[] nArray = (int[])this.K.elementAt(i);
                        if (nArray[0] != n) continue;
                        return nArray[1];
                    }
                } else {
                    for (int i = 0; i < this.J.size(); ++i) {
                        int[] nArray = (int[])this.J.elementAt(i);
                        if (nArray[0] != n) continue;
                        return nArray[1];
                    }
                }
                break;
            }
            case 2: {
                for (int i = 0; i < this.M.size(); ++i) {
                    int[] nArray = (int[])this.M.elementAt(i);
                    if (nArray[0] != n) continue;
                    return nArray[1];
                }
                break;
            }
        }
        return 0;
    }

    public final void x() {
        int[] nArray;
        int n;
        if (this.S == null) {
            this.S = new Vector();
        } else {
            this.S.removeAllElements();
        }
        for (n = 0; n < this.K.size(); ++n) {
            nArray = (int[])this.K.elementAt(n);
            if (GameDatabase.gameDatabase[4][nArray[0]][4] != 0) continue;
            this.S.addElement(nArray);
        }
        for (n = 0; n < this.J.size(); ++n) {
            nArray = (int[])this.J.elementAt(n);
            if (GameDatabase.gameDatabase[4][nArray[0]][4] != 0) continue;
            this.S.addElement(nArray);
        }
    }

    public final boolean i(int n) {
        int[] nArray;
        if (n == 0) {
            nArray = new int[]{n, 0, 0};
        } else {
            nArray = new int[]{n, 1, 0};
            if (n == 1 || n == 2 || n == 3 || n == 4) {
                this.P[n - 1] = 1;
            }
        }
        this.N.addElement(nArray);
        return true;
    }

    public final void c(int n, int n2) {
        int[] nArray;
        for (int i = 0; i < this.N.size(); ++i) {
            nArray = (int[])this.N.elementAt(i);
            if (nArray[0] != n) continue;
            nArray[2] = nArray[2] + n2;
            if (nArray[2] >= 99) {
                nArray[2] = 99;
            }
            return;
        }
        nArray = new int[]{n, 0, n2};
        this.N.addElement(nArray);
    }

    public final int d(int n, int n2) {
        if (0 < this.N.size()) {
            int[] nArray = (int[])this.N.elementAt(0);
            if (nArray[0] == n && (n == 7 || n == 9 || n == 8)) {
                if (nArray[1] <= 99) {
                    return 0;
                }
                return 1;
            }
            return -1;
        }
        if (n2 > 99) {
            return 1;
        }
        return -1;
    }

    public final boolean e(int n, int n2) {
        for (int i = 0; i < this.N.size(); ++i) {
            int[] nArray = (int[])this.N.elementAt(i);
            if (nArray[0] == n && (n == 7 || n == 9 || n == 8)) {
                this.petParty[n2].i((byte)n);
                if (nArray[2] > 0) {
                    nArray[2] = nArray[2] - 1;
                    this.N.setElementAt(new int[]{nArray[0], 0, nArray[2]}, i);
                } else if (nArray[2] <= 0) {
                    this.N.removeElementAt(i);
                }
                return true;
            }
            if (nArray[0] != n || nArray[1] != 0) continue;
            this.N.setElementAt(new int[]{nArray[0], 1, nArray[2]}, i);
            break;
        }
        return false;
    }

    public final void j(int n) {
        for (int i = 0; i < this.N.size(); ++i) {
            int[] nArray = (int[])this.N.elementAt(i);
            if (nArray[0] != n || nArray[1] != 1) continue;
            this.N.setElementAt(new int[]{nArray[0], 0, nArray[2]}, i);
            return;
        }
    }

    public final boolean k(int n) {
        for (int i = 0; i < this.N.size(); ++i) {
            int[] nArray = (int[])this.N.elementAt(i);
            if (nArray[0] != n || nArray[1] != 1) continue;
            return true;
        }
        return false;
    }

    public final boolean l(int n) {
        for (int i = 0; i < this.L.size(); ++i) {
            int[] nArray = (int[])this.L.elementAt(i);
            if (nArray[0] != n) continue;
            nArray[1] = 0;
            return true;
        }
        return false;
    }

    public final void f(int n, int n2) {
        short s;
        boolean bl;
        int[] nArray;
        Player player;
        int n3;
        block7: {
            if (this.petParty[n2].baseStats[5] >= 0) {
                this.l(this.petParty[n2].baseStats[5]);
                this.petParty[n2].baseStats[5] = -1;
            }
            n3 = 0;
            player = this;
            for (n3 = 0; n3 < player.L.size(); ++n3) {
                nArray = (int[])player.L.elementAt(n3);
                if (nArray[0] != n || nArray[1] != 1) continue;
                bl = true;
                break block7;
            }
            bl = false;
        }
        if (bl) {
            this.l(n);
            boolean bl2 = false;
            for (n3 = 0; n3 < this.partyPetCount; ++n3) {
                if (this.petParty[n3].baseStats[5] != n) continue;
                this.petParty[n3].baseStats[5] = -1;
                bl2 = true;
                break;
            }
            if (!bl2) {
                for (n3 = 0; n3 < this.O.size(); ++n3) {
                    int[] nArray2 = (int[])this.O.elementAt(n2);
                    if (nArray2[2] != n) continue;
                    nArray2[2] = -1;
                    break;
                }
            }
        }
        player = this;
        for (n3 = 0; n3 < player.L.size(); ++n3) {
            nArray = (int[])player.L.elementAt(n3);
            if (nArray[0] != n) continue;
            nArray[1] = 1;
            break;
        }
        this.petParty[n2].baseStats[5] = s = (short)n;
    }

    public final byte y() {
        if (this.partyPetCount < 6) {
            return 0;
        }
        if (this.O.size() < 100) {
            return 1;
        }
        return 2;
    }

    public final boolean z() {
        return this.O.size() < 100;
    }

    public final void a(int n, int n2, byte by, short s, int[] nArray) {
        this.petParty[this.partyPetCount] = new Pet();
        this.petParty[this.partyPetCount].initPet(n, n2, (short)-1, by, s, (byte)-1);
        this.petParty[this.partyPetCount].b(nArray);
        this.a((byte)this.petParty[this.partyPetCount].getSpeciesValue((byte)1), n, (byte)2);
        ++this.partyPetCount;
    }

    public final void a(int n, int n2, int n3, byte by, short s, int[] nArray) {
        this.petParty[this.partyPetCount] = new Pet();
        System.arraycopy(this.petParty, n, this.petParty, n + 1, this.partyPetCount - n);
        this.petParty[n] = null;
        this.petParty[n] = new Pet();
        this.petParty[n].initPet(n2, n3, (short)-1, by, s, (byte)-1);
        this.petParty[n].b(nArray);
        ++this.partyPetCount;
    }

    public final void a(int[] nArray) {
        this.petParty[this.partyPetCount] = new Pet();
        this.petParty[this.partyPetCount].initPet(nArray[0], nArray[1], (short)nArray[2], (byte)nArray[3], (short)nArray[4], (byte)nArray[5]);
        this.petParty[this.partyPetCount].restoreProgress((short)nArray[6], nArray[7], nArray[8]);
        int[] nArray2 = new int[nArray.length - 9];
        for (int i = 0; i < nArray2.length; ++i) {
            nArray2[i] = nArray[i + 9];
        }
        this.petParty[this.partyPetCount].b(nArray2);
        this.a((byte)this.petParty[this.partyPetCount].getSpeciesValue((byte)1), nArray[0], (byte)2);
        ++this.partyPetCount;
    }

    public final void m(int n) {
        this.petParty[n] = null;
        while (n < this.partyPetCount - 1) {
            this.petParty[n] = this.petParty[n + 1];
            this.petParty[n + 1] = null;
            ++n;
        }
        --this.partyPetCount;
    }

    public final void n(int n) {
        for (int i = 0; i < this.partyPetCount; ++i) {
            if (this.petParty[i].getPetId() != n) continue;
            this.m(i);
            return;
        }
    }

    public final boolean o(int n) {
        int n2 = 0;
        for (int i = 0; i < this.partyPetCount; ++i) {
            if (i == n || !this.petParty[i].isAlive()) continue;
            ++n2;
        }
        return n2 > 0;
    }

    public final int A() {
        int n;
        int[] nArray = new int[this.partyPetCount];
        for (n = 0; n < this.partyPetCount; ++n) {
            nArray[n] = this.petParty[n].baseStats[1] - this.petParty[n].currentStats[1];
        }
        n = nArray[0];
        for (int i = 1; i < nArray.length; ++i) {
            if (n >= nArray[i]) continue;
            n = nArray[i];
        }
        if (n == 0) {
            return -1;
        }
        return n;
    }

    public final void p(int n) {
        Pet pet = this.petParty[n];
        while (n > 0) {
            this.petParty[n] = this.petParty[n - 1];
            --n;
        }
        this.petParty[0] = pet;
    }

    public final void a(int n, int n2, byte by, short s, int n3, int n4, int[] nArray) {
        int[] nArray2 = new int[9 + nArray.length];
        int[] nArray3 = nArray2;
        nArray2[0] = n;
        nArray3[1] = n2;
        nArray3[2] = -1;
        nArray3[3] = by;
        nArray3[4] = s;
        nArray3[5] = -1;
        nArray3[6] = n3;
        nArray3[7] = 0;
        nArray3[8] = n4;
        System.arraycopy(nArray, 0, nArray3, 9, nArray.length);
        this.O.addElement(nArray3);
        this.a((byte)GameDatabase.gameDatabase[0][n][1], n, (byte)2);
    }

    public final void b(int[] nArray) {
        this.O.addElement(nArray);
        this.a((byte)GameDatabase.gameDatabase[0][nArray[0]][1], nArray[0], (byte)2);
    }

    public final void q(int n) {
        this.O.removeElementAt(n);
    }

    public final void r(int n) {
        Object object = this;
        Pet pet = new Pet();
        object = (int[])((Player)object).O.elementAt(n);
        pet.initPet((int)object[0], (int)object[1], (short)object[2], (byte)object[3], (short)object[4], (byte)object[5]);
        pet.restoreProgress((short)object[6], (int)object[7], (int)object[8]);
        int[] nArray = new int[((Object)object).length - 9];
        for (int i = 0; i < nArray.length; ++i) {
            nArray[i] = (int)object[i + 9];
        }
        pet.b(nArray);
        this.petParty[this.partyPetCount] = pet;
        ++this.partyPetCount;
        this.q(n);
    }

    public final void a(short s) {
        this.quickItemSlots[this.I] = s;
        this.I = (byte)(this.I + 1);
    }

    public final void a(byte by, byte by2, byte by3) {
        this.B[by][by2] = by3;
        if (this.B[0][0] == 2) {
            ScreenView.a().a(GameDatabase.getValue((byte)2, (short)0, (byte)5) / 2, GameDatabase.getValue((byte)2, (short)0, (byte)5) / 2);
        }
    }

    public final byte c(byte by, byte by2) {
        return this.B[by][by2];
    }

    public final void a(byte by, int n, byte by2) {
        boolean bl;
        block11: {
            Player player = this;
            for (int i = 0; i < player.E[by]; ++i) {
                if (player.collectionOrder[by][i] != n) continue;
                bl = false;
                break block11;
            }
            bl = true;
        }
        if (bl) {
            this.collectionOrder[by][this.E[by]] = (byte)n;
            byte by3 = by;
            this.E[by3] = (byte)(this.E[by3] + 1);
            if (by2 == 2) {
                this.F = (byte)(this.F + 1);
                if (GameDatabase.gameDatabase[0][n][22] == 2) {
                    this.G = (byte)(this.G + 1);
                } else if (GameDatabase.gameDatabase[0][n][22] == 1) {
                    this.H = (byte)(this.H + 1);
                }
            }
            this.collectionFlags[by][n - this.elementStartIds[by]] = by2;
            return;
        }
        if (this.a(by, n) <= 1) {
            if (by2 == 2) {
                this.F = (byte)(this.F + 1);
                if (GameDatabase.gameDatabase[0][n][22] == 2) {
                    this.G = (byte)(this.G + 1);
                } else if (GameDatabase.gameDatabase[0][n][22] == 1) {
                    this.H = (byte)(this.H + 1);
                }
            }
            this.collectionFlags[by][n - this.elementStartIds[by]] = by2;
        }
    }

    public final byte a(byte by, int n) {
        return this.collectionFlags[by][n - this.elementStartIds[by]];
    }

    public final void B() {
        this.ac = true;
    }

    public final int C() {
        if (WorldManager.a().f == 4 && WorldManager.a().g == 1) {
            return EngineUtils.randomRange(4, 8);
        }
        return EngineUtils.randomRange(this.ad, this.ae);
    }

    private void O() {
        if (WorldManager.a().M.h() || OverworldScreen.t == 0) {
            return;
        }
        --this.w;
        if (this.w <= 0) {
            WorldManager.a().q();
            this.w = 0;
        }
        --this.x;
        if (this.x == 0) {
            this.spriteRenderer.a(0);
            this.x = -1;
        }
        if (!WorldManager.a().c() || this.x > 0) {
            return;
        }
        if (this.ac && this.v > 0 && this.P[1] != 2 && this.P[3] != 2) {
            --this.v;
        }
    }

    public final boolean D() {
        return this.v <= 0;
    }

    public final int getGold() {
        return this.gold;
    }

    public final void addGold(int amount) {
        this.gold += amount;
    }

    public final void resetGold() {
        this.gold = 0;
    }

    public final boolean hasGold(int amount) {
        return this.gold >= amount;
    }

    public final int getArenaPoints() {
        return this.arenaPoints;
    }

    public final void addArenaPoints(int amount) {
        this.arenaPoints += amount;
    }

    public final void resetArenaPoints() {
        this.arenaPoints = 0;
    }

    public final boolean hasArenaPoints(int amount) {
        return this.arenaPoints >= amount;
    }

    public final boolean b(int n, int n2, int n3) {
        if (GameDatabase.gameDatabase[n3][n][4] == 0) {
            return this.hasGold(n2);
        }
        return this.hasArenaPoints(n2);
    }

    public final void initializeStarterPet() {
        this.a(68, 7, (byte)2, (short)2, new int[]{1, 40, 45});
        this.i(0);
    }

    public final boolean loadSprite(int n, boolean bl) {
        super.loadSprite(n, bl);
        if (this.x > 0) {
            this.spriteRenderer.a(1);
        }
        return true;
    }

    public final void J() {
        this.b((byte)0, this.facingDirection);
    }

    static {
        ah = new byte[][]{{9, 2, 9, 3, 0}};
        ai = new short[][]{{0, 3, 112, 256}};
    }
}

