/* Generated by tools/rebuild_reference.py from original/game.jar.
 * Readable reference only; not compiled by project.py.
 * Unmapped names and CFR warnings need further bytecode inspection.
 */
/*
 * Decompiled with CFR 0.152.
 */
package game;

import game.GameStateController;
import game.OverworldScreen;
import game.Player;
import game.ScriptEngine;
import game.WorldManager;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;

public final class TitleScreen
extends BaseScreen {
    private static TitleScreen a;
    private static int[] b;
    private static int c;
    private byte d = 0;
    private Image e;
    private Image f;
    private byte g = (byte)10;
    private int[][] h = new int[this.g][5];
    private int[] i = new int[]{28, 3, 21, 22, 50, 5, 17, 17};
    private byte j = (byte)30;
    private byte k = (byte)30;
    private boolean l = false;
    private int m = 0;
    private int[] n = new int[this.g];
    private int[] o = new int[]{3958719, 3958719, 3958719, 7248110, 7248110, 9943031};

    public static TitleScreen a() {
        if (a == null) {
            a = new TitleScreen();
        }
        return a;
    }

    public final boolean d() {
        this.interactionController = ScriptEngine.a();
        this.uiManager = UIManager.getInstance();
        this.interactionController.a(this);
        c = 0;
        b = isGameStarted ? new int[]{504, 503, 505, 506, 507, 508} : new int[]{503, 505, 506, 507, 508};
        if (this.e == null) {
            this.e = EngineUtils.loadImage("/data/img/", "img_833");
        }
        if (this.f == null) {
            this.f = EngineUtils.loadImage("/data/tex/", "menu");
        }
        this.c();
        this.setScreenMode((byte)0);
        return true;
    }

    private void c() {
        for (int i = 0; i < this.g; ++i) {
            this.h[i][0] = -EngineUtils.randomInt(this.j);
            this.h[i][1] = TitleScreen.getScreenHeight() + EngineUtils.randomInt(this.k);
            this.h[i][2] = EngineUtils.randomInt(2);
            this.h[i][3] = EngineUtils.randomRange(1, 5);
            this.h[i][4] = EngineUtils.randomRange(3, 5);
        }
    }

    private void e() {
        WorldManager.D = false;
        WorldManager.G = 0;
        OverworldScreen.f = true;
        WorldManager.x = false;
        WorldManager.a().f = 0;
        WorldManager.a().g = 0;
        if (WorldManager.a().M != null) {
            WorldManager.a().M.e();
        }
        if (WorldManager.a().c != null) {
            WorldManager.a().c.releaseParty();
        }
        if (this.interactionController != null) {
            this.interactionController.b();
        }
        Player.getInstance().y = false;
        isGameStarted = false;
        GameStateController.getInstance().setScreenMode((byte)9);
    }

    public final void b() {
        if (!this.inputEnabled) {
            return;
        }
        this.snapshotInput();
        switch (this.screenMode) {
            case 0: {
                TitleScreen titleScreen = this;
                if (titleScreen.isKeyPressed(16400)) {
                    if (--c < 0) {
                        c = b.length - 1;
                    }
                } else if (titleScreen.isKeyPressed(32832)) {
                    if (++c > b.length - 1) {
                        c = 0;
                    }
                } else if (titleScreen.isKeyPressed(196640)) {
                    if (isGameStarted) {
                        switch (c) {
                            case 0: {
                                TitleScreen titleScreen2 = titleScreen;
                                if (WorldManager.a().M != null) {
                                    WorldManager.a().M.e();
                                }
                                if (WorldManager.a().c != null) {
                                    WorldManager.a().c.releaseParty();
                                }
                                if (titleScreen2.interactionController != null) {
                                    titleScreen2.interactionController.b();
                                }
                                Player.getInstance().y = false;
                                GameStateController.getInstance().setScreenMode((byte)9);
                                GameStateController.getInstance().setScreenMode((byte)9);
                                break;
                            }
                            case 1: {
                                titleScreen.setScreenMode((byte)5);
                                break;
                            }
                            case 2: {
                                titleScreen.setScreenMode((byte)1);
                                break;
                            }
                            case 3: {
                                titleScreen.setScreenMode((byte)2);
                                break;
                            }
                            case 4: {
                                titleScreen.setScreenMode((byte)3);
                                break;
                            }
                            case 5: {
                                titleScreen.setScreenMode((byte)4);
                            }
                        }
                    } else {
                        switch (c) {
                            case 0: {
                                titleScreen.e();
                                break;
                            }
                            case 1: {
                                titleScreen.setScreenMode((byte)1);
                                break;
                            }
                            case 2: {
                                titleScreen.setScreenMode((byte)2);
                                break;
                            }
                            case 3: {
                                titleScreen.setScreenMode((byte)3);
                                break;
                            }
                            case 4: {
                                titleScreen.setScreenMode((byte)4);
                            }
                        }
                    }
                }
                titleScreen.interactionController.f();
                titleScreen = this;
                if (!titleScreen.l) break;
                ++titleScreen.m;
                if (titleScreen.m < 100) break;
                for (int i = 0; i < titleScreen.n.length; ++i) {
                    titleScreen.n[i] = 0;
                }
                titleScreen.m = 0;
                titleScreen.c();
                titleScreen.l = false;
                break;
            }
            case 1: {
                this.interactionController.t();
                break;
            }
            case 2: {
                this.interactionController.p();
                break;
            }
            case 3: {
                this.interactionController.r();
                break;
            }
            case 4: {
                if (this.isKeyPressed(131072)) {
                    GameStateController.getInstance().setScreenMode((byte)1);
                    break;
                }
                if (!this.isKeyPressed(262144)) break;
                this.setScreenMode((byte)0);
                break;
            }
            case 5: {
                if (this.isKeyPressed(131104)) {
                    WorldManager.a();
                    WorldManager.o();
                    this.e();
                    break;
                }
                if (!this.isKeyPressed(262144)) break;
                this.setScreenMode((byte)0);
                this.uiManager.closeUI("/data/ui/msgtip.ui");
            }
        }
        this.uiManager.update();
    }

    public final void b(Graphics graphics) {
        switch (this.screenMode) {
            case 0: {
                int n;
                if (this.f != null) {
                    graphics.drawImage(this.f, 0, 0, 20);
                }
                int n2 = TitleScreen.getScreenHeight() - 20;
                int n3 = (TitleScreen.getScreenWidth() - TitleScreen.getSmallFont().stringWidth(TitleScreen.getString(b[c]))) / 2;
                String string = TitleScreen.getString(b[c]);
                Graphics graphics2 = graphics;
                TitleScreen titleScreen = this;
                graphics2.setColor(titleScreen.o[titleScreen.d]);
                graphics2.drawString(string, n3, n2 - 1, 36);
                graphics2.drawString(string, n3, n2 + 1, 36);
                graphics2.drawString(string, n3 - 1, n2, 36);
                graphics2.drawString(string, n3 + 1, n2, 36);
                graphics2.setColor(0xFFFFFF);
                graphics2.drawString(string, n3, n2, 36);
                titleScreen.d = (byte)(titleScreen.d + 1);
                if (titleScreen.d >= 6) {
                    titleScreen.d = 0;
                }
                graphics2 = graphics;
                titleScreen = this;
                if (titleScreen.l) break;
                for (n = 0; n < titleScreen.g; ++n) {
                    graphics2.drawRegion(titleScreen.e, titleScreen.i[titleScreen.h[n][2] << 2], titleScreen.i[(titleScreen.h[n][2] << 2) + 1], titleScreen.i[(titleScreen.h[n][2] << 2) + 2], titleScreen.i[(titleScreen.h[n][2] << 2) + 3], 0, titleScreen.h[n][0], titleScreen.h[n][1], 20);
                    int[] nArray = titleScreen.h[n];
                    nArray[0] = nArray[0] + titleScreen.h[n][3];
                    int[] nArray2 = titleScreen.h[n];
                    nArray2[1] = nArray2[1] - titleScreen.h[n][4];
                    if (titleScreen.h[n][0] <= TitleScreen.getScreenWidth() && titleScreen.h[n][1] >= 0) continue;
                    int n4 = n;
                    titleScreen.n[n4] = titleScreen.n[n4] + 1;
                }
                for (n = 0; n < titleScreen.n.length && titleScreen.n[n] > 0; ++n) {
                }
                if (n < titleScreen.n.length) break;
                titleScreen.l = true;
                break;
            }
            case 1:
            case 2:
            case 3: {
                Graphics graphics3 = graphics;
                for (int i = 0; i < TitleScreen.getScreenHeight() / 20; ++i) {
                    if (i % 2 == 0) {
                        graphics3.setColor(10440998);
                    } else {
                        graphics3.setColor(12082732);
                    }
                    graphics3.fillRect(0, i * 20, TitleScreen.getScreenWidth(), 20);
                }
                break;
            }
            case 4: {
                graphics.setColor(0);
                graphics.fillRect(0, 0, TitleScreen.getScreenWidth(), TitleScreen.getScreenHeight());
                graphics.setColor(0xFFFFFF);
                graphics.drawString("B\u1ea1n c\u00f3 mu\u1ed1n tho\u00e1t kh\u00f4ng?", TitleScreen.getHalfWidth(), TitleScreen.getHalfHeight() - 10, 17);
                graphics.drawString("", 2, TitleScreen.getScreenHeight(), 36);
                graphics.drawString("Kh\u00f4ng", TitleScreen.getScreenWidth() - 2, TitleScreen.getScreenHeight(), 40);
            }
        }
        this.uiManager.render(graphics);
    }

    public final void f() {
        this.e = null;
        this.f = null;
        this.uiManager.releaseAll();
    }

    public final void setScreenMode(byte by) {
        this.screenMode = by;
        switch (by) {
            case 2: {
                this.interactionController.o();
                return;
            }
            case 3: {
                this.interactionController.q();
                return;
            }
            case 1: {
                this.interactionController.s();
                return;
            }
            case 0: {
                return;
            }
            case 5: {
                this.interactionController.H();
                this.interactionController.a("C\u00f3 ch\u1eafc ch\u1eafn x\u00f3a d\u1eef li\u1ec7u c\u0169 \u0111\u1ec3 ch\u01a1i m\u1edbi kh\u00f4ng?");
            }
        }
    }

    static {
        b = null;
    }
}

