#!/usr/bin/env python3
"""Regenerate readable reference symbols from original bytecode, never regex-edit Java.

Default: stage under build/readable-reference. --apply replaces the generated
reference tree only after an inverse remap proves code and asset preservation.
The intermediate JAR is for decompilation, never for playing or releasing.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
NAMES = ROOT / 'tools/reference-names.json'
EMULATOR = ROOT.parent / 'emulator/freej2me_plus.jar'
ORIGINAL = ROOT / 'original/game.jar'


def run(*args):
    subprocess.run(list(map(str, args)), check=True)


def descriptor(value, classes):
    # JVM descriptors, not Java text. No generic signatures occur in this JAR.
    import re
    return re.sub(r'L([^;]+);', lambda match: 'L' + classes.get(match[1], match[1]) + ';', value)


def regenerate(apply=False):
    expected = (ROOT / 'original/SHA256.txt').read_text().split()[0]
    if hashlib.sha256(ORIGINAL.read_bytes()).hexdigest() != expected:
        raise SystemExit('Original JAR changed; refusing to regenerate reference.')
    mapping = json.loads(NAMES.read_text())
    rows = [['class', old, new] for old, new in mapping['classes'].items()]
    for kind in ('field', 'method'):
        rows.extend([[kind, *entry] for entry in mapping[kind + 's']])
    rows.extend([['parameters', *entry[:3], *entry[3]] for entry in mapping['parameters']])
    if len({tuple(row[:4]) for row in rows}) != len(rows):
        raise ValueError('Duplicate symbol in naming registry')
    with tempfile.TemporaryDirectory(prefix='vqsv-readable-') as temp:
        stage = Path(temp)
        tsv = stage / 'names.tsv'
        tsv.write_text(''.join('\t'.join(row) + '\n' for row in rows), encoding='utf-8')
        run('javac', '--release', '8', '-encoding', 'UTF-8', '-cp', EMULATOR,
            '-d', stage, ROOT / 'tools/ReadableReference.java')
        classpath = os.pathsep.join([str(stage), str(EMULATOR)])
        readable = stage / 'readable.jar'
        run('java', '-cp', classpath, 'ReadableReference', ORIGINAL, tsv, readable)
        effective = Path(str(readable) + '.names.tsv').read_text()
        inverse = []
        for line in effective.splitlines():
            values = line.split('\t')
            if values[0] == 'class':
                inverse.append(['class', values[2], values[1]])
            else:
                kind, owner, name, desc, new = values
                inverse.append([kind, mapping['classes'].get(owner, owner), new,
                                descriptor(desc, mapping['classes']), name])
        reverse = stage / 'inverse.tsv'
        reverse.write_text(''.join('\t'.join(row) + '\n' for row in inverse))
        restored = stage / 'restored.jar'
        run('java', '-cp', classpath, 'ReadableReference', readable, reverse, restored)
        run('java', '-cp', classpath, 'ReadableReference', '--compare', ORIGINAL, restored)
        decompiled = stage / 'decompiled'
        run('java', '-jar', ROOT / 'tools/cfr-0.152.jar', readable,
            '--outputdir', decompiled, '--extraclasspath', EMULATOR, '--silent', 'true')
        paths = {new + '.java' for new in mapping['classes'].values()}
        actual = {p.relative_to(decompiled).as_posix() for p in decompiled.rglob('*.java')}
        if actual != paths:
            raise ValueError(f'Decompiled class set differs: {actual ^ paths}')
        for file in decompiled.rglob('*.java'):
            source = '\n'.join(line.rstrip() for line in file.read_text().splitlines()) + '\n'
            file.write_text('/* Generated by tools/rebuild_reference.py from original/game.jar.\n'
                            ' * Readable reference only; not compiled by project.py.\n'
                            ' * Unmapped names and CFR warnings need further bytecode inspection.\n'
                            ' */\n' + source, encoding='utf-8')
        (decompiled / 'names.tsv').write_text(effective, encoding='utf-8')
        summary = decompiled / 'summary.txt'
        lines = summary.read_text().splitlines()
        lines[0] = 'Summary for original/game.jar with tools/reference-names.json'
        summary.write_text('\n'.join(lines) + '\n', encoding='utf-8')
        destination = ROOT / ('reference/decompiled' if apply else 'build/readable-reference')
        destination.parent.mkdir(parents=True, exist_ok=True)
        # Generated tree: stage first; preserve the old tree if replacement fails.
        backup = destination.with_name(destination.name + '.previous')
        if backup.exists():
            raise SystemExit(f'Previous backup exists: {backup}; inspect it before replacing.')
        if destination.exists(): destination.rename(backup)
        try:
            shutil.copytree(decompiled, destination)
        except Exception:
            if destination.exists(): shutil.rmtree(destination)
            if backup.exists(): backup.rename(destination)
            raise
        if backup.exists(): shutil.rmtree(backup)
        if not apply:
            shutil.copyfile(readable, destination / 'readable-reference.jar')
        print(f'Generated {len(actual)} reference classes: {destination}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply', action='store_true', help='Replace reference/decompiled after verification')
    regenerate(parser.parse_args().apply)
